### ISSUE TITLE
Encrypted content on persistant storage with forgettable keys

### ISSUE THREAD

**Issue by alexandrestein** [simplex-chat/simplex-chat#1034]
Hello,

Because it can be hard to truly delete data from a persistant storage, have you consider encrypting all messages/piece of data with different keys with some kind of ratcheting or similar mechanism.

The threat model is like this: the police/attackers get your phone/computer. Deleted content can't be recovered even if part of the data persiste on the drive because the key does not exist anymore.

Similar to message ratcheting between contacts but just to save the content on persistant storage.

Some application has failed to properly delete messages in the past. (Session with IPhone)
This can lead to catastrophic situation.

**Comment by alexandrestein** [comment]
I'm not aware how SQLite is working internally. 
But I hope that if they have made a a dedicated DB to have data encrypted, I hope they have made sure that the keys are rotated and can't be recovered after deletion.

Thanks for your update, I'll to learn about SQLCipher.

**Comment by epoberezkin** [comment]
SQLcipher itself does not store the key, so it cannot rotate it. The application (or the user) should provide the key (or passphrase from which the key is derived) when the database is initialized.

**Comment by alexandrestein** [comment]
Yes the base key is on the application, true. 

But usually ciphers should never be called/used with the same key or nonce more than once. So usually every writes are done with a dedicated key/nonce. 
I was thinking about those keys in fact, not the master. But again I don't know how it works under the wood.

I'll educate myself on SQLcipher and maybe close the ticket on my own. 
Thanks for your feedback.

**Comment by alexandrestein** [comment]
Sorry I didn't express my idea properly.

Most ciphers algorithms need to be have a unique key and/or nonce. 
If the master key is used to generate deterministic keys/nonce, old message can still be recovered if the mater key is known. 

I still need to learn about SQLCipher but encrypting the all database don't seems to fix the issue in my mind. 
But having the saved messages encrypted is defensively a great step in that direction.

Kind regards.

**Comment by alexandrestein** [comment]
Which if I understand correctly does not address the threat I have in mind. 
That's not that critical, just an other step to lock every deleted stuff into an unrecoverable state no matter what happen to the device and the master key.

Thanks for your explanations.

**Comment by epoberezkin** [comment]
Can you please explain the difference? What specific scenario you are trying to address?

We had an idea of off-the-record conversations - I was wondering if it might be a fit?

**Comment by alexandrestein** [comment]
Threat model: illegal or confidential content been crack by authorities like the police or enterprise ready to spy emploies or competitors.

Users/humans generally use poor passwords and therefore secure content is "easy" to crack.

Authorities/enterprises have the knowledge and ressources to search into the persistant storage for deleted content.
Making all piece of information encrypted with unrecoverable keys resolve the issue.
Even if: 

- the user has a very poor password
- device malfunction not properly deleting content
- application/lib malfunction also 

I imagine that something needs to be persistently saved on the device to be able to decryption saved content. 
I don't have a design in mind. But, I think/believe that's possible to minimize the amount of data competent/talented people could extract from persistante storage.

It's a similar issue addressed by double-ratcheting (implemented into the app) but not regarding the transport/network but the storage.

Is it making sense?

**Comment by canary5** [comment]
So now on pixels it uses titan chip to securely store the keys?

**Comment by epoberezkin** [comment]
The key used to encrypt database passphrase is on TPM indeed, in case the passphrase is stored on the device. The passphrase cannot be on tpm as it needs to be passed to sqlcipher.

**Comment by shumvgolove** [comment]
Encrypted storage was implemented in https://github.com/simplex-chat/simplex-chat/pull/988
