### ISSUE TITLE
Cannot delete contact after they leave a group

### ISSUE THREAD

**Issue by Perelandra0x309** [simplex-chat/simplex-chat#1037]
I have two Simplex accounts:

Contact A: Android 11, SimpleX v3.2.1 (52)
Contact B: Fedora 36 KDE, SimpleX Chat v3.2.1

This is the sequence of events:

-Contact B (Fedora) sends Contact A (Android) their chat address
-Contact A uses "Connect via received link" to establish a connection
-Contact B accepts, and both are able to communicate in 1:1 chat
-Contact A is an admin in a group and sends invite to Contact B to be a "member"
-Contact B accepts, is able to communicate in group
-Contact B leaves group
-Contact A goes into their 1:1 chat and attempts to delete Contact B but gets the error:

> Can't delete contact!
> Contact [Contact B]! cannot be deleted, they are a member of the groups(s) [GroupName].

Contact A is a member of the group still and views the group info and Contact B is not listed as a member
Contact B uses the /groups command to verify they are no longer in the group

Current workaround is to clear the chat and set a contact name so I know which is the old one (I am changing server configs Contact B uses).

**Comment by epoberezkin** [comment]
Agreed, we will be improving it. I am considering to make a direct connection in the group optional - maybe a property of the group itself. Also it should be possible to delete the contact after they leave the group indeed.

**Comment by epoberezkin** [comment]
this is done now, you can delete contacts even while they are in groups
