### ISSUE TITLE
Buzz (empty) messages [feature request]

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1039]
I was thinking of an empty message, serving only as a signal, a buzz, as in "so what have you decided?" or "I'm thinking of you."

Basically SimpleX should allow the creation of an empty chat message for the sole purpose of alerting the recipient. Like a buzz or a trill, just to advice someone.

What are your thoughts on this? Could it be useful for you as well?

**Comment by epoberezkin** [comment]
Single space works like that :)
