### ISSUE TITLE
bug with sending file

### ISSUE THREAD

**Issue by kvn80** [simplex-chat/simplex-chat#104]
Hi
v0.4.0
simplex-chat-ubuntu-20_04-x86-64
on Manjaro

./simplex -d alice
./simplex -d tom
mkdir alice 
nano ./alice/file (wrote some text)

```# ./simplex -d alice
# /f @tom ./alice/file
use /fc 11 to cancel sending


# ./simplex -d tom
14:29 alice> sends file file (10 bytes / 10 bytes)
use /fr 11 [<dir>/ | <path>] to receive it
# /fr 11 ./tom
saving file 11 from alice to ./tom/file
started receiving file 11 (file) from alice
error receiving file: incorrect chunk size
```
received file with 0 byte

**Comment by epoberezkin** [comment]
thank you @kvn80 - we've not tested on this particular Linux distribution - it must be something system specific, as we have it working on Ubuntu/Mac/Windows... We will see if we can reproduce - thank you!

**Comment by epoberezkin** [comment]
actually, I think I know what might be the issue - it's never been tested with files smaller than the chunk size (about 7kb). Does it by any chance show the error `error receiving file: incorrect chunk size`? This is what I see when sending 10 bytes file...
