### ISSUE TITLE
[BUG] Speaker settings not working

### ISSUE THREAD

**Issue by ioiouaua** [simplex-chat/simplex-chat#1043]
When you call somebody only loudspeaker is working. When you tap on speaker icon nothing is changed.
GrapheneOS, Android 13
Google Pixel 6

**Comment by mika-nl** [comment]
Yes ,I see it also in android

**Comment by epoberezkin** [comment]
It does seem to work in android 11, but not in 12 indeed

**Comment by shumvgolove** [comment]
@ioiouaua Is the issue resolved?

**Comment by serdarth** [comment]
This issue occurs in recent versions on an   Xiaomi RedMi Note9S device.  OS: MIUI Android 10
