### ISSUE TITLE
Grouped photo submission (up to 9 pictures in one submission)

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1046]
I often have to send more than one photo to the recipient, but unfortunately SimpleX limits me to sending only one image at a time, even if I stay within the 8mb limit.

In my opinion, it would be useful to improve this aspect in the future.

**Comment by mika-nl** [comment]
I think it is working in android 4.1

**Comment by shumvgolove** [comment]
If issue still persist — please reopen.
