### ISSUE TITLE
building the code and getting this issue

### ISSUE THREAD

**Issue by abdullahkassim3** [simplex-chat/simplex-chat#1054]
ninja: error: '/Users/mobileprogramming/Downloads/simplex-chat-stable/apps/android/app/src/main/cpp/libs/arm64-v8a/libsimplex.so', needed by '/Users/mobileprogramming/Downloads/simplex-chat-stable/apps/android/app/build/intermediates/cxx/Debug/115bs5w5/obj/arm64-v8a/libapp-lib.so', missing and no known rule to make it

what would be the problem?

**Comment by AshishGrt** [comment]
we need .so files and they haven't pushed them bcoz they blocked it in gitignore file

**Comment by gaurav5800** [comment]
<img width="659" alt="Screenshot 2022-09-15 at 3 10 08 PM" src="https://user-images.githubusercontent.com/11702780/190371193-2fe5e645-a02a-4765-a4a9-8360633ad9ca.png">
I have complied Haskell libraries still getting error shown in image
