### ISSUE TITLE
[Request] Adding short description and image to pending invitation links

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1122]
By generating many invitation links (to a party for example) it may happen that we cannot remember which link is linked to a specific person, and as a result we will have many pending invitation links to which we nevertheless cannot give an identity.

Therefore, I ask for the possibility to add an image on the side (900x900) and a short description about who is the recipient of that invitation.

![Screenshot_2022-09-25-12-09-20-66_28ac417cb9c2b686fc9f487d569b4fc7 (1)](https://user-images.githubusercontent.com/113377431/192138370-dcfa8fe9-c0af-4452-afcd-ab83fe0e543d.jpg)

**Comment by epoberezkin** [comment]
I think image is an overkill, tbh - where would you get it from? The description makes sense - it's coming in v4.1 most likely.

**Comment by mika-nl** [comment]
Can you then also make a option to copy the link again.? So you can send it again  ?

**Comment by epoberezkin** [comment]
Yes, this is coming too in the same change

**Comment by epoberezkin** [comment]
this is done - both setting contact name and be able to re-share it, minus the images, which we are not planning
