### ISSUE TITLE
Visual Bug for Persian/Arabic Alphabet

### ISSUE THREAD

**Issue by Shahin-rmz** [simplex-chat/simplex-chat#1135]
Hello, 
Thanks for providing the app.
Because of recent political issues, there are lot of Iranians who are considering using Simplex.
There is a Problem with Persian right to left alphabet, where the time will mix up with first words.
Appreciate if you consider fixing the issue.
Best
![simplex](https://user-images.githubusercontent.com/32805117/192366618-aa7129c5-12ef-4e56-8571-35b2532c75b9.jpg)

**Comment by Shahin-rmz** [comment]
If you want to see an example text:
`تست `
‍‍‍`این یک تست بلند است`

**Comment by Icy-Thought** [comment]
Fixed in the upcoming version. (Check #1032)

**Comment by Shahin-rmz** [comment]
Thanks,
Issue closed. :)
