### ISSUE TITLE
Fixed domains and disposable invitation tickets: an idea to have both worlds

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1147]
I came up with an idea about the safe use of long-term (not one-time) addresses while minimizing problems.

My idea is of course to have a fixed domain (you can delete it and have a new one) to which I associate tickets (the pregenerated one-time invitation links).

Now since I can have more than one domain (alex-job... alex-friends, what you want) each domain will contain exactly the finite number of tickets you have decided to generate for it.

If a domain has run out of tickets it can no longer accept requests unless you generate more tickets again.

This allows you to have the convenience of a fixed domain on the one hand, and control over spam cases on the other.

By being able to have multiple domains, it is possible to customize the recipient targeting and consequently know for sure which domain the spam is coming from.

For example, if the domain alex-job receives out of 20 pregenerated tickets 19 of spam I can decide to close only that one, while I can leave all the others active.

Also, since tickets are a finite number determined by the user, it is possible to know in advance how many invitation tickets are left open.

What do you think about it?

Problems, critical issues, possible improvements, what goes, what doesn't...

**Comment by epoberezkin** [comment]
You lost me a bit… what’s a ticket? How does it link to domain? (Do you mean DNS domain, right? Or something else)
