### ISSUE TITLE
Countdown before deleting a contact

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1150]
This morning while trying to clean chats I mistakenly deleted a contact by mistaking the 'delete' function for 'clear'.

That said, I ask that a 5-second countdown be introduced before permanently deleting a contact or group to avert errors due to distraction.

Of course while the 5 seconds are running there must be the CANCEL button.

**Comment by kimg45** [comment]
Seems like it would be really annoying if you were trying to delete multiple at the same time. It already gives you a warning dialog when you delete a chat, I don't see a need for this.

**Comment by kimg45** [comment]
That's ok, just looking through at what could potentially be closed to clear out the issues a bit.

**Comment by kimg45** [comment]
If you don't think this should be added, could you close the issue?
