### ISSUE TITLE
SimpleX home server app (docker) for Citadel

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1161]
One of the great advantages of SimpleX protocol is that you can set up your own server to connect your client app.

To this end, Citadel (foss) was born, which aims through a Raspberry Pi4 to become an operating system for small home servers.

![app-store-5f94b694](https://user-images.githubusercontent.com/113377431/193439553-f0901933-a324-4c5f-8731-4dd00a014d4d.png)

It would be useful in this regard for SimpleX to look at this possibility as the fruit of two emerging entities that can combine their efforts.

Exactly like any OS, Citadel has its own apps that are like those of Umbrel, based on containers (docker).

https://runcitadel.space/

https://blog.runcitadel.space/

https://hub.docker.com/

https://www.docker.com/resources/what-container/

**Comment by shumvgolove** [comment]
Currently, it's not planned.

Closing.
