### ISSUE TITLE
[Bug] App crashes when click on a specific floating number

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1176]
If you write exatly 0.00001 in a chat, send it, and after click on it, SimpleX crashes. Always.

4.0.1(60) Android 12

![Screenshot_2022-10-05-23-59-46-84_28ac417cb9c2b686fc9f487d569b4fc7 (1)](https://user-images.githubusercontent.com/113377431/194172095-6639b311-adf9-4718-a081-b74d9eee0963.jpg)

**Comment by avently** [comment]
Looks like you don't have a system phone application, do you?
