### ISSUE TITLE
An idea for shortening invitation links

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1240]
We know that an invitation link is about 530 characters long, a little too long to fit into a text message or to be aesthetically pleasing to the eye.

If I have to include it in a job application people who see it immediately think of malware. This is inconvenient for both the sender and the receiver.

One possible solution is the creation of a support website that collects (maximum one year then they are destroyed) all user-generated invitation links.

Thus an address like https://simplex.chat/invitation/15c636b28465c083a3c472aa628f35581943ac24 can contain a much larger link.

In addition, the 530 characters could increase further if the invitation, intended as such, carried with it a message to be delivered to the recipient, a feature that may be added in the future.

**Comment by epoberezkin** [comment]
We are planning optional addresses indeed, based on a separate identity server - possibly, users will be able to choose between email based and random string addresses.

**Comment by andreasmjg** [comment]
What prevents a user from copy-pasting a Simplex address into any URL shortener?

For example: 

- mydomain.com/simplex ==> URL re-direct ==> Long 530 character simplex address
- tinyurl.com/mysimplex ==> URL re-direct ==> Long 530 character simplex address

As I understand, these addresses do not need to be kept private as the conversations that are created from the initial connection is severed from the initial address. 

Or did I misunderstand?

**Comment by epoberezkin** [comment]
4.3 will show short descriptions instead of links in the chats, the rest will be addressed with identity server late next year.
