### ISSUE TITLE
Messages from Android not sending at times

### ISSUE THREAD

**Issue by gitbq** [simplex-chat/simplex-chat#1264]
At times it takes time before the "sent" message shows a tick beside the message.
This can lead to the conversation being a little out of order.

As you can see in then pics, eventually the messages came through to the iphone.

![1027 SE messages](https://user-images.githubusercontent.com/47218763/198251251-65e05db6-68db-45b0-9b9e-f053f60dc222.jpg)
![1027 pix messages](https://user-images.githubusercontent.com/47218763/198251354-fc3c126f-3c81-4f4a-b6d2-b6023457a230.png)

I assume the tick indicates the message has been delivered.

**Comment by epoberezkin** [comment]
The tick indicates that the message was accepted by the server. Is it still the case? I'd love to look deeper - if you could connect via the chat I would ask questions to try to understand the reason.

App restart is likely to fix it, but it would be good to look at the problem while it's happening.

**Comment by gitbq** [comment]
It's only an occasional issue... Sometimes just takes a few minutes to connect to the server.

**Comment by epoberezkin** [comment]
4.2.1 should have a bit increased timeouts, so it should connect more reliably, I wonder if you’d see the difference.

Thank you!
