### ISSUE TITLE
QR code image link on https://app.simplex.chat/ doesn't correspond to repository link and fingerprint

### ISSUE THREAD

**Issue by paperony** [simplex-chat/simplex-chat#1300]
Apps that can be downloaded from a custom repository on F-Droid such as Bitwarden, Bromite, and Newpipe, have their custom repository QR code image link include both the repository link and fingerprint
![Screenshot_20221105-135912](https://user-images.githubusercontent.com/117518757/200119282-c20fd26a-a625-40cd-82e6-5f94df9a3e1d.png)
![Screenshot_20221105-140633](https://user-images.githubusercontent.com/117518757/200119283-2ef7db30-710e-41df-a495-b71c8d085032.png)

**Comment by epoberezkin** [comment]
Sorry, I don't understand the problem... This QR code does include the fingerprint - I just checked.

**Comment by epoberezkin** [comment]
please re-open if you have more information, closing for now
