### ISSUE TITLE
Is Simplex 4.2 Android App Compatible With Android 13?

### ISSUE THREAD

**Issue by PackMeister** [simplex-chat/simplex-chat#1345]
Continue having call-related issues with Simplex 4.1 and 4.2 on latest GrapheneOS which is based upon AOSP 13.

Does Simplex 4.2 work with the latest version 13 of Android or does it require a particular, lower version of Android?

**Comment by epoberezkin** [comment]
It does work on Andrpid 13 for me - do you have some issue there?

**Comment by epoberezkin** [comment]
going to close, but please re-open if there is some issue.

**Comment by PackMeister** [comment]
Was just trying to identify if Android 12 vs Android 13 compatibility might be the underlying issue as to why I've been unable to get Android 4.1 or 4.2 clients to sucessfully perform voice calls.

**Comment by epoberezkin** [comment]
What exactly happens?

**Comment by Lord-KA** [comment]
Maybe I have a related problem, LOS 20 (Android 13). When I make a call to a contact (contact is online and uses Android 11), they don't have any message or notification about it and can't anwser. When the same contact calls me, I see notification and can answer, but after that I get this screen and it freezes (call, not the app, I can end it and get back to the chat).
![image_2022_12_25_19_46_58](https://user-images.githubusercontent.com/43700614/209476020-401f70ef-ba7b-48b3-8bb9-7ad0508ef207.jpg)

**Comment by Lord-KA** [comment]
@epoberezkin?

**Comment by epoberezkin** [comment]
I don't think it's related to android version, more likely it's related to provider/server configuration.

What would help:
- try connecting via another provider (e.g., wifi, VPN)
- try using a different STUN/TURN server - there are many publicly available ones.
- debug your connection with our servers using this guide: https://github.com/simplex-chat/simplex-chat/blob/master/docs/WEBRTC.md#troubleshoot (our preset servers addresses are here, for example: https://github.com/simplex-chat/simplex-chat/blob/stable/packages/simplex-chat-webrtc/src/call.ts#L219)

**Comment by Lord-KA** [comment]
Seems to be fixed in 4.5, thank you!

**Comment by epoberezkin** [comment]
stupidly, we missed that WebRTC requires an explicit fallback to TCP in case UDP is blocked, it's not the default. And a lot of people have UDP blocked...
