### ISSUE TITLE
Setting an image for incognito profiles

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1352]
I have finally understood as incognito mode works, but I would like that I can have the possibility to set an image by myself or alternatively random generated by some images hosting services (royalty free).

I mean the circular image that show the profile avatar.

I would also like to be able to change the random name if I needed to.

**Comment by epoberezkin** [comment]
I think what you want needs to be addressed with supporting multiple user profiles - we plan them - not as part of incognito mode. The point of incognito mode is to create random one-off disposable identities you should not be configuring manually, as any manual configuration might reveal patterns, etc., simplifying correlation between multiple incognito profiles. For the same reason we do not plan allowing setting custom names on them.

The need to support multiple configurable identities within one app will be supported with separate user profiles in a single database - it is coming early next year!
