### ISSUE TITLE
General suggestions and questions

### ISSUE THREAD

**Issue by shumvgolove** [simplex-chat/simplex-chat#136]
First of all: thanks for the great project! It's really cool to see a true successor for IRC. Although it's in early stages, but current chat prototype works flawlessly, looking forward for mobile app.

While using the simplex-chat, I collected a few thoughts/suggestions:

- It would be great if `TAB` could autocomplete commands; subcommands; contacts; file and directory names when using `/f`; etc. and arrow keys to scroll past commands like in your favorite interactive shell.
- While we here: when user "drag'n'drops" file from file manager to terminal, file path contains trailing whitespace, so executing `/f <file_path> ` would fail. I guess it would make sense if simplex-chat just ignored this.
- Currently, simplex-chat prints everything (DMs, group messages, command output) in one window. Change TUI layout to something modular: split up chat to multiple tabs for each opened contact/group and create separate `main` tab for general info/command output. Something like [irssi](https://github.com/irssi/irssi) + [tiny](https://github.com/osa1/tiny) irc clients do:

![bitmap](https://user-images.githubusercontent.com/37271604/144128507-554f374b-e131-4771-a1eb-9ac8305c8e66.png)

So, above user input (which also shows current user in use) there's multiple opened tabs with different colors: ![#fbf1c7ff](https://via.placeholder.com/15/fbf1c7ff/000000?text=+) `#fbf1c7ff` means current tab, ![#fb4934ff](https://via.placeholder.com/15/fb4934ff/000000?text=+) `#fb4934ff` – you've been mentioned, ![#b16286ff](https://via.placeholder.com/15/b16286ff/000000?text=+) `#b16286ff` – there's new messages and ![#504945ff](https://via.placeholder.com/15/504945ff/000000?text=+) `#504945ff` – no messages. It's just a concept and if you have something on your mind already – feel free to ignore this  ;^)
- Changing TUI layout as suggested in previous section would require making some kind of bindings/shortcuts (like `left`/`right` arrow keys to change tabs). So, implementing configuration file with user settings, so user can change bindings and other stuff (like default simplex server) would be also great.
- Show past history and messages with date and time. It would be also ideal if chat history could be scrolled with `Ctrl+UP`/`Ctrl+DOWN` or similar.
- Implement new command `/contact` which would list all available users/groups to message.
- Currently, Linux releases contain dynamically linked executable, compiled in `glibc` environment, which makes it impossible to execute binary on systems with `musl` libc (like Alpine Linux). I was able to successfully compile fully statically-linked `simplex-chat` binary with Alpine Linux, so I think that shouldn't be too hard. Distributing such static binary will provide universal Linux coverage for both `glibc` and `musl` distributions.

And I've got a bunch of questions from user perspective:

1. Is it possible to find out which available public groups https://github.com/simplex-chat/simplexmq/pull/143 (in the future) can I connect to? 
2. What is the difference between the current [E2EE algorithm](https://github.com/simplex-chat/simplexmq/blob/master/rfcs/2021-01-26-crypto.md#e2e-encryption) and the well-known protocols like [Signal Protocol](https://signal.org/docs/), [OMEMO](https://xmpp.org/extensions/xep-0384.html) and [Matrix Olm/Megaolm](https://gitlab.matrix.org/matrix-org/olm/-/tree/master/docs)?
3. What happens in the following scenario: I've created my `db` with user named `Alice` and chose SMP server `smp.example.com`. Then, I've executed `/c` and server generated ID (as described in [simplex queue](https://github.com/simplex-chat/simplexmq/blob/master/protocol/simplex-messaging.md#simplex-queue) if I was able to understand this correctly) for my connection. I've sent this invitation to `Bob` and we successfully  established connection. But then, after closing my client, I chose another SMP server `smp.example2.com`. Do i need to generate another `ID` for `smp.example2.com`  or `SMP` servers somehow exchange information between each other?

Well, that's all I've got.

**Comment by epoberezkin** [comment]
Thanks a lot for comments/questions!

> It would be great if TAB could autocomplete commands; subcommands; contacts; file and directory names when using /f; etc. and arrow keys to scroll past commands like in your favorite interactive shell.

great idea

> when user "drag'n'drops" file from file manager to terminal, file path contains trailing whitespace, so executing /f <file_path> would fail. I guess it would make sense if simplex-chat just ignored this.

That's super trivial to fix - I think we should just ignore trailing whitespace in all commands, including the messages. Are you interested in contributing that? Or we could just do that...

> Currently, simplex-chat prints everything (DMs, group messages, command output) in one window.

I did explore it, but it feels bad ROI, we are currently prioritising protocol improvements and mobile/desktop/web apps instead...
The complexity here that it requires managing terminal output in a much more involved way than we already do, and unicode characters that take more than one position make it really hard, so we probably won't do it unless we see some simpler way to do it...

> Implement new command /contact which would list all available users/groups to message.

It prints them on the start now, but it's a super simple thing to add - it just have to be some other command as I mostly use 1-2 letter command abbreviations... But maybe /contacts and /cs is fine to list contacts (similar to /members /ms)

> Currently, Linux releases contain dynamically linked executable, compiled in glibc environment, which makes it impossible to execute binary on systems with musl libc (like Alpine Linux). I was able to successfully compile fully statically-linked simplex-chat binary with Alpine Linux, so I think that shouldn't be too hard. Distributing such static binary will provide universal Linux coverage for both glibc and musl distributions.

If you could share what you did to compile we might be able to the CI build to include it. I do suspect that we would need a GitHub runner in this environment or to compile inside docker, so it might be a bit involved... But maybe you could contribute the script to GitHub CI...

> Is it possible to find out which available public groups open/public queue extension for SMP and SMP agent protocols simplexmq#143 (in the future) can I connect to?

This RFC is not implemented yet. I am prioritising a permanent contact links this week (and it would also change the link format). Public groups are a bit further down the line :)

> What is the difference between the current E2EE algorithm and the well-known protocols like Signal Protocol, OMEMO and Matrix Olm/Megaolm?

The current algorithm is an embarrassingly simple ad hoc hybrid scheme with RSA keys. It's secure the way it's constructed, but it does not provide forward secrecy in case of device break in. If an attacker retains encrypted messages (e.g. by compromising the server and retaining the copy of all traffic inside encrypted transport connection) and obtains the decryption key, they would be able to decrypt the messages. It can be mitigated by creating a new contact, exchanging the messages, and deleting this contact - that would remove the key from the device. Message queue rotation (that's not added yet) will also mitigate it.
But in any case, we will switch to double ratchet protocol very soon (that's what Signal and most messengers use) - it's a priority - it will provide message-level forward secrecy, at a cost of additional complexity.

The advantage over Signal is that the key exchange is always protected against man-in-the-middle attack. In case of Signal this protection is optional, and requires comparing key fingerprints after the connection is established. Also, there is no metadata privacy with Signal and other messengers.
Matrix E2E encryption is optional, it depends on the home server or client you use.

Hope it makes sense.

All these improvements will happen this/early next year, it is still a bit of a prototype, however stable and reliable. Once we stabilise the protocol there will be a security audit of the implementation.

**Comment by shumvgolove** [comment]
Thanks for your response!

> That's super trivial to fix - I think we should just ignore trailing whitespace in all commands, including the messages. Are you interested in contributing that? Or we could just do that...

If only I knew Haskell - then I would definitely helped, sorry! Currently learning some [Zig](https://ziglang.org/).

> The complexity here that it requires managing terminal output in a much more involved way than we already do, and unicode characters that take more than one position make it really hard

I think there's no simpler way to do it, unless there is some kind of `ncurses` library for Haskell. Goggle search gave me [brick](https://github.com/jtdaugherty/brick/) and [summoner](https://github.com/kowainik/summoner) libraries, maybe that could help you decide fate of TUI in `SimpleX-chat`? When I master `Zig` I could write SimpleX client with TUI, but that's gonna be in the far future :^)

> If you could share what you did to compile we might be able to the CI build to include it.

Yes, I'll share my steps (or maybe `dockerfile`) for building static binary when I get back home, but the process was a little tricky.

> I am prioritising a permanent contact links this week (and it would also change the link format). 

Wow, that's great news! Looking forward to it too.

> Message queue or encryption key rotation (neither is added yet) will also mitigate it, without any manual efforts.
But in any case, we will switch to double ratchet protocol very soon (that's what Signal and most messengers use) - it's a priority - it will provide message-level forward secrecy, at a cost of additional complexity.

Thanks for your clear response, much appreciate it.

---
And to answer to my own question:
> Q: What happens in the following scenario: I've created my `db` with user named `Alice` and chose SMP server `smp.example.com`. Then, I've executed `/c` and server generated ID (as described in [simplex queue](https://github.com/simplex-chat/simplexmq/blob/master/protocol/simplex-messaging.md#simplex-queue) if I was able to understand this correctly) for my connection. I've sent this invitation to `Bob` and we successfully  established connection. But then, after closing my client, I chose another SMP server `smp.example2.com`. Do i need to generate another `ID` for `smp.example2.com`  or `SMP` servers somehow exchange information between each other?

> A: You can still talk to people using default or any other server - it only affects the location of the message queue when you initiate the connection (and the reply queue can be on another server, as set by the other party's client) - [source](https://github.com/simplex-chat/simplex-chat#running-the-chat-client)

**Comment by epoberezkin** [comment]
> What happens in the following scenario: I've created my db with user named Alice and chose SMP server smp.example.com. Then, I've executed /c and server generated ID (as described in simplex queue if I was able to understand this correctly) for my connection. I've sent this invitation to Bob and we successfully established connection. But then, after closing my client, I chose another SMP server smp.example2.com. Do i need to generate another ID for smp.example2.com or SMP servers somehow exchange information between each other?

by chose, do you mean passing it via command line parameter? If so, then the server is per messaging queue, the command line parameter only defines the server(s) on which the new message queues are created (you can pass several servers, it will be chosen randomly every time). Once the queue is created it will not change the server. We will be adding queue rotation, so by changing the configured queues, they will be migrated to the new servers under the hood, but it is not implemented yet. The contacts themselves are only stored on your device, in the local database, server does not have this information.

**Comment by shumvgolove** [comment]
> by chose, do you mean passing it via command line parameter?

Yes.

> We will be adding queue rotation, so by changing the configured queues, they will be migrated to the new servers under the hood, but it is not implemented yet.

That's also great to hear!

**Comment by epoberezkin** [comment]
> by changing the configured queues

I meant configured servers, but you probably understood :))

**Comment by shumvgolove** [comment]
Well, here it is: my "franken-hacked-together" solution to statically compile `simplex-chat`:
```dockerfile
FROM alpine:latest
# Alpine Linux doesn't provide libtinfow.so.6 library, so we need to symlink it.
# Add essential packages for stack to work.
RUN apk add --no-cache \
    curl \
    git \
    xz \
    grep \
    ghc-dev \
    gmp-dev \
    zlib-static \
    zlib-dev \
    alpine-sdk &&\
    ln -s /usr/lib/libncursesw.so.6 /usr/lib/libtinfow.so.6

# Alpine Linux doesn't provide stack, so we need to get one.
RUN curl -LO https://get.haskellstack.org/stable/linux-x86_64.tar.gz &&\
    tar -xzf linux-x86_64.tar.gz stack-2.7.3-linux-x86_64/stack --strip-components 1 &&\
    rm linux-x86_64.tar.gz &&\
    mv stack /usr/local/bin/

RUN git clone https://github.com/simplex-chat/simplex-chat
WORKDIR ./simplex-chat

# To produce fully statically compiled build we need to add flags to the compiler and point resolver to use musl build of ghc.
# simplex-chat needs ghc 8.10.4, but Alpine has ghc 9.0.1
RUN sed -i '/      - -threaded/a\      - -O2\n\      - -static\n\    cc-options: -static\n\    ld-options: -static -pthread' package.yaml &&\
    printf 'setup-info:\n  ghc:\n    linux64-alpine:\n      8.10.4:\n        url: "https://github.com/redneb/ghc-alt-libc/releases/download/ghc-8.10.4-musl/ghc-8.10.4-x86_64-unknown-linux-musl.tar.xz"\n\nghc-build: alpine' >> stack.yaml

# Finally, compile the simplex-chat.
RUN stack install
```

**Comment by epoberezkin** [comment]
Thank you!

Btw, @shumvgolove we have just released v0.5 that has long term user addresses!

This is mine for the next 24 hours (we don't have any anti-spam measures yet!): https://simplex.chat/contact#/?smp=smp%3A%2F%2Fnxc7HnrnM8dOKgkMp008ub_9o9LXJlxlMrMpR-mfMQw%3D%40smp3.simplex.im%2F-nXTuuQe8jEennlR%23&e2e=rsa%3AMIIBoTANBgkqhkiG9w0BAQEFAAOCAY4AMIIBiQKCAQEA0lzByTOgtSCdC2if8hebe32xg3yoW4tc77bRL_S6BawiCjnMHOlri529cbbeRRTPBDdD61N3lPISEXsaMGIBw5rr9tgfbTpB3BnDtfIS_PcaHzdXlhn2WxBozZ8AQcbKx1K_f0cnVd6bZ6BsEPUHmuPinj7B0txKmWvgqWijMsU2wEO8RH0E3F_n84J7_at_MTKOViMuIEm2Xu5WuvIHLMZVjqhRpYhLKeWaUbg3jXLw98FOJ6GO4GDsSzaQi6wQuvtJ1I7ztneS7bTcdv-8-zmSYoECUC-cO0V-egiqTUbxI-bYQ15Gsr2j4S5WzYTxtA9x52ehPKjJqGg1miZ2DwKBgQCGmKriEIablxLvtOWksAk0cHEzQ-aXX0DRTFXsXnvge8d-cAwucTmGczfWIGKtfEJgQ5d4qiF9F60R5cnR63nSyyP_kvXNfcAnhidaGnqNsBM5GqmEh5lNR8rly1N5zHd7-hpbixWVUlAAsZdIC1MQ9Du62Qn-WqQyZXSdza4J2w%3D%3D

**Comment by shumvgolove** [comment]
That's great!

I've successfully statically compiled latest version of `simplex-chat` and sent you an invite.

**Comment by Poussinou** [comment]
@simplex-chat
While we wait for this app in F-Droid ( #437 ), and even if you have your own repo (now listed [here on F-Droid side](https://forum.f-droid.org/t/known-repositories/721)), could you please attach the apk to the [Release Section](https://github.com/simplex-chat/simplex-chat/releases) from now on, and for every new release ?
It'll be easier to update for people without your F-Droid repo, and maybe @IzzySoft can then easily take it in its own repo.

**Comment by IzzySoft** [comment]
If you let me know when it's there I can indeed take a look.

**Comment by epoberezkin** [comment]
Oh @Poussinou @IzzySoft  - this is really cool - thank you so much! I really appreciate your support.

I've just attached v3.0 APK (build 43) to the release here: https://github.com/simplex-chat/simplex-chat/releases/tag/v3.0.0

Please let me know where it would be, I will put the links to our page.

Thank you!!! 🙏

**Comment by IzzySoft** [comment]
Thanks @epoberezkin – and something I was afraid of (which is why I only committed to "take a look") is the app might go beyond the size limit of my repo, which is 30M per app. Unfortunately that fear seems to have been justified, and it's almost 6 times beyond :cry: But at least the other wish of @Poussinou is fulfilled, and the APK easier to find now ("releases" is the first place people usually look for the APK).

Usually at this point I ask whether a single-arch build would be possible, but I'm afraid that still would be beyond 50M…

**Comment by epoberezkin** [comment]
It's a single arch build... Haskell's binary size is not its strong side. We will be working to reduce it, but even 50Mb would be a big win, highly unlikely we can get it under 30Mb... Which is a shame, as Intel build is much much smaller than ARM...

**Comment by IzzySoft** [comment]
I won't argue about a single byte (30M is not a hard limit, 32M would be a more critical one for one of the APIs I use but for a few cases can work around though I prefer to keep those cases low). If you'd get below 32M that would be a huge win (literally) – I didn't dare hoping that would be possible. Keeping my :crossed_fingers: for you!

**Comment by epoberezkin** [comment]
v3.0.1 release: https://github.com/simplex-chat/simplex-chat/releases/tag/v3.0.1

**Comment by IzzySoft** [comment]
Hm, now we're at 180M for the Android APK… OK, I'll wait patiently and not yet lose hope :wink: :crossed_fingers:

**Comment by epoberezkin** [comment]
I’ve just posted the updated version :)

**Comment by IzzySoft** [comment]
Yeah, I figured it was not yet the "size optimized" one :smile: No worries, good things need time to be done right. So better have it done right than hastened :wink: Thanks!

**Comment by shumvgolove** [comment]
Closing as this has been answered.

**Comment by bambirombi** [comment]
Is there any plan for adding TAB auto-completion?

**Comment by alexandrestein** [comment]
Not that I'm aware of.
That would be really good.

**Comment by epoberezkin** [comment]
it's actually now done: https://github.com/simplex-chat/simplex-chat/pull/2125, coming in the next release.

It was a bit fiddly but seems quite useful :)
