### ISSUE TITLE
TUI improvement proposal

### ISSUE THREAD

**Issue by solus-hq** [simplex-chat/simplex-chat#1369]
Current CLI version of SimpleX is surely simple and usable, but I see room for improvement.

I don't know if CLI version is on priority list (personally wouldn't make it so), but there are powerful Go frameworks for building great TUI apps which are definitely looking luxury compared to most of the terminal apps.

You have to check out this:

https://github.com/charmbracelet/bubbletea

**Comment by shumvgolove** [comment]
Related https://github.com/simplex-chat/simplex-chat/issues/136

**Comment by epoberezkin** [comment]
@solus-hq we won't be making CLI app into a full TUI - some simple suggestions for additional commands are welcome though. There will be a fully-featured desktop UI next year.
