### ISSUE TITLE
Improve receiving files to retry in all cases

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1372]
![Screenshot_2022-11-15-14-45-13-48_28ac417cb9c2b686fc9f487d569b4fc7 (1)](https://user-images.githubusercontent.com/113377431/201935311-d40b9f0c-d205-4421-9f8a-9b71472e4b72.jpg)

Today I sent a small pdf (28kb) to my sister and she didn't able to download it.

It happens the same in the reverse mode.

Device A: Xiaomi Android 11 (SimpleX build 67)
Device B: OnePlus Nord 2T 5G Android 12 (SimpleX build 67)

**Comment by epoberezkin** [comment]
yes, we are aware of this problem - it happens when the file arrives when the connection is unstable. We will be fixing it in 4.4
