### ISSUE TITLE
Decide on encryption keys in the connection (same for all queues or one per queue)

### ISSUE THREAD

**Issue by efim-poberezkin** [simplex-chat/simplex-chat#138]
| Factor | One key for all queues | A key per queue |
--- | --- | ---
| Connection request size | **(+)** smaller | **(-)** bigger |
| Management complexity | **(+)** easier | **(-)** harder - need to manage pairs of DH exchanged keys per pair of queues inside the connection |
| Correlation of messages | **(-)** yes - same encrypted message can be correlated across queues and servers  | **(+)** no - encrypted messages will have different representation per queue |

**Comment by epoberezkin** [comment]
We could address the last point either by having different nonces or by using different sequential ratchet keys, it doesn't necessarily require separate DH exchanges.

Also, some correlation would still be possible via timing and the number of messages.

**Comment by epoberezkin** [comment]
double ratchet per connection, simple E2E crypto_box per queue (to avoid traffic correlation in multiple queues in connection inside TLS)
