### ISSUE TITLE
Feature request: Message to self in one contact

### ISSUE THREAD

**Issue by andreasmjg** [simplex-chat/simplex-chat#1383]
Currently message to self is possible by using the contact link and add myself as a contact.

However, then I see both sender and receiver as two separate chats in SimpleX.

It would be good to be able to recognize that both sender and receiver is myself - not sure if it's possible without giving away some info that could be analysed.

Thanks
A

**Comment by shumvgolove** [comment]
As @serrq suggested, you should just create an empty group with yourself.

Closing.
