### ISSUE TITLE
Is it normal that I can’t get into my contact settings panel while incognito in a certain group?

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1398]
I’ve always joined groups with a clear identity. However recently I wanted to try the incognito mode in a group and I realized with great surprise that I am unable to see which servers I am connected to, the name of the local database, etc., in short the personal panel.

Instead, I can visit that of the other members.

**Comment by epoberezkin** [comment]
Not sure I understand this correctly, do you mean that you cannot open the panel for yourself in the group? It’s not like there could be any server there, this incognito profile is still local to your device

**Comment by shumvgolove** [comment]
Closing then.
