### ISSUE TITLE
Question: Where do you get a secure channel?

### ISSUE THREAD

**Issue by NorfairKing** [simplex-chat/simplex-chat#141]
Basically this tweet: https://twitter.com/kerckhove_ts/status/1467490690984783873?s=20

**Comment by epoberezkin** [comment]
Replied in twitter: https://twitter.com/epoberezkin/status/1467586947111604233?s=21

As the other comment said, as long as you have an authenticated channel where you trust that you communicate with you think it is, it is good enough to establish a secure channel - the message you pass out of band can only be used once to establish the connection, and as long as the other party confirms it - it is secure.

A better tech doc and thread model is coming very soon a - in 2-3 weeks.

**Comment by NorfairKing** [comment]
> A better tech doc and thread model is coming very soon a - in 2-3 weeks.

NICE! I look forward to it. This could be a game-changing project and I sure hope it will be!

**Comment by epoberezkin** [comment]
@NorfairKing thank you :) We are working full time on it now, so it'll move much faster than before.

If I may ask - how did you find SimpleX Chat?

Anything you could do to "spread the word" - would massively help :)

**Comment by NorfairKing** [comment]
> If I may ask - how did you find SimpleX Chat?

The Haskell subreddit.
