### ISSUE TITLE
[CLI] Please write errors to stderr

### ISSUE THREAD

**Issue by kseistrup** [simplex-chat/simplex-chat#1516]
SimpleX for CLI has a habbit of writing a lot of errors messages, that can make if difficult to see what happened earlier in a conversation. To mitigate that I have, for a while, been launching SimpleX like this:

```sh
$ exec simplex-chat 2>/dev/null
```

However, I still see errors like these written to stdout:

```
server disconnected smpN.[…]
> exception: HandshakeFailed (Error_Misc "Network.Socket.[…]
server connected smpN.[…]
```

It would be nice to either have _all_ error messages written to stderr, or to be able to configure the loglevel manually.

This is:

*  **simplex-chat-ubuntu-20_04-x86-64**: v4.3.0

Cheers.

**Comment by epoberezkin** [comment]
I was just thinking today that we should do something about it. I have an account with lots of connections, many of which use their own servers, that can often be offline, so it is at the stage when like 80% of the screen is errors 🤦‍♂️

But I didn't want to spend any time on it if it's only me who's suffering :) Now I have an excuse ;)

**Comment by epoberezkin** [comment]
> exception: HandshakeFailed (Error_Misc "Network.Socket.[…]

This is the most annoying, and the least easy as it's from TLS library that doesn't seem to have logging config (or maybe I missed it)...

**Comment by kseistrup** [comment]
Great! :smile_cat:

**Comment by epoberezkin** [comment]
added log levels :) hopefully a bit less noisy, but probably not enough yet

**Comment by kseistrup** [comment]
Thanks, I appreciate your effords.

**Comment by kseistrup** [comment]
Which log level should I choose to get rid of the `server {,dis}connected smp*` messages? I've tried `error` and `important`, and neither seems to help.

If all error messages were written to standard error stream, as they should, it would be so easy to get rid of them.

**Comment by epoberezkin** [comment]
The problem with writing to stderr by default is that it would overwrite input area - both errors and normal messages use output logic that preserves the input area... So you only want to write errors to stderr in case you redirect them.

How about an option that would do that as non-default behaviour and accept filename?

**Comment by epoberezkin** [comment]
Re connected/disconnected are not even errors - they are some sort of network status events... possibly it should be another option to send them to errors or just suppress?

**Comment by kseistrup** [comment]
> Re connected/disconnected are not even errors - they are some sort of network status events... possibly it should be another option to send them to errors or just suppress?

Yes, that's where I started (with this issue). I don't feel they belong in the chat timeline and I had hoped that they were printed to stderr so I could redirect them and still see the chat. Unfortunately they are printed to stdout so they are impossible to get rid of with redirection. And the log levels also aren't helpful here.

> So you only want to write errors to stderr in case you redirect them.

That's what I tried initially: `simplex-chat 2>/dev/null`

> How about an option that would do that as non-default behaviour and accept filename?

I would be fine with such a solution.

**Comment by epoberezkin** [comment]
ok, I'll make an option to send all errors to a specified device/file. We cannot use stderr because we don't use stdout in a usual way too...

**Comment by epoberezkin** [comment]
didn't even take a year :)

It would still log all responses to console, even those that would be logged to file if they are events.

Easy to change the list of what goes to file if it was too much one way or the other, it's here: https://github.com/simplex-chat/simplex-chat/commit/901e62d6c17b42223beb49e181861aad1a51d576#diff-9c9e06d020a924e3258948187c1ce2d6de46b62d01effd25024190c30f86b3f9R492

**Comment by epoberezkin** [comment]
also if you enable --log-agent these will go to console, but they actually can be redirected with `2>>file` because they are logged to stderr.

**Comment by epoberezkin** [comment]
Please use `--log-file` option to define the file where these events would be logged. I am actually not sure if it'll work with /dev/null, we can look into it later if it doesn't, but it definitely works with a file.

**Comment by kseistrup** [comment]
Ah, `--log-file`. Thanks. Let me try…
