### ISSUE TITLE
[Discussion]  Multi-hop routing

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1532]
The idea came to me because it is present in Proton VPN.

This makes it difficult, if not impossible, to track a certain transmission or reception channel.

Currently we can configure one only tx and rx server.

What if each it makes bounced the packet to other SMP servers (if available) before delivering the message to the recipient?

So some hops for Tx, and some hops for Rx.
Totally optional, of course.

Would that be a security advantage?

PS: I want to add that I am a complete incompetent in IT and network, so take my considerations as simple curiosity of a non-expert person.

**Comment by epoberezkin** [comment]
That would make it more difficult to discover the message route, indeed, that's a classic mix network design. We consciously chose single-hop for several reasons:

1. simpler, lower latency, more reliable - so it's a better user experience, overall
2. servers do not need to be aware of other server existence - that provides better protection from network-wide attacks (as the network is simply a client-side consensus, on the server level there is simply no network).

The design you consider has its merits, but we believe that the current design is overall a better trade-off that the traditional mix-network with multi-hop nodes. Also, it's technically possibly to implement client-side mix network - somebody can do it - e.g. a client you run somewhere in the cloud can be programmed to forward messages to different clients, depending on the sender.

**Comment by chen-chan** [comment]
Why not just use it over I2P or Tor?

**Comment by alexandrestein** [comment]
Those tools on smartphones consume way too much power to be really partctical IMHO.
