### ISSUE TITLE
API for Sending Messages (Push Notifications)

### ISSUE THREAD

**Issue by Snake883** [simplex-chat/simplex-chat#1544]
I would like a feature for an API to send messages to a recipient.
I want to write a few lines of Python/Bash code to send messages/notifications/alerts to a recipient.

**Comment by mat-l** [comment]
Python binding would be great.
Would love to see them in the future. 🤩

**Comment by epoberezkin** [comment]
You already can execute simple commands via CLI parameters, you don't need language specific bindings for that.

You can `simplex-chat -e '@name hello!'` to send the message, and there is also -t option to increase the time CLI will be running (you need to increase it if network is slow or if you are sending to a large group, the default is 3 seconds which is usually more than enough to send the message to a single contact).

You can also use CLI as a web socket server, sending command strings and receiving JSON as the response. Language specific library in some language would make it simpler, of course, currently we have it only in TypeScript (and you can pick types from Kotlin/Swift code of mobile apps too).
