### ISSUE TITLE
Attachment - taking time to send

### ISSUE THREAD

**Issue by gitbq** [simplex-chat/simplex-chat#1562]
Attachments taking a long time to send.
7 minutes to receive 7mb video. 

It seems that after getting the notification of the message with the attachment, in order to receive / download the file, the source device also needs to be online at same time. Is that the correct behavior?

Once both devices are online it takes some time to send.

Both devices connected on 4g with fast connection speed. Streaming videos on YouTube was smooth. So transfer speed should not be a network problem. 

Preferred behaviour:
Transfer a bit faster.

Apologies if this is mentioned in the material somewhere.

Devices: 
pixel 4, android 13, Calyx
Iphone, ios16.

**Comment by shumvgolove** [comment]
Should be fixed with new release of `XFTP`.
