### ISSUE TITLE
Do not showing QR code on display when capturing

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1586]
This is a security improvement (maybe).

I saw a video on internet where a payment app during capturing only showed a circular ring that turned green (from red) when scanning went properly.

If this increase security, please implement in SimpleX.

**Comment by JakeTrock** [comment]
one could presumably use the ` [component].setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);` flags to prevent such action. It's meant to prevent screen capture as well as ADB tether capture

**Comment by epoberezkin** [comment]
Android already allows to prevent screenshots - need to check if it also prevents capturing

**Comment by JakeTrock** [comment]
I tested with ADB capture and screen record, both result in blackscreens so I'm pretty sure you're safe

**Comment by JakeTrock** [comment]
Ah so you mean like a button that displays the QR on press. That makes more sense

**Comment by epoberezkin** [comment]
I see what you are suggesting, but it is both complex to implement, and would complicate capturing, as you won't see if it's not in focus.

If you think that your screen can be compromised, then, equally, any other part of the device can be compromised too, including the camera, I don't think this measure achieves too much in terms of security, while it has obvious downsides.
