### ISSUE TITLE
Android build failing with dependencyResolutionManagement Error

### ISSUE THREAD

**Issue by floudwig** [simplex-chat/simplex-chat#1608]
I tried serveral times to build the apk with the Build-Android.sh in the scripts folder but it ends in the following error:

A problem occurred evaluating settings 'android'.
Could not find method dependencyResolutionManagement() for arguments [settings_d400q3j8rntyab1x0cvsegrb$_run_closure1@2e1f9339] on settings 'android' of type org.gradle.initializationDefaultSettings .

I tried to install gradle 7.2 since it seems you use it for your project but i cant solve this problem. 
Any ideas ?

**Comment by shumvgolove** [comment]
Building simplex-chat for android requires building from [`stable-nix-android`](https://github.com/simplex-chat/simplex-chat/commits/stable-nix-android) branch.

Try with: 
```sh
./scripts/android/build-android.sh bb4582109d119d4daf8081561b69504debdc573d
```

**Comment by floudwig** [comment]
Thanks for your quick answer. 

I tried to build it with the stable-nix-android branch which results in the next error:

`trace: WARNING: No materialized dummy-ghc-data.  mkdir /nix/store/rsjsp5bz9hgr09pxafdvbbhw7h1830v5-source/materialized/dummy-ghc/aarch64-unknown-linux-android-aarch64-unknown-linux-android-ghc-8.10.7-x86_64-linux

error: hash mismatch importing path '/nix/store/vwcx8k4j6w0cr25y626hsix2if21ic5w-source-repository-package';
         specified: sha256:1r8x0k3zcxyizh4045a6j1wqrzgpmyv0acxp8k78pnix134n52y2
         got:       sha256:04vczkgnbagk25h5xmmn6z2v1ds1jiyrxg9ikdiy0hi77ib7lk8m
         
error: some substitutes for the outputs of derivation '/nix/store/f32h510qiww8sjrxfaycypns7fqqq7lf-source-repository-package.drv' failed (usually happens due to networking issues); 
try '--fallback' to build derivation from source
error: 1 dependencies of derivation '/nix/store/xwly72mv53x6yhzw7vxlhn1j51s8n0q9-haskell-project-plan-to-nix-pkgs.drv' failed to build
`

What am i doing wrong here ?

**Comment by floudwig** [comment]
I tried it over and over again. I cant resolve this issue. 

Am i the only one with this problem or is there any known solution ?

I would love to try some improvements on tablets with this application but i cant even deploy the apk :/

**Comment by shumvgolove** [comment]
Hey, sorry for the late reply. Could you switch to `master` branch and run script from there? Like so:

```sh
git clone https://github.com/simplex-chat/simplex-chat
cd simplex-chat
git checkout master
./scripts/android/build-android.sh bb4582109d119d4daf8081561b69504debdc573d
```

**Comment by floudwig** [comment]
Hey, thanks for your reply. I tried to build it as you told me but this results in the first error again which says something like this:

A problem occurred evaluating settings 'android'.
Could not find method dependencyResolutionManagement() for arguments [settings_7urgyc5slxlvct2vo0kbti
3i$_run_closure1@736150a] on settings 'android' of type org.gradle.initializationDefaultSettings

Can you tell me which gradle version you are using ? maybe thats the problem. Thanks a lot !

**Comment by shumvgolove** [comment]
Please open a new issue if this persists, thanks!
