### ISSUE TITLE
Is it possible or in future (short-term) plans to increase the duration of voice notes?

### ISSUE THREAD

**Issue by tuqueque** [simplex-chat/simplex-chat#1610]
Hello.

First of all, this project has improved quite a lot! Congrats to the very competent dev team and I hope this project keeps improving as quickly as it has been so far! I've become very disappointed with the Session project. Their dev team is more focused in adding idiotic features, leaving already present ones full of bugs or with a sense of unfinished state.

Anyway, back to SimpleX (which, BTW, how should I pronounce it? "Simplex"?... "Simple Ex"?...)

I'm just getting familiar with this app, but me and all my contacts use voice notes A LOT, and it ends up being a deal breaker having such a limited time for voice notes. We need at least a 3-to-5-minute time limit for voice notes... Is it possible to increase the time limit? Personally, I don't care about the quality of the audio as long as the voice message is understandable.

As far as I know, the OPUS audio codec is currently a fantastic option, open source and present in pretty much all operanting systems. Maybe using OPUS instead of AAC and lowering the quality of the audio files could help increasing the time of voice notes without affecting the file size too much.

I really hope this can be done somehow, since this is untimately a deal breaker for me and my contacts.
Thank you in advance.

**Comment by grm34** [comment]
Absolutely agree, 43s is really short.

Full support on this project 👌

**Comment by epoberezkin** [comment]
We will be increasing it once XFTP support is rolled out (see the blog post about XFTP). The reason for the current limit is that voice messages must be 1-step async - that is, fully sent out without acceptance and can be fully received without the sender ever being online again (you know the problem with images and files, I assume). Old (current) files sub-protocol is multi-step async, so not good enough for larger voice files. XFTP on another hand is 1-step async for any size files, so increasing both the duration and quality of the voice messages won’t be a problem (and it’ll send much faster too).

**Comment by epoberezkin** [comment]
About the ETA - April or early May
