### ISSUE TITLE
Can we compute SHA256 of built binaries and include in release notes?

### ISSUE THREAD

**Issue by epoberezkin** [simplex-chat/simplex-chat#162]

**Comment by efim-poberezkin** [comment]
Theoretically we can with [hashFiles](https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles). For the chat we'd need to find an action (or create it ourselves, not sure it's worth it) to update release notes and test how the release behaves when multiple parallel jobs update it. Another option is to include in binary name but then we'd break install script
