### ISSUE TITLE
Feature request for adding support for offline end to end encrypted bluetooth messaging or even local wifi

### ISSUE THREAD

**Issue by nobaraos12** [simplex-chat/simplex-chat#1628]
Feature request for adding support for offline end to end encrypted bluetooth messaging or even local wifi

Use cases 

**- airline travel (airlines only allow imessage and whatapp on free wifi as they can monitor)**
- backcountry travel (no cellular service)
- conjested networks (helps relatively close communication when network speed is slow or unreliable) 

Update:
According to my recent search there is another app that does bluetooth messaging called briar https://briarproject.org/
this may help development. Note they seem to only have support for android and linux

_Originally posted by @nobaraos12 in https://github.com/simplex-chat/simplex-chat/discussions/1501_

"look forward to seeing how much interest there is - vote above!" - @epoberezkin

**Comment by epoberezkin** [comment]
please add any comments to the discussion you linked.

**Comment by ElsAr4e** [comment]
Just wanted to add this as a feature request. Like it possible using Briar: https://briarproject.org/how-it-works/

Or using Jami (https://jami.net/) you can make conversations without the internet (bluetooth not yet supported):
https://docs.jami.net/user/faq.html#can-i-use-jami-in-a-local-network-lan-without-internet-access
