### ISSUE TITLE
Some devices doesn't receive calls after latest update

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1665]
Two phones (Android 10, 11) with 4.4.2 aren't reachable after latest update.
Android 12 is ok. I am not sure if OS version is the reason.

**Comment by epoberezkin** [comment]
what was the previous version where it was working?

**Comment by ralaud** [comment]
Test 1: Two devices with Android 12, I receive calls. 

Test 2: One device Android 12 and one device Android 11, in both directions, I receive calls.

4.4-beta.4 (83)

Maybe it is just a simple bug and your call settings did just reset after update. I only receive calls on lock screen if I set to Accept.
![SimpleX-calls.png](https://user-images.githubusercontent.com/27868982/210134233-7f576291-4614-4465-a37b-75348e471f78.png)

**Comment by epoberezkin** [comment]
> I only receive calls on lock screen if I set to Accept.

Do you mean they don't even show up if you choose Show?

**Comment by ralaud** [comment]
> > I only receive calls on lock screen if I set to Accept.
> 
> Do you mean they don't even show up if you choose Show?

I did test this now with 4.4-beta4 (83) (both Android 12), it is showing now. Lastly I did test this on older 3.x.x version, when this did not work for me I switched to "Accept". Looks like showing calls does work now. Sorry for this confusion.

**Comment by shumvgolove** [comment]
Please reopen if issue persist, this should be fixed with latest releases.
