### ISSUE TITLE
Disappearing messages could make use of a "global timer"

### ISSUE THREAD

**Issue by x80486** [simplex-chat/simplex-chat#1688]
I see the newly releases `Disappearing Messages` feature. Looks like the main setting(s) for this are under `Chat Preferences` — although there is another "delete messages after` under `Database passphrase & export` which I thought it was related with the same.

The main hurdle I see is that I'm unable to set the "timer" this globally. Probably that's the intention, but I guess a global setting that could be overridden at the user level makes sense.

A small issue that I see is that I can enable the `Disappearing messages` globally, but when I check the contact preferences to set the "timer" for each, it's not really activated. Not sure if it's because the contacts don't allow it, or if it's something else...but only when I enable the setting there is that I can see the timer — defaults to `1 day`.

**Comment by epoberezkin** [comment]
The option in Database doesn’t delete messages for your recipients, it is only clearing your database locally - it’s independent from disappearing messages, whatever timer triggers sooner will delete the message locally.

Disappearing messages should be enabled per chat. The global setting in the user preferences, if enabled, would allow all your contacts to enable disappearing messages in the conversations with you, without requiring your confirmation.

Not sure there should be a global “time to disappear” setting, in any case - currently it’s not supported.

**Comment by x80486** [comment]
> The option in Database doesn’t delete messages for your recipients, it is only clearing your database locally - it’s independent from disappearing messages, whatever timer triggers sooner will delete the message locally.

OK, if I understand this correctly, the database setting is like a maintenance setting, where all the messages sent and received, for my device, will be remove after `X` amount of time, right?

If that's the case, it's going to be quite interesting to sync all the state if/when device sync is implemented in `SimpleX`.

> Disappearing messages should be enabled per chat. The global setting in the user preferences, if enabled, would allow all your contacts to enable disappearing messages in the conversations with you, without requiring your confirmation.

OK, got it. So it's my global opt-in setting just in case any contact enables that as well.

> Not sure there should be a global “time to disappear” setting, in any case - currently it’s not supported.

I think this should be really handy because it's going to be hard to set a default value that all users agree on, hence when we enable that setting, a default value is set, but I can see it, without inferring/remembering it on a per-user basics.

A global configuration guarantees that one can set the expected value (inherited by default across the board) for all conversations. If desired, could be overridden in the per-user setting.

**Comment by ltGuillaume** [comment]
>whatever timer triggers sooner will delete the message locally.

What happens if the "Delete messages after" triggers first on a disappearing message? Wil it still be removed for the recipient(s), too?

**Comment by epoberezkin** [comment]
> What happens if the "Delete messages after" triggers first on a disappearing message? Will it still disappear for the recipient(s), too?

Yes, of course. The devices have independent timers to “disappear” messages - on the sender’s device it starts when the message is sent (for live messages - once completed), on the recipient’s device - once the message is read (for live messages once both completed AND read). Local deletion via database settings has no effect on another device. It’s even possible that the message will be sent after it’s removed from your chat, e.g. if local deletion interval or time to disappear is less than the time you had no internet connection - that fact worries me a little bit, maybe we should do something more clever about unsent messages still in the local queue.

**Comment by ltGuillaume** [comment]
Timers are local, makes perfect sense. Thanks!
