### ISSUE TITLE
Public groups are important!

### ISSUE THREAD

**Issue by marco-trovato** [simplex-chat/simplex-chat#1693]
When a new user install the app is alone and there is nothing to do. Even I forgot about it and eventually uninstalled it.

Please make searchable public groups, it's the only way to find other people to talk to about a topic. Please add this feature, just like there is in Telegram, Revolt.chat, Matrix.org, XMPP, and IRC.

**Comment by theAkito** [comment]
One of the most annoying things is how easy it is to get spammed into public groups on Matrix. It's the worst thing about it.

I think, a traditional Instant Messaging model fits this type of app, perfectly.
