### ISSUE TITLE
Spanish interface

### ISSUE THREAD

**Issue by lsmor** [simplex-chat/simplex-chat#1713]
Hi there!

Are you willing to introduce a Spanish interface? I voluntee myself to make the translation if you give me some guidance. I've read in the contributing guidelines you use weblate for the task. I am not familiar with the tool, but sure it is easy.

btw: I am a native Spanish speaker

**Comment by lsmor** [comment]
Thanks for your answer. I've read that, I just wonder if they are willing to integrate it or not.

**Comment by sith-on-mars** [comment]
Spanish has been added on Weblate.

**Comment by epoberezkin** [comment]
It's updated now. Weblate and this repo inevitable go out of sync in many cases, and any update cycle requires fully re-setting weblate, as it doesn't understand squash commits (I don't want to merge these PRs:).
