### ISSUE TITLE
Error Adding Members on Group

### ISSUE THREAD

**Issue by neonota** [simplex-chat/simplex-chat#1717]
Hi ,
I was trying to invite someone to a group .. But got this weird error message... It was working fine few hours ago !
![SmartSelect_20230109-191904_SimpleX](https://user-images.githubusercontent.com/114842102/211552621-177aa818-dfb5-4c1f-9ed2-bb85b347a03b.jpg)

TIA

**Comment by epoberezkin** [comment]
What is the group name/full name/image? This error would happen when the message is bigger than allowed, which is strange in this case...

It would help if you could

1. Enable dev tools
2. Check group ID for console in group page
3. In chat console, enter the command: `/_group_profile #ID` (the ID is what you got in point 2)

If what it returns is not sensitive, please share it here, or maybe you can send via chat

**Comment by epoberezkin** [comment]
The workaround would be to remove/replace group image

**Comment by neonota** [comment]
Got it .. It was a issue with the Group Image .. What's the allowed size of Group PFP ?

**Comment by neonota** [comment]
It's really weird .. I even tried a image with the size of 7kb .. Still having the same issue .. Also the app frequently crashes whenever someone on Android 13 tries to join my group.. 

The Group Name : PrivacyHQ

**Comment by epoberezkin** [comment]
I believe it's fixed some time ago. Please open another one with the symptoms
