### ISSUE TITLE
Transmitting pictures with periodically notification

### ISSUE THREAD

**Issue by fightuntilwedie** [simplex-chat/simplex-chat#1730]
Hi,

I'm testing SimpleX with 2 devices (1xLOS 19, 1xLOS 20). Both devices use periodically notification since this does not drain the batteries. When I send a picture from one device only some kind of a bad picture preview arrives on the other device. When I click this preview I get a notification that the picture will be delivered when the other device is online. But nothing happens when the sending device is online and SimpleX is opened when I click the preview on the receiving device again.

This works perfectly when notifications on both devices are always active.

Is this an intentional behaviour? Afaik messages, pictures, files are being stored on servers until the receiving device can receive.

**Comment by epoberezkin** [comment]
I believe it's fixed in 4.4.1, commented on Reddit - thank you! closing here.
