### ISSUE TITLE
Unable to see group after join

### ISSUE THREAD

**Issue by x80486** [simplex-chat/simplex-chat#1742]
I've been joining and leaving (the English speaking) `SimpleX-Group` while testing some things.

After a couple of attempts I then tried to join using `Incognito` mode...but the application is telling me that `You are already connected to admin!`, though I don't see the group anymore.

I disabled `Incognito` mode and tried to do the same operation...but now I'm getting the same message. I thought that `SimpleX` would allow to join groups as `Incognito` :roll_eyes:

Moreover, it looks like somehow I'm locked into some group(s) I'm unable to leave :grimacing:

**Comment by x80486** [comment]
I did also try to join the other groups (Russian, French, etc.) in between, and I recap some error message about one of the `smp6` servers.

**Comment by x80486** [comment]
OK, I just leave the application to take a nap, and later on I was able to join the group, with my personal profile and in `Incognito` mode as well.

Looks like joining those groups needs approval from someone...or something around those lines.

**Comment by ltGuillaume** [comment]
Was the group you tried to join English SimpleX Support?

**Comment by x80486** [comment]
Yes, that's the one that gave me the trouble.

**Comment by ltGuillaume** [comment]
Apparently the client that handles the invitations was stuck for a while. It has been restarted a few hours ago.
