### ISSUE TITLE
[Feature Request] Show all media 

### ISSUE THREAD

**Issue by mika-nl** [simplex-chat/simplex-chat#1752]
I would like to see the option to see all media in A chat. So that it is easier to search back a picture or file .

Now you can scroll the media but only the bit (last 100 posts) that is loaded . this is perfect for just scrolling through just gotten pictures .

I would like to see an extra button where all media becomes visible.

**Comment by shumvgolove** [comment]
Duplicate of https://github.com/simplex-chat/simplex-chat/issues/1899
