### ISSUE TITLE
Gif Functionality or Giphy Support (Feature Request) 

### ISSUE THREAD

**Issue by powline99** [simplex-chat/simplex-chat#1754]
Can we get as a feature request Giphy (Gif) Support like Signal has which maintains privacy. Many of the other privacy chat apps have this: Session, Signal, etc. 

Here is a blog article: (https://signal.org/blog/giphy-experiment/)

> Giphy has API and an SDK (which is proprietary). For privacy reasons I would implement it using the API, similar to Signal (which is also open source).

**Comment by JakeTrock** [comment]
I'd generally think it'd be best to keep the responsibilities of the server as slim as possible here. Perhaps this would be a good feature in the future though if an extensions framework was added, where this responsibility could be passed off to some sort of bot that communicates via direct messages not visible to the user
