### ISSUE TITLE
Problem installing cli on ubuntu [self-resolved]

### ISSUE THREAD

**Issue by JakeTrock** [simplex-chat/simplex-chat#1762]
Hey all, just wanted to put this here in case you were getting the error `./simplex-chat-ubuntu-20_04-x86-64: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory` The solution is simple. 
1.) go [here](https://archlinux.org/packages/core/x86_64/openssl-1.1/) and click download mirror
2.) extract the tarfile locally, go to the directory that contains the "usr" folder
3.) run `sudo cp -rvu usr /`

[sidenote: it'd be nice in the future if this were packaged within the application]

**Comment by epoberezkin** [comment]
cc @shumvgolove 

yes, we will be adding static builds to CI

**Comment by i18nde** [comment]
Thank you for the hint, I upgraded Linux Mint to LMDE 6 (Faye) which is based on Debian 12 Bullseye, and encountered this error. So, not a long-lasting solution, but I can use SimpleX CLI.  ;-)

**Comment by qm3ster** [comment]
Current [simplex-chat-ubuntu-22_04-x86-64](https://github.com/simplex-chat/simplex-chat/releases/download/v5.8.1/simplex-chat-ubuntu-22_04-x86-64) does suffer from this.

**Comment by qm3ster** [comment]
~~I~~ the user was actually using the the [simplex-chat-ubuntu-20_04-x86-64](https://github.com/simplex-chat/simplex-chat/releases/download/v5.8.1/simplex-chat-ubuntu-20_04-x86-64), on Ubuntu 24.04. False alarm.
