### ISSUE TITLE
live message bug

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1765]
two or three seconds after the start of a live message, the app freezes completely and I can't press any buttons. only closing the app helps.
```
miui 13.0.5;
android 12;
ver. – 4.4.2.

**Comment by theAkito** [comment]
Works for me. Must be something specific on your system.

**Comment by epoberezkin** [comment]
It was indeed a bug in 4.4.2, it’s now fixed in 4.4.3 - closing
