### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1766]
```
offered Удаление для всех
```

English word in Russian translation (this is not normal)

translation: 
```
"delete for all" is requested
```

>my friend found this mistake, I pass it on to you.
>
>

this bug happens with ```all requests```.

**Comment by epoberezkin** [comment]
I think it might be fixed in 4.4.3 - could you please double check? Will check too

**Comment by epoberezkin** [comment]
you are right, it's fixed in iOS but not in Android

**Comment by epoberezkin** [comment]
fixed in PR, to be released in 4.4.4
