### ISSUE TITLE
customize the disappearance time of the message (feature request)

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1768]
I want to customize the time of the disappearing message when I long press the send button

almost all messengers (private) have implemented this. Why hasn't yours done it yet?
 ‌
 ‌
>updated:
>
>
concept of what happens when you long press the send button:

 ‌
A menu will appear:

**Destroying the message after:**

``` ``` ‌ ‌ ‌second(s)
``` ``` ‌ ‌ ‌minute(s)
``` ``` ‌ ‌ ‌hour(s)
``` ``` ‌ ‌ ‌day(s)
``` ``` ‌ ‌ ‌week(s)
``` ``` ‌ ‌ ‌month(s)
``` ``` ‌ ‌ ‌year(s)
unlimited

it will be possible to write any number in ‌ ‌``` ```

then you can choose one of the values.

this value will be the time after which the message will be deleted.

**Comment by epoberezkin** [comment]
Time is limited, so we have to prioritise :) Yes, we did consider it, and the protocol allows it - it’s a property of the message, so we might extend UI at some point to allow it.
