### ISSUE TITLE
Highlighting multiple messages as in Telegram (or in another style). feature request

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1769]
I'm tired of deleting messages one by one

```All``` the other messengers I use have multiple message highlighting. But you don't.

I propose to correct this.

>concept:
>
a weak click on the message will result in the usual dialog box. With a long press there should be a multiple selection

**Comment by albotroz** [comment]
I am also waiting for the possibility of multiple selection (for deleting, copying, forwarding) of messages within a chat.
