### ISSUE TITLE
Ability to change the language itself, in the application (feature request)

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1770]
sometimes the android is wrong;
sometimes it's just more convenient to speak another language.

I think it would be helpful to some people

**Comment by slrslr** [comment]
Yes it is there. Click avatar (it may be almost hidden in the bottom-left corner), Settings, Appearance. It may be handy if the language can be changed on the initial (1st app launch) screen: https://github.com/simplex-chat/simplex-chat/issues/6768
