### ISSUE TITLE
file, more than 8 mb (feature request).

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1771]
I need videos (most importantly) and other file types. Without solving the 8 mb problem, nothing will work

**Comment by epoberezkin** [comment]
we're aware of that, check out xftp RFC - it's in progress

**Comment by epoberezkin** [comment]
https://github.com/simplex-chat/simplexmq/blob/stable/rfcs/2022-12-26-simplex-file-transfer.md
