### ISSUE TITLE
Read once massages (feature request taken from the Olvid app)

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1772]
![IMG_20230117_214321.jpg](https://user-images.githubusercontent.com/113500363/212984331-807caae9-52eb-4319-ab03-e2b1f97fc822.jpg)

**Comment by x80486** [comment]
What's really the point of this one? If the message is set to disappear (read: to be removed from all devices) at some point, what's the visibility role?

**Comment by epoberezkin** [comment]
you lost me :) how is it different from disappearing with a really small time (like 30 seconds)?
