### ISSUE TITLE
Message retention policy (feature request taken from the Olvid app)

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1774]
![302285.jpg](https://user-images.githubusercontent.com/113500363/212792072-ab61517e-692b-46d2-ba00-7e3414ae4972.jpg)
`
![302287.jpg](https://user-images.githubusercontent.com/113500363/212792094-a7720db1-0a2f-4e67-aedb-f1f12f2ddb15.jpg)
![302286.jpg](https://user-images.githubusercontent.com/113500363/212792111-16041337-ac4c-416c-a942-4e3ed5215dda.jpg)

**Comment by epoberezkin** [comment]
Time-based retention is there, in Database settings. Count-based seems a bit of a gimmick tbh - not quite sure what problem does it solve. If storage space, it's a bit strange to worry about it too much these days...
