### ISSUE TITLE
automatically delete exif, metadata, etc. when uploading photos (feature req.)

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1776]
as these apps do:
https://gitlab.com/juanitobananas/scrambled-exif/tree/HEAD, https://github.com/Tommy-Geenexus/exif-eraser

**Comment by epoberezkin** [comment]
it kind of happens already as the image is compressed/resized, no metadata is retained. When we support sending unscaled images we will review.

**Comment by epoberezkin** [comment]
> @epoberezkin please could this be made optional.

Are you referring to the current image compression or to the future full-size image EXIF stripping?

For the current: there is no intentional stripping, but there may be a case for re-adding it after compression. You can still send a full res picture as file.

For the future: it will certainly be an on-by-default option.

**Comment by silverfisk** [comment]
> @epoberezkin please could this be made optional. I hate that Signal and various other apps strip exif information without asking. It makes it impossible to sort the images later when exported out of the app. It locks the media into the app, because outside of the app pictures are just a blob of data.
> 
> And it makes it very difficult to match time periods with photos from the same time period. For example, getting pictures from Signal, WhatsApp and Telegram for the same event, and then figuring out in what order they should be placed. It is a nightmare.
> 
> I understand the privacy concern of exif information. But honestly the main privacy concern is the face in the picture. And then if there are real privacy concerns, why are you taking pictures in the first place? Instead enjoy your clandestine moment.
> 
> Please can exif stripping and image conversions/size changes etc be made an option in settings.
> 
> Thank you!
> 
> Andreas

All images does not contain faces. I would like such an exif removal option to be enabled by default

**Comment by epoberezkin** [comment]
I agree that users should be in control of what data they send and how they manage it once it is received. You can see this view in other features. Right now there is no way to send the image without compressing, so it's just something to develop still.
