### ISSUE TITLE
types of messages, as in telegram: more (feature req.)

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1779]
monospace;
[hyperlink](https://github.com/simplex-chat/simplex-chat);
_oblique_;
underlined

**Comment by epoberezkin** [comment]
Markdown is already supported - check "how to use" in settings. Hyperlinks won't be supported for now, as it's a security issue to allow senders hiding URLs without any simple UI to show them - we'd have to add an alert to show an actual link (and people usually don't click alerts). At some point we might add trusted domains though to allow hyperlinks in them (or allow them without alerts), it's not a priority though, we will revisit it once we have public channels - as they are somewhat of an equivalent of a website hyperlinks make more sense there.
