### ISSUE TITLE
Automatically back up to the cloud (feature request)

### ISSUE THREAD

**Issue by TalOrenshtein** [simplex-chat/simplex-chat#1781]
I saw that SimpleX implemented encrypted backup solution. So, what's stopping us from storing it at the cloud so we can use it if the phone dies on us? I think it'd be useful. Maybe even the user can schedule it manually (once a day/week etc. at a time that they choose so the disabled chat won't bother the user)

**Comment by epoberezkin** [comment]
Nothing does, it's already happening via your system settings (on Android it is disabled by default in privacy settings, you can enable it).

**Comment by TalOrenshtein** [comment]
> Nothing does, it's already happening via your system settings (on Android it is disabled by default in privacy settings, you can enable it).

I'm a bit confused. When you export the database, it exported encrypted. I suggested a feature that will do it based on a schedule, and upload it to the cloud (I.e, via WebDAV). Can you explain what did you mean?
