### ISSUE TITLE
lokinet support

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1782]
> > >I am almost certain that it can if tor can then yeah theres no reason why it shouldn't be able to as well. This is the protocol used in session so I believe SimpleX should be able to benefit from it as well.
'
Take a look
https://lokinet.org/faq
>
>

> >yep, it indeed can be used in this way. Well, then somebody needs to make an Android app that provides Lokinet routing via SOCKS proxy and the job is done. Maybe, such an app already exists?
>
>

>I believe session does this already but you mean for you to copy the code? I wouldn't want to switch apps I would just like SimpleX to have that as a second option aside from the tor routing.
>
>

Waiting for the second option or the overlay of lokinet on tor

Modified: I found their app for android
https://github.com/oxen-io/lokinet-flutter-app

**Comment by epoberezkin** [comment]
If this app provides SOCKS proxy it can be used, we definitely won't be integrating lokinet support directly in the app.

**Comment by epoberezkin** [comment]
If there is an equivalent of .onion addresses on lokinet, we might consider adding support for these addresses in the client and adding these addresses to our pre-set servers, but I am not a big fan of this idea – lokinet is neither sufficiently decentralised nor independent to be considered a good overlay network on par with Tor and i2p. So I am not sure why would anyone want to use it - what problems does it solve that Tor or i2p don't solve better?

**Comment by epoberezkin** [comment]
Let's clarify - the issue can be about multiple things:

- allowing people to self-host servers with lokinet addresses – nothing need to be done about it, it should just work, as long as the clients are connecting via LokiNet.
- supporting SimpleX client connection via LokiNet, without any external software - it is technically possible, but we will not be able to do it internally. Some other developer can fork this implementation and make a version that connects via LokiNet.
- supporting SOCKS5 proxy for LokiNet - nothing needs to be done for that to work, as long as there is an external third party app that provides SOCKS5 proxy, in the same way as Orbot for Tor and Invizible for i2p, it will just work. I am not aware of such app, but it is quite possible to implement, as there is desktop SOCKS5 proxy - someone just needs to wrap it into a mobile UI. We will not be able to do it too, as it is a general software that can be used for any network access, and we are 100% focussed on SimpleX software.
- recognising .loki addresses of the servers in the clients. We will consider adding it if/when there is:
  - Android app providing Lokinet as a SOCKS proxy.
  - server-side client that we can run on the server that would make this server available on .loki address

**Comment by cannatoshi** [comment]
Hey! 👋

Really appreciate the detailed breakdown @epoberezkin!

The last point is particularly interesting:

>>>  "server-side client that we can run on the server that would make this server available on .loki address"

I'm currently exploring server-side tooling for SMP operators and multi-network support (Tor + Lokinet) would be a great addition for operators who want network diversity.

Quick question for the community: Is anyone currently running SMP servers accessible via both .onion AND .loki addresses? Would love to hear about dual-stack setups and experiences with Lokinet reliability compared to Tor! 🧅🟣
