### ISSUE TITLE
(bug) Calls and video calls don't work for me

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1791]
I just get the initialization message. Nothing else happens.

My friend doesn't get my calls at all

But at the same time, everything works for my friend (for other people). 

When he calls me I get a notification , but when I press answer I get the initialization barrier again

And when he calls other people he works fine, so I have a problem, not him. 

everything except calls and video calls works for me

–––––––
I have an endless initialization, help 

>miui 12.0.5. Android 12, latest version
>
>

**Comment by andreasmjg** [comment]
Other call related issues:

https://github.com/simplex-chat/simplex-chat/issues/1230

https://github.com/simplex-chat/simplex-chat/issues/1045


I have not managed to make a call with Simplex. I have tried to iPhone and Android users. Doesn't work and I have no idea why (have tried on/off VPN, WiFi/mobile)

**Comment by epoberezkin** [comment]
Could you please follow troubleshooting guide here and let me know what is / isn't working:

https://github.com/simplex-chat/simplex-chat/blob/stable/docs/WEBRTC.md#troubleshoot

Use the servers addresses from code here:

https://github.com/simplex-chat/simplex-chat/blob/stable/packages/simplex-chat-webrtc/src/call.ts#L219

Thank you!

**Comment by mika-nl** [comment]
Do you use nat behind nat ? (Like one provider modem and then a own router ? )
Because when I do the turn test I see my public IP address.

**Comment by epoberezkin** [comment]
@Wjxfi could you please follow this guide and share what did/didn't work: https://github.com/simplex-chat/simplex-chat/issues/1791#issuecomment-1399284333 ?

Fallback from UDP to TCP was indeed added this year and it fixed calls for many people, but there may be other issues of course.

Assuming you are on Android?

4.6 fixes bluetooth and sound issues for Android, and has a complete new implementation for iOS making them quite usable there, but from your description it won't solve your issues. Please help debug/understand - it's not clear what the issue is.

**Comment by SmallCoder13** [comment]
Having a similar issue. I can audio call, but the call ends when my device enters sleep mode. Also, my half brother can’t video call

**Comment by andreasmjg** [comment]
As of latest update 4.6-beta.1 calls now work between my Android and iPhone 🙌

**Comment by shumvgolove** [comment]
@Wjxfi Please open separate issue with detailed description, thanks.

**Comment by shumvgolove** [comment]
You didn't provide the requested information by Evgeny – [WebRTC Troubleshoot](https://github.com/simplex-chat/simplex-chat/blob/stable/docs/WEBRTC.md#troubleshoot) – to debug this issue further. Please test this again with `v.5.0.0` release and open the new issue with detailed steps to reproduce and logs from WebRTC Troubleshoot guide.
