### ISSUE TITLE
Translations deleted on Weblate

### ISSUE THREAD

**Issue by sith-on-mars** [simplex-chat/simplex-chat#1795]
I started doing the Chinese translation in last month. I also saw someone else was doing the Norwegian translation on Weblate. However, both languages are gone now and basically our progress are lost. Is there any reason why they were removed?

**Comment by ltGuillaume** [comment]
Either way, Weblate is the worst platform I've ever worked with. It's far too difficult to properly track changes, especially when other screw up translations, its structure is extremely confusing, its documentation is the worst I've ever seen and hosted.weblate is so slow that it takes up to 25 seconds to load a page over here.

**Comment by epoberezkin** [comment]
@ltGuillaume  which platforms you consider to be better? We're probably going to stay with weblate for now but might consider migrating at some point.

@sith-on-mars yes, we did have some teething pains with weblate, the workflow seems to be stable now, not the best possible, but manageable. I am limiting to one new language in progress at a time, as it's easier to add small number of strings and the initial translations require the most effort, both from the translators and from us.

Happy to kick off Chinese now that Italian is completed if you have time in the next couple of weeks to do it? Chinese is going to be more challenging than European languages I think, but interesting.

**Comment by epoberezkin** [comment]
And sorry for losing the translations, I didn't figure out that it will happen on some UI action, and their support wasn't helping in recovering it...

**Comment by ltGuillaume** [comment]
I like http://www.crowdin.com best, then https://poeditor.com, then https://www.oneskyapp.com

If you still want to use Weblate, consider using https://translate.codeberg.org instead of https://hosted.weblate.org

**Comment by sith-on-mars** [comment]
No worries at all @epoberezkin! I'm happy to do Chinese translation next.

I've been involved in another Weblate translation project before, and everybody can just chip in, add new languages, and do translation whenever they want to. Of course, sometimes people need to put new translations because the new strings are added, but the project doesn't restrict the numbers of translation you can have at the same time. I'm curious why this is not the case here? Limiting to one translation at a time means more time to finish translating all languages.

**Comment by epoberezkin** [comment]
@ltGuillaume thank you! Will review this - definitely came across crowdin.

**Comment by epoberezkin** [comment]
@sith-on-mars I've added Chinese (Simplified) - I believe it's the right one :) Look forward to working on it with you. Please connect to me via the chat (my address is on my GitHub profile), I'll add you to the group of translators.

> I've been involved in another Weblate translation project before, and everybody can just chip in, add new languages, and do translation whenever they want to. ... I'm curious why this is not the case here? Limiting to one translation at a time means more time to finish translating all languages.

Yes, I've seen it too. In general, we are trying to do fewer things of higher quality, so the things we do have work well for the end users. That applies to interface translations too – I think it's better to have fewer high quality translations, than a lot of incomplete translations.

Each language, particularly when it's added initially, requires a lot of upfront investment of both your time (I estimate 2 full working days or a bit more), but also of the team time - we have to see how it works in the app and to validate that translations are generally correct, and to support you with any questions.

Ongoing maintenance is much easier for everybody. So it feels like if we try to do several languages in parallel it will take all our time, and we won't be able to make a meaningful progress adding new features... As the team gets bigger we should probably be able to add new languages faster - hopefully we will be able to grow the team this year.

Thank you!

**Comment by sith-on-mars** [comment]
Fantastic, much appreciated for the detailed explanation. I'm glad I can do something to support the project!

Is there any group for discussing translation related question, or we just use the user group for this?

**Comment by epoberezkin** [comment]
yes, please connect to me - will add you to the group. Thank you!
