### ISSUE TITLE
Android app does not prompt to save changed SMP server settings when returning to main screen

### ISSUE THREAD

**Issue by Perelandra0x309** [simplex-chat/simplex-chat#1802]
I have a self hosted SMP server and recently added a password to it. I went to edit the server settings in the Android app under "Your SMP servers", and successfully added the ":password" section to the address, and got a successful result from "Test server". However I simply hit the back button a few times to get back to my contacts list. I later tried to add a new contact and was getting errors connecting. I discovered my password had not been saved in my server settings.

After playing around with the sever settings for a bit I discovered I need to hit the "Save servers" button on the "Your SMP servers" screen for the changed settings to stick. It's pretty obvious now, but I missed seeing that before. It would be nice if when you try to go back from the "Your SMP servers" screen and there are unsaved changed there is a warning about that.

**Comment by epoberezkin** [comment]
Makes sense, we did add this warning on changing chat preferences as it was also easy to miss.

**Comment by epoberezkin** [comment]
released
