### ISSUE TITLE
Minor Fix: Quickly Tapping the (i)-Icon on Incognito menu entry opens the info page several times.

### ISSUE THREAD

**Issue by natzki** [simplex-chat/simplex-chat#1804]
Just a minor issue that is just something "cosmetic", yet it happened to me once accidentally, and since tried it out multiple times again.

It seems that if the infopage isn't fully swiped to the left (from right), you can tap the icon again and a second page will also open over the first one. Pressing back is required two times then just as seems accurate.

Maybe pressing the icon can be made to be disabled until the info screen is closed or there is a timeout of a second or so each time you tap.

###### ~~Unrelated:  My first real Issue on GitHub posted :D ~~

**Comment by natzki** [comment]
Minor cosmetic issue it's still present haha

**Comment by natzki** [comment]
By the way other menu fields are also affected by this

**Comment by kuflierl** [comment]
Could not reproduce on iOS 15 v4.6 (135)

**Comment by shumvgolove** [comment]
Please reopen if issue persist with latest release.
