### ISSUE TITLE
Mute notification randomly stopps working on iOS

### ISSUE THREAD

**Issue by sith-on-mars** [simplex-chat/simplex-chat#1817]
I'm using SimpleX on iOS. My notification setting is instantly.

From what I understand, at least on iOS, muting notification means that when new messages arrive, I won't receive any notification on my device, nor will I see any badge count on the app icon. Once I open the app, I can see badge count. 

Sometimes I still received notifications after muting notification in a chat group. It happened randomly.

**Comment by walteb** [comment]
I am getting these unwanted notifications as well. Sometimes even multiple notifications in quick succession, which may be for the same event. I also seem to get notifications when a user joins a group chat -- I'm not sure if this is expected behavior or not. 

I am using v4.4.4 (118) on iOS 16.3.

**Comment by epoberezkin** [comment]
A non-intuitive thing is that after disabling notification on a group, particularly a large one, you need to give app some time to update notification server. It's not super-efficient right now, can take couple minutes with a large group, as there is a separate subscription for each member.

If you disable notifications and close the app straight away, the notifications will continue arriving, as for push notifications the app MUST show something, it can't just hide them on the basis you disabled them, you need to instruct the server to stop sending them, separately for each group member.

**Comment by epoberezkin** [comment]
That will be improved and will happen faster in future versions.

**Comment by walteb** [comment]
Ah that makes sense. Yes this was happening to me in the big SimpleX-Group. After muting the group and leaving the app running for a few minutes, the number of unwanted notifications was significantly reduced. However I still occasionally get them when a new user connects to the group.

Thanks!

**Comment by epoberezkin** [comment]
We now can fix it more comprehensively, incoming :)

**Comment by kuflierl** [comment]
Looking forward to the fix

**Comment by epoberezkin** [comment]
It's been released, please open another one if some symptoms still happen.
