### ISSUE TITLE
Create a mirror in Codeberg

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1835]
my issue is at this link:
https://github.com/Darkempire78/OpenCalc/issues/131

Also, in addition to the link above to my issue, I give you a link to the information on the site
https://docs.codeberg.org/getting-started/what-is-codeberg/#what-is-codeberg

**Comment by x80486** [comment]
`Codeberg` is by far something to be considered...at least for the moment. The Git forge has been unstable for some time now, and `Gitea` in general is not ready for the real world yet.

I would go with `GitLab` — it's open source as well with a slightly different model.

Moreover, what's the point of moving to another place?

**Comment by shumvgolove** [comment]
Not for now, but thanks for consideration!

**Comment by ghost** [comment]
Considering the latest news: https://arstechnica.com/gadgets/2025/08/github-will-be-folded-into-microsoft-proper-as-ceo-steps-down/, the AI code stealing bullshit and bad politics of the owning company of this site, this would probably be an excellent time to reconsider either creating a mirror or moving there completely.
