### ISSUE TITLE
Almost impossible to receive images

### ISSUE THREAD

**Issue by x80486** [simplex-chat/simplex-chat#1843]
Looks like for `SimpleX`, in order to receive images, the sender must be online, otherwise a blur version of the picture(s) will be displayed.

What happens currently is that no one in my contacts use the notification service because it drains the battery, so they configured as `Run when the application is open`.

In that sense, it's practically impossible to receive an image because we have to be online at the same time. I actually don't think this would be solved even with proper push notifications, but it would get better many times.

Is there a way to overcome this issue? For instance, people in `Cuba` usually connect one or twice a day for a couple a minutes, and then no more until the other day because it's deadly expensive. So you can imagine with this "connection mode" it's practically impossible to receive anything currently.

**Comment by shumvgolove** [comment]
This should be fixed with latest version.
