### ISSUE TITLE
Can’t add any server

### ISSUE THREAD

**Issue by Silent-wqh** [simplex-chat/simplex-chat#1875]
I can't add any server in simplex in Appstore or simplex in testflight.
It always shows red exclamation mark.
Even if I delete the original three servers and add them again, simplex still displays a red exclamation mark.
![59525BB4-D644-41FA-B7C4-0E13C80735CE](https://user-images.githubusercontent.com/24985177/216417206-0d5c1015-397d-4810-87b5-e67454e5dd7f.png)
![5DD7DBCF-E889-4372-85B4-870DB30D349A](https://user-images.githubusercontent.com/24985177/216417241-68ad2b82-33c4-421a-b7c4-b5eb495b6ba2.png)

**Comment by epoberezkin** [comment]
you shouldn't be adding preset servers manually, if that's what you are doing? When you click "add" there is an option to add preset servers. If it's with your server, possibly it has an incorrect address?

**Comment by epoberezkin** [comment]
Is there maybe a line break or space after `smp://` or somewhere else in the server address?

**Comment by epoberezkin** [comment]
also, there is at least one letter difference in onion part of the address, although it shouldn't be making it invalid, but it won't work when connecting via Tor - the line `gypaavemqurytl6hozr47wfc7uuecaciadvwpw` I have as `qypaavemqurytl6hozr47wfc7uuecacjqdvwpw` (note the first letter - it's a different address)

**Comment by Silent-wqh** [comment]
！[FE9B595D-4C38-47E9-9CA3-CBCDACF30BDB]（https://user-images.githubusercontent.com/24985177/216553878-1ee0397d-7d86-4995-84b5-a90193a10975.jpeg）
this is my custom server. The line break is not used, and the screen shows an automatic line break. Not using tor.

**Comment by Silent-wqh** [comment]
![313C6D2E-934B-49F3-97EA-D6B11C8DA48F](https://user-images.githubusercontent.com/24985177/216554930-5afb71d1-b92c-4a9b-a2ee-149fd30d5c1e.jpeg)

This is my custom server config. The line break is not used, and the screen shows an automatic line break. Not using tor.

**Comment by Silent-wqh** [comment]
smp://d_7l8zp1CgnF0YttjRS—reRTKl02a07vfQqybtVGaY=:furbish-modified-finch-neatly@41.127.200.56:5244

This is the partially modified configuration of my original server.

**Comment by epoberezkin** [comment]
what is this character after `S`? It doesn't look like `-`, it's some other character that makes it non-valid base64url encoding.

**Comment by epoberezkin** [comment]
you shouldn't be posting server password btw :) please change it - otherwise other people will be able to receive the messages via it :)

**Comment by epoberezkin** [comment]
ah - it's modified... ok then.

**Comment by Silent-wqh** [comment]
fingerprint: d_7l8zp1CgnF0YttjRS—reRTKl02a07vfQqybtVGaY=
password: furbish-modified-finch-neatly
ip address and port: 41.127.200.56:5244

Are there any other parameters needed for this?
I configured the link based on this document.
https://github.com/simplex-chat/simplex-chat/blob/stable/docs/SERVER.md#smp-server-address

**Comment by epoberezkin** [comment]
no, this is all correct, but your fingerprint has a character `—` in it - possibly, it was two hyphens in a row that some editor, maybe iOS, replaced with long dash which is invalid in base64 .

**Comment by Silent-wqh** [comment]
> no, this is all correct, but your fingerprint has a character in it - possibly, it was two hyphens in a row that some editor, maybe iOS, replaced with long dash which is invalid in base64 .`—`

It's solved. The key point is that ios replaces the two "-" with one "—".
Thank you for your help and for your contribution to keeping your privacy safe.
![38548BEFED2C868B968C33067784B6A3](https://user-images.githubusercontent.com/24985177/216583530-cd2047be-4f16-4cf4-b410-caa42cc10385.png)

**Comment by epoberezkin** [comment]
right, so the real issue is that we need to disable autocorrect on this field. Thank you!

**Comment by epoberezkin** [comment]
hm, it actually has autocorrectionDisabled(true) - this is strange... So maybe it got replaced in transit, not during the insertion :)

**Comment by epoberezkin** [comment]
alright, going to close it then.
