### ISSUE TITLE
Czech translation 🇨🇿

### ISSUE THREAD

**Issue by zen0bit** [simplex-chat/simplex-chat#1879]
Added czech translation 🇨🇿 

Přidán český překlad 🇨🇿

Let's finish it...

Pojďme to dodělat...

What I am missing in

Co chybí, je špatně v českém překladu?

# CZECH translation?

Android app - First correction on weblate

[![android app](https://hosted.weblate.org/widgets/simplex-chat/cs/android/svg-badge.svg)](https://hosted.weblate.org/engage/simplex-chat/cs/)
iOS app - First translation DONE - not tested

První překlad hotov

Netestováno!
Někdo kdo může vyzkoušet?

[![ios app](https://hosted.weblate.org/widgets/simplex-chat/cs/ios/svg-badge.svg)](https://hosted.weblate.org/engage/simplex-chat/cs/)

website - First correction DONE

web - první korekce HOTOVA

[![website](https://hosted.weblate.org/widgets/simplex-chat/cs/website/svg-badge.svg)](https://hosted.weblate.org/engage/simplex-chat/cs/)

Write me here on github

Napište mi zde na githubu

nebo v české skupině na simpleX chat...

 or...

- [\#SimpleX-CZ](https://simplex.chat/contact#/?v=1-2&smp=smp%3A%2F%2FSkIkI6EPd2D63F4xFKfHk7I1UGZVNn6k1QWZ5rcyr6w%3D%40smp9.simplex.im%2Fa9cQnGxqjcl0yuFfeatRXZNTVNBzFSlm%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEA6rmC2VihWCpd2XgDLFpi54szBASR3HcRDvWkRJLMADw%253D%26srv%3Djssqzccmrcws6bhmn77vgmhfjmhwlyr3u7puw4erkyoosywgl67slqqd.onion&data=%7B%22type%22%3A%22group%22%2C%22groupLinkId%22%3A%22KEKaQO6o0TqSHacX0XTvcw%3D%3D%22%7D) (Czech speaking).

**Comment by zen0bit** [comment]
I see merged in master branch...
Question is: How to test translation in android app prior to release?

**Comment by zen0bit** [comment]
Android app correction:
https://github.com/simplex-chat/simplex-chat/pull/1926

**Comment by zen0bit** [comment]
Also translated version isn't still included in prerelease versions...

**Comment by zen0bit** [comment]
website correction:

https://github.com/simplex-chat/simplex-chat/pull/1952

**Comment by epoberezkin** [comment]
@zen0bit Thank you!!!

We're releasing 4.5.3 that will include Czech today, it'll be on beta channels first, but I can add you to Google and/or iOS internal testers.

Are there any corrections in GitHub that are still needed? Weblate workflow is convoluted enough, so it's easier if it all comes via weblate. But if needed we can review/merge any changes from GitHub too - please rebase them on master then.

Also please review the corrections by @MSarmadQadeer (he was reviewing all translations) here: https://github.com/simplex-chat/simplex-chat/pull/1956

Please let us know if they are ok or you disagree, then please propose any corrections.

Thank you very much - it's a huge effort to add a new language :)

**Comment by zen0bit** [comment]
Looks good to me for now

But I must see it in app.

...

@epoberezkin Please add me to Google internal testers.

...

Added translated docs on github...

https://github.com/simplex-chat/simplex-chat/pull/1963

**Comment by zen0bit** [comment]
So from now on translation will go through weblate...
But docs (README etc. on GitHub) are not on weblate...

**Comment by zen0bit** [comment]
1. android app translation correction on weblate

### Ready for merge...

@epoberezkin

**Comment by epoberezkin** [comment]
This massive effort is now complete!

**Comment by epoberezkin** [comment]
Thank you!!!

**Comment by zen0bit** [comment]
You are welcome :heart

Filled new string in iOS on weblate..
