### ISSUE TITLE
[Bug?] Database issue

### ISSUE THREAD

**Issue by WX4300** [simplex-chat/simplex-chat#1883]
(In the past I paused the chat and I exported my database, I tested the servers and they were working)
1. I'm receiving all of new messages
2. At some point I don't receive new messages anymore (a person I talk to confirmed that they sent messages)
3. I pause and resume the option "Chat is running"
4. I get the messages mentioned above
5. I'm receiving new messages normally

**Comment by shumvgolove** [comment]
Please reopen if issue persist with latest release.
