### ISSUE TITLE
App crashing systemUI after answering call

### ISSUE THREAD

**Issue by mollyuser** [simplex-chat/simplex-chat#1934]
Hi, the app is crashing the sysyemUI after i answer a call on GrapbeneOS. Calls on lock screen has to be set on ACCEPT to answer a call without unlocking the device. When i do this and i answer a call the systemUI crashes and i have to reboot the phone. If i set the calls on lock screen to disable. I can answer a call after i unlock the screen and then it works fine. Can someone please solve this because the app is unusable with GraoheneOS like this.

**Comment by silent-ninja-1** [comment]
Hi there @mollyuser! 

Another GrapheneOS user here. I also have set the **Calls on lock screen** setting to **Accept**, and I am able to answer incoming calls from the lock screen without issue.  Can you update SimpleX to v4.6.0 and try again?

**Comment by shumvgolove** [comment]
Please open a new issue if this behavior persists.
