### ISSUE TITLE
iOS photo library access

### ISSUE THREAD

**Issue by valynor** [simplex-chat/simplex-chat#1939]
Hey, 

just installed 4.5.2 on two iOS 16.3.1 devices and noticed that SimpleX (or rather iOS) didn't ask for photo library permissions when adding a picture via the "paperclip" icon. Whatever ways the app uses to not ask for this permission but access the photo roll anyway, it should probably not do that. 

It did ask for camera permissions when I tried that, though.

**Comment by epoberezkin** [comment]
Well spotted, surprised more people don't ask about it, as most apps don't do it the right way, like we do :)

SimpleX iOS app uses a relatively new (~ 3 years old soon) private photo picker that runs a system photo selection dialog in an isolated container that the app has no access to, so the app can only access the photos that you chose - iOS takes care of that, it wouldn't allow accessing all photos without permission.

So while you can see all photos, the app cannot - hope it makes sense. You can watch this video about it: https://developer.apple.com/videos/play/wwdc2020/10652/

if you look in the system photo access settings it would show SimpleX Chat as having access to chosen photos only, or something like this.
