### ISSUE TITLE
[l10n] Please add Lithuanian language to Weblate

### ISSUE THREAD

**Issue by welaq** [simplex-chat/simplex-chat#1947]
Please add Lithuanian language to Weblate  as it is now absent

**Comment by zen0bit** [comment]
You can ask for adding language straight through weblate...

**Comment by welaq** [comment]
I did. I asked a few weeks ago. But it is still not added.

**Comment by welaq** [comment]
@epoberezkin FYI

**Comment by epoberezkin** [comment]
Sorry, and thanks for chasing!
