### ISSUE TITLE
Donations via Bitcoin Lightning network

### ISSUE THREAD

**Issue by systemling32** [simplex-chat/simplex-chat#1964]
Hey there,

I love the project and would like to support the cause and appreciate the option to donate with Bitcoin. However on-chain transactions are not the most efficient way to do donations especially for smaller amounts. 
The Bitcoin lightning network has come a long way and is equipped to handle such transactions much faster, cheaper and with anonymity for the sender. In every way it is better for the donators and also for you since you will save on fees once you want to send the donated funds somewhere.

I would be happy to see an option to pay via lightning and you could use either a self-hosted lightning node with BTCPayServer or a custodial solution with LNbits, Alby or Wallet of Satoshi for example.
Then you could add a static Lightning address or LNURLp to your donation options and users could tip effortlessly with all the advantages of the lightning network.
It would enable me to schedule automatic monthly contributions of let's say 5$ without my interaction which would not be economically feasible with an on-chain transaction.

Please consider adding lightning payments, I am sure to setup a recurring donation when you do!

Keep up the great work, I really admire your work!

**Comment by epoberezkin** [comment]
Thank you!

Try this: https://getalby.com/p/simplex
