### ISSUE TITLE
Add SMS support?

### ISSUE THREAD

**Issue by Sn0whax** [simplex-chat/simplex-chat#1976]
Good opportunity to lure all of the angry signal users over.
It could be a separate toggle where the users are prompted to link their number to the app to enable sms, but also indicating Simplex would remaing e2e without ties to the phone number.

**Comment by Darin755** [comment]
I know that SMS is pretty disliked but I think that there should be SMS integration in the form of sharing.

What this could look like is a button that shares a link with a SMS contact. 

I would also be nice to verify that someone is who they say they are with SMS but that may require much more effort to implement privately
