### ISSUE TITLE
Failed to set storage encryption

### ISSUE THREAD

**Issue by Lord-KA** [simplex-chat/simplex-chat#1985]
When I try to set encryption password to export db, `failed to set storage encryption: chatCmdError database errorEncrypted` error occurs.
![IMG_20230308_231525](https://user-images.githubusercontent.com/43700614/223840648-ec0635f2-c9aa-4034-8955-dbf97271ca62.jpg)
 

Android 13 (LOS 20)
SimpleX 4.5.2 (100)

**Comment by Lord-KA** [comment]
OK, now I've tried to toggle "Save passphrase in Keystore", it didn't make any difference to the error but when I tried to enable chats again, it logged me out of the app:
![IMG_20230308_232428](https://user-images.githubusercontent.com/43700614/223841552-834b31e9-a4fd-400a-b0b3-3bf225d6821d.jpg)

**Comment by Lord-KA** [comment]
As we discussed in #1930 the db is encrypted by random passphrase and if you disable "Save passphrase in Keystore" you delete the only copy of it. It seems as if I've lost all my chats and contacts *again*...

**Comment by epoberezkin** [comment]
hm, the app doesn't allow disabling "Save passphrase in Keystore" when it is random - how did you do it?

**Comment by epoberezkin** [comment]
looking at the first screenshot, as the app asks for the "current passphrase" it means that it is not random - I don't have it when I first install the app (as expected)...

But also the button to update passphrase should not be enabled until you enter "current passphrase", but it is enabled in your case...

It's possible that it got into some unexpected state, maybe after restoring from backup or some other series of actions? Not quite sure how it could have happened - could you try to reproduce all the steps?

**Comment by avently** [comment]
What happens if you enter correct passphrase after app starts up?

**Comment by epoberezkin** [comment]
The minor issue seems to be that the button Update password is enabled even if you don't enter a current (not random) password you set previously.  And that results in the error as it passes the empty passphrase as the current one, so that SQLCipher thinks as if it is not encrypted. So if you enter the correct passphrase it should both allow opening the app and changing it.

**Comment by Lord-KA** [comment]
Oh, you were right, I've forgotten that I set a password and the app didn't tell me that directly. So the issue is mainly in the `Update` button that doesn't check empty "current password". And there is one more thing, when I enter from 0 to 3 characters into "current password" the `update` button is active, while with exactly 4 chars it is gray. This doesn't seem intended.

**Comment by epoberezkin** [comment]
... because validating can be fast and re-encrypting with the same password is slow – it effectively exports the whole database to the new files.

**Comment by epoberezkin** [comment]
> I've forgotten that I set a password and the app didn't tell me that directly.

yep, it is kind of implied, as the footer is changed, but I understand that when somebody's stressed about having lost passphrase they are not particularly attentive to the small print nuances... We might modify the message to say it explicitly that it is a user-provided passphrase now.

**Comment by Lord-KA** [comment]
Ok, now it returns almost the same `failed to set storage encryption: chatCmdError userld: 1 database errorEncrypted`, but in a prettier message window :)

**Comment by Lord-KA** [comment]
And before that there is an information window `Database will be encrypted. Please store the passphrase securely...`, that doesn't really fit the scenario, as the db is encrypted anyway. But it doesn't seem too important.

**Comment by shumvgolove** [comment]
@Lord-KA  Could you reinstall the application (and export your database beforehand), make a clear profile and then try to set password?

**Comment by Lord-KA** [comment]
Well, it is a bit weird. On a newly installed app I get a `Change database passphrase?` screen, while on a db where I already have a password installed it is `Encrypt database?`. It seems like the messages should be swapped.

**Comment by Lord-KA** [comment]
And when I am asked to install the password for the first time there is no field for old password, so there is no confusion with the newly installed app.

**Comment by shumvgolove** [comment]
Yeah, that's what I thought. So the issue is resolved (besides confusing messages)?

**Comment by Lord-KA** [comment]
Yes, thank you!
