### ISSUE TITLE
Servers not connected 

### ISSUE THREAD

**Issue by TheRedBaron745** [simplex-chat/simplex-chat#1986]
For the past few months that I have been using SimpleX chat for I have not had any issues until today. I have encountered an unfixable issue regarding the servers used for chat. After it connects there is an error with the error code "agent broker timeout." And when I attempt to test the servers it gives me the following error code "Test failed at step Connect. Possibly, certificate fingerprint in server address is incorrect. I have no idea how to fix it and any help would be appreciated.

**Comment by epoberezkin** [comment]
There was some worse connectivity today. You can try increase timeouts in advanced network settings - it may help when network latency is too high.
