### ISSUE TITLE
A new network design

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1991]
I was a social network user called Nostr for a few weeks, and I learned some things I think they are useful.

The server-client idea has come to an end: if what we are looking for is resistance to censorship, unfortunately, one server is not enough.

Not only that, but in a dictatorial country one can suffer the forced seizure of the domestic server. Now I’m not saying that the police will be able to break encryption that protect your data.

I’m saying we need another design where each server is the relay of each of us. On Nostr happens just this: I was connected to four relays simultaneously that propagated my events without asking questions. Their only purpose was the events' propagation. No restrictions.

If so, this is the way.
Encryption will protect data privacy.

**Comment by Darin755** [comment]
I don't think this is the goal of Simplex chat. 

If your looking for a decentralized alternative you could try Session or Briar

**Comment by PalmTamino** [comment]
> I don't think this is the goal of Simplex chat.
> 
> If your looking for a decentralized alternative you could try Session or Briar

So what do you think is the goal for simplex? I think it’s also for those who live in an authoritarian regime to communicate. Luckily simplex is not on the radar, but it will surely get blocked if it gets bigger, so a mitigation for this would be amazing.

For those living in liberal democracies, they don’t have to use something like simplex that nobody of their friends uses anyway, they can just use Signal. But in other countries, simplex, session, briar or status is their only option, and even getting the hands on simplex is super hard for them.

**Comment by Darin755** [comment]
The only way Simplex can resist censorship is when it runs though tor. Tor is still the best way of avoiding censorship as long as you have a internet connection. Briar is the best option if you don't have reliable internet.

Simplex is good for me personally because it keeps random people from calling me.

**Comment by x80486** [comment]
That' not **the only way** — it may be currently, which I deduct you might be referring to, but I think something like `Nostr` (open protocol) is close to ideal.

At some point there is going to be a "dedicated" application in this realm using `Nostr`...and that's a game changer, so why not embracing that if possible?

**Comment by epoberezkin** [comment]
my problem with Nostr is the lack of privacy, and I think that resisting censorship does require not just technical resilience of the content, but also privacy.  We will be addressing it.
