### ISSUE TITLE
Share multiple images

### ISSUE THREAD

**Issue by freemyminde** [simplex-chat/simplex-chat#1994]
Hello

I am new to Simplex Chat.
Everything in the app works more or less smooth. But I have seen, that there is no option to send several selected files (like pdf). And for sharing multiple pictures from the gallery, takes a lot of time on my phone. And with the time I do not mean the time to send. Once I selected my pictures and click share>Simplex>"myContact" it takes some time (38 seconds for 10 images) until I get the screen, where the pictures are shown in the chat to send them.

I hope you can reproduce this on other phones as well. I use a OnePlus5.

Best regards

**Comment by shumvgolove** [comment]
Please open new issue if issue persist with latest release.
