### ISSUE TITLE
Is SimpleX compatible with Manjaro (KDE) OS?

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#2039]
I wish to buy Pinephone and Pinebook Pro. I ask if SimpleX is compatible with both devices.

**Comment by epoberezkin** [comment]
Android mobile app certainly won't work on Linux without a lot of glue - there are some desktop solutions for linux, but I don't know if it would work on Pinephone. We certainly won't be supporting it in the near future, but it might be possible to run it somehow.

**Comment by robster7674** [comment]
@serrq I've tried on PinePhone: looks like the first obstacle is to get cabal and ghc compiled on aarch64. I was using Manjaro. Did you already get your Pine devices?
