### ISSUE TITLE
Can't switch between profiles when sharing to SimpleX

### ISSUE THREAD

**Issue by realpixelcode** [simplex-chat/simplex-chat#2057]
When sharing content via SimpleX using Android's Share menu, it seems impossible to switch to a different sending profile before selecting a recipient.

**Comment by mika-nl** [comment]
Yes , wish this was possible.
Now you are in a web browser and try to share a link you have to be sure the right profile from simplex is active

**Comment by avently** [comment]
#2084 should make possible to change a profile
