### ISSUE TITLE
in Transport.hs: T.getPeerFinished not found

### ISSUE THREAD

**Issue by testexplode** [simplex-chat/simplex-chat#206]
I made a cabal build, and got the same as in the hackage CI:

``[tags/v1.0.0] % cabal build
Build profile: -w ghc-8.10.6 -O1
In order, the following will be built (use -v for more details):
 - simplexmq-1.0.0 (lib) (first run)
 - simplex-chat-1.0.0 (lib) (first run)
 - simplex-chat-1.0.0 (exe:simplex-chat) (first run)
Preprocessing library for simplexmq-1.0.0..
Building library for simplexmq-1.0.0..
[11 of 28] Compiling Simplex.Messaging.Transport ( src/Simplex/Messaging/Transport.hs, /home/me/programming/haskell/simplex-chat/dist-newstyle/build/x86_64-linux/ghc-8.10.6/simplexmq-1.0.0/build/Simplex/Messaging/Transport.o, /home/me/programming/haskell/simplex-chat/dist-newstyle/build/x86_64-linux/ghc-8.10.6/simplexmq-1.0.0/build/Simplex/Messaging/Transport.dyn_o )

src/Simplex/Messaging/Transport.hs:284:27: error:
    Not in scope: ‘T.getPeerFinished’
    Module ‘Network.TLS’ does not export ‘getPeerFinished’.
    |
284 |     cxtFinished TServer = T.getPeerFinished
    |                           ^^^^^^^^^^^^^^^^^

src/Simplex/Messaging/Transport.hs:285:27: error:
    Not in scope: ‘T.getFinished’
    Module ‘Network.TLS’ does not export ‘getFinished’.
    |
285 |     cxtFinished TClient = T.getFinished
    |                           ^^^^^^^^^^^^^
cabal: Failed to build simplexmq-1.0.0 (which is required by exe:simplex-chat
from simplex-chat-1.0.0).

1  ~/programming/haskell/simplex-chat (git)-[tags/v1.0.0] % ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.6
me@here ~/programming/haskell/simplex-chat (git)-[tags/v1.0.0] % cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library ```

**Comment by epoberezkin** [comment]
We use a forked version of TLS library because the one in hackage didn’t expose peer finished messages, and the change I didn’t merge upstream the change I made yet.

I’ve literally pushed cabal.project an hour ago to allow building the project in cabal - could you please pull the latest commit from master and try building it again?

**Comment by epoberezkin** [comment]
Thank you - please keep us posted on what uses you find for it :)

Are you building on Android?

**Comment by epoberezkin** [comment]
Please use stable branch though :)
