### ISSUE TITLE
Establishing calls take too much time

### ISSUE THREAD

**Issue by x80486** [simplex-chat/simplex-chat#2092]
This is something I've seen since I started using `SimpleX`. With the recent (version `4.6.x`) update, this feature improved in stability, but still, I think we can all agree that it takes too much time to actually establish the call from the moment the called party answers.

I think replicating what a usual phone would do is what most people understand and are familiar with. I have plenty of people that tells me about this problem quite often. It also gets more complicated because during calls the screen can be turned off (as it usually happens in `Android`) when the phone is unused, so inhibiting that could be a plus as well.

Not sure if that can be improved, but if not it would be good to know the reason(s).

**Comment by x80486** [comment]
Actually, I think one of the issues might be that `SimpleX` does not actually establish the call until the called party answers. For instance, when I'm using the Bluetooth connection, I can't hear anything until that happens, so that's one clue to let me arrive to that conclusion — but I may be wrong.

**Comment by epoberezkin** [comment]
That is correct, nothing happens until another party answers - only a message is sent, but the call session is not created yet. It may indeed result in a bit longer call handshake, but it also allows to answer after a longer time.

**Comment by x80486** [comment]
Can you link the commit/reference where was this fixed?
