### ISSUE TITLE
Group name & full name disappear

### ISSUE THREAD

**Issue by DeMoN100** [simplex-chat/simplex-chat#2108]
During creation of a group name if your screen rotates the text gets cleared out.
![grouptextpoof](https://user-images.githubusercontent.com/8564572/229099280-02cf4e2b-f324-4d0e-a8fa-8ca6a02ef6d8.gif)

**Comment by epoberezkin** [comment]
Thank you!

**Comment by DeMoN100** [comment]
> Thank you!

I would like to also let you know I have discovered this happens with welcome messages to groups as well. If there is text saved already new written unsaved text will be erased when screen rotates. This is happening in the latest version currently.

**Comment by avently** [comment]
@DeMoN100 

> During creation of a group name if your screen rotates the text gets cleared out

> I would like to also let you know I have discovered this happens with welcome messages to groups as well. If there is text saved already new written unsaved text will be erased when screen rotates

These issues were already fixed a couple of days ago. You can see the changes in the updated version of the app, for example, in the beta: https://github.com/simplex-chat/simplex-chat/releases/tag/v5.1.0-beta.0

Let me know if you still have the issues, I'll reopen.
