### ISSUE TITLE
(Bug) Simplex 4.6 video call camera footage not transmitted

### ISSUE THREAD

**Issue by PalmTamino** [simplex-chat/simplex-chat#2116]
Its just blank. Tested with iPhone 12 Mini and iPad Pro (both testflight version of simplex)
![BBFE8AF1-C67D-487F-8F6A-3A1DDA694477](https://user-images.githubusercontent.com/36358673/229246387-f9a80756-2213-4e52-a615-50e90b15a1b4.png)

**Comment by epoberezkin** [comment]
the problem is on another phone though - what's happening there?

**Comment by PalmTamino** [comment]
> the problem is on another phone though - what's happening there?

Cameras work on both. Just no received feed.

**Comment by laishulu** [comment]
Same for me.

I tested with others, both using ios.
we can hear each other, but we can only see ourselves.

**Comment by epoberezkin** [comment]
what is iOS version?

**Comment by PalmTamino** [comment]
> what is iOS version?

16.4.1
16.4 (back then)
and 16.3.1 (back then affected too)

**Comment by laishulu** [comment]
see：https://github.com/simplex-chat/simplex-chat/issues/2435

**Comment by epoberezkin** [comment]
yes, looks like a duplicate
