### ISSUE TITLE
[Bug] iOS no video picker XFTP

### ISSUE THREAD

**Issue by PalmTamino** [simplex-chat/simplex-chat#2126]
- With XFTP enabled, I still can’t choose videos from picker on iOS. Only from files picker.
- Videos are as a result still sent as files and not directly viewable in the app

(here you see example, i mean the middle option, there in the gallery it only shows photos)
![AA345ACA-D25F-4961-9567-FD9641926648](https://user-images.githubusercontent.com/36358673/229319910-8eeb77be-f529-42e2-a9b0-e0a1310bb22e.png)

4.6.1 137

**Comment by epoberezkin** [comment]
that's just not done yet :)

**Comment by PalmTamino** [comment]
oh ok

**Comment by epoberezkin** [comment]
can't wait too :)
