### ISSUE TITLE
Cant seem to locate the windows binary

### ISSUE THREAD

**Issue by Xanthus58** [simplex-chat/simplex-chat#2127]
Hey so I'm brand new to simplex and wanted to give it a test; I've got the android app which seems to work perfectly fine. I was even able to get the Linux version working by following the install guide [here](https://github.com/simplex-chat/simplex-chat/blob/stable/docs/CLI.md#%F0%9F%9A%80-installation) However when looking at the ["windows" section](https://github.com/simplex-chat/simplex-chat/blob/stable/docs/CLI.md#windows) all it says is to move a binary file; which i cant actually find anywhere. If i could get some help in installing the application for windows that'd be greatly appreciated.

Unless i have to build from source to get the windows binary and i'm not aware of that. As I assumed one would be provided

**Comment by shumvgolove** [comment]
Issue fixed, It's available under new release: https://github.com/simplex-chat/simplex-chat/releases/tag/v5.1.2

**Comment by dillfrescott** [comment]
It seems to have gone missing again for the latest release
