### ISSUE TITLE
Wrong binary in v1.0.3 release?

### ISSUE THREAD

**Issue by vsevolod-mineev** [simplex-chat/simplex-chat#215]
When I re-installed for version 1.0.3 using the install script I noticed that the version printed on login is 1.0.0

I then copied the binary from the release and sure enough the version printed is still 1.0.0 so either the binary is wrong or the version coded into the binary is wrong.

**Comment by epoberezkin** [comment]
The correct list version is 1.0.1, the 1.0.3 release is created by mistake
