### ISSUE TITLE
ios 15 issues: broken Japanese/Chinese input

### ISSUE THREAD

**Issue by gitbq** [simplex-chat/simplex-chat#2157]
When using ios 15 devices, there is a glitch meaning that typing any sentence in a non Latin keyboard like Chinese or Japanese is impossible.

For example on Chinese, typing two characters is fine, but after that the keyboard is unuseable.
Ios 16 fixes this issue, but it would be super helpful to support this feature on ios 15.

Thanks for all the time you devs spend on this app.

***tested and affected ios 15 versions include
15.5, 15.6.1, 15.7.4.

**Comment by gitbq** [comment]
Actually I have many friends who are wanting to try this, but as they need these non Latin languages, are unable to do so on these older devices.
Anything that could be done would be really appreciated.

**Comment by epoberezkin** [comment]
Could you maybe help with that please?

We're not 100% certain how "works" would differ from "doesn't work" – what would really help are two videos recorded on iOS 15 and iOS 16 showing incorrect and correct keyboard behaviours. Because to me it seems like it works on both (iOS 15.3.1, specifically, and some iOS 16) - I am using Chinese/Simplified (Pinyin QWERTY - it was the first in the list).

**Comment by epoberezkin** [comment]
also, would it help if you disable autocorrect and / or predictive keyboard?

**Comment by epoberezkin** [comment]
Settings > General > Keyboard > Toggle off the Predictive option

**Comment by epoberezkin** [comment]
Also, there is an option "Fuzzy Pinyin" - does toggling it on/off change anything? In my case it was off.

**Comment by epoberezkin** [comment]
Sorry, yet one more question - does it work correctly in say Signal or any other open-source app you know of?

**Comment by gitbq** [comment]
Thanks for the quick reply as always. You guys are great! 
I've been using these Asian keyboards with open source apps on all platforms over the last few years including session, signal etc and have never encountered this issue with any other app. Even on ios 15 this is the first issue I have ever encountered.  It's fair to say I'm a reasonably heavy user of many different apps. 
I have tried the things you suggested but I am fairly confident the problem doesn't lie there as this is common across all ios 15 devices I have tried including those from different countries. 
I will try and upload via pc or something because this app won't let me upload a video for some reason..

**Comment by gitbq** [comment]
Can I send the 2 videos via simplex?

**Comment by gitbq** [comment]
This is on iOS 16

https://user-images.githubusercontent.com/47218763/230719301-2937e45e-b0d3-4b74-816b-7188e82d5189.mp4

This is iOS 15


https://user-images.githubusercontent.com/47218763/230719331-cbb32b86-2517-4935-ab60-296ae12fe59c.mp4

**Comment by gitbq** [comment]
Basically after writing two characters the keyboard is unusable. Totally frozen. 
this only happens in simplex.

**Comment by gitbq** [comment]
I have multiple devices which all react the same, I several friends who also reported the same issue on their devices. This leads me to believe it isn’t due to some kind is user error on my own part.

**Comment by epoberezkin** [comment]
Hm. Exactly the same sequence doesn't freeze it for me in 15.3.1. Can we please compare the keyboard settings?

![image](https://user-images.githubusercontent.com/2769109/230721510-6bc3baca-65c9-4a93-ac15-0b697dd547cd.png)

![image](https://user-images.githubusercontent.com/2769109/230721532-eb5ba5e7-e33a-4b9b-a984-83f11ff40b49.png)

![image](https://user-images.githubusercontent.com/2769109/230721549-e09b186a-b56a-403c-987b-a6dbfe4ce2ab.png)

![image](https://user-images.githubusercontent.com/2769109/230721575-53f2dd5d-34d8-4473-9aed-03116e2ce16c.png)

**Comment by epoberezkin** [comment]
Please tell me where your settings are different, so far I cannot reproduce it on 15.3.1 (and there is no way to upgrade it to 15.7, only to 16). Also, if the settings are different anywhere, will the issue happen if you make them the same?

I am not suggesting that this is a user error, but we need to reproduce the issue on my device before it can be fixed. So something is different, we need to understand what exactly...

**Comment by gitbq** [comment]
My settings are exactly the same.

**Comment by gitbq** [comment]
So if you type in "nh" you get the option to pick ＂你好＂from the bar above the keyboard. And you can do this continually and keep selecting it so you can get something like this "你好你好你好＂is that right?

**Comment by gitbq** [comment]
I dug up another old device running 15.6.1.
It behaves exactly like the video above.

**Comment by gitbq** [comment]
I have now tested on several devices and the affected ios 15 versions include 15.5, 15.6.1, 15.7.4.
They all have the same issues.

**Comment by epoberezkin** [comment]
yes, if I type "nhnhnh" I can then pick "你好你好你好"

**Comment by epoberezkin** [comment]
but if I type "nh", then pick "你好", then the next time I type "nh" I cannot pick "你好"

**Comment by gitbq** [comment]
Exactly. This is the way the pinyin keyboard should work. Without any options to select it is basically frozen. Once the 你好 or whatever random two characters have been selected, nothing else can ever be selected as the top selection bar becomes frozen, meaning it will only show the comma, periad, question mark etc no matter what letters are pressed.

**Comment by epoberezkin** [comment]
going to remove notifications part, submit as another issue if it still persists.
