### ISSUE TITLE
How can you trust links are coming from who they say they are?

### ISSUE THREAD

**Issue by Darin755** [simplex-chat/simplex-chat#2166]
I know that you can share a invite link over SMS but I am concerned that someone could perform a man in the middle attack to intercept the link to change it.

### the problem

The problem is many people switch to simplex chat from less secure platforms. I don't think its improvable that someone could modify a link that is send though a different platform in order to send a different link to the destination. All you would need is a bridge that relays messages.

### a solution 

To mitigate against this risk I am currently asking my contacts questions that only they know the answer to. For closer contacts I am just sharing the qrcode in person.

### a fix?

I think it would be really cool to add the ability to add security questions to invite links. Such questions wouldn't be a perfect solution but they would help to add some security.

**Comment by epoberezkin** [comment]
To protect from link substitution you should do security code verification via some other channel: https://github.com/simplex-chat/simplex-chat/blob/stable/docs/guide/privacy-security.md#security-code-verification

**Comment by Darin755** [comment]
I understand that but it isn't entirely obvious to people who may not be as tech literate. Here's what I propose.

 1. Allow for the creation of untrusted links. Such links could be used for DM's on social media or a contact me button on a website.
 2. Highlight all untrusted chats as orange. People should be aware that they could be getting scammed or attacked
 3. Improve the verification process. The security code isn't the most obvious currently and there needs to a simple wirrard in the app that walks you 
 4. Enforce two factor sharing in the app. They need to be a button that starts the process to add a trusted contact. It should have a option for in person or a option with two share buttons. The sharing should enforce two different methods communication.
