### ISSUE TITLE
[Bug] [Android] no ringtone when screen is locked 

### ISSUE THREAD

**Issue by JvM-nl** [simplex-chat/simplex-chat#2173]
I have no ringtone when Android lockscreen is locked.
When i unlock it starts ringing . When i lock it again it keep ringing.
I have tested with Android 11,12 and 13

**Comment by epoberezkin** [comment]
duplicate of #1404?

**Comment by avently** [comment]
@JvM-nl, since you tried it on multiple devices, do you have some specific settings in the app or just use defaults? I tested on 12 (real device, emulator) and 13 (real device, emulator), can't reproduce. Before we tested on 11 (real device) as well.

**Comment by epoberezkin** [comment]
@JvM-nl Do you still have a phone that's not working? It might help...

**Comment by epoberezkin** [comment]
It seems like it was caused by custom ringtone, closing it.
