### ISSUE TITLE
IOS sample app missing libraries

### ISSUE THREAD

**Issue by wildiostonight** [simplex-chat/simplex-chat#2174]
Hi i tried downloading the sample app.
<img width="414" alt="Screen Shot 2023-04-12 at 1 34 31 PM" src="https://user-images.githubusercontent.com/130530580/231360564-9f16181a-2a76-4a71-9c9f-71b3c92872ef.png">

And there are some missing libraries? Can't seem to find the documentation for installation guide. Readme.md is empty

**Comment by epoberezkin** [comment]
The need to be built from Haskell code using Nix.
