### ISSUE TITLE
Blocked in China?  How will we proceed?

### ISSUE THREAD

**Issue by PalmTamino** [simplex-chat/simplex-chat#2176]
Hey, it seems like Simplex got blocked in China recently.

No connection without VPN possible anymore. It would be great if you could make it resistant.

**Comment by sith-on-mars** [comment]
Can turn on `use .onion hosts` in the preferences be a workaround?

**Comment by epoberezkin** [comment]
on itself it would only work if you use SOCKS proxy that connects via Tor, like Orbot.

**Comment by Darin755** [comment]
Could you use some of the anti censorship techniques from the Tor project? I think snowflakes can be used outside tor.

**Comment by TermsofService11** [comment]
you may deploy an SMP server of your own. it works well for me.
https://github.com/simplex-chat/simplexmq

**Comment by shumvgolove** [comment]
There's nothing we could do on our side. Closing.

**Comment by zpbooks** [comment]
I just solved the problem that the Windows client cannot be used in China even with a proxy turned on. You need to use a proxy program (v2rayN is recommended) and turn on Tun mode. There is no need to turn on any proxy options in SimpleX's network settings. Restart SimpleX and you can connect.

**Comment by zpbooks** [comment]
I just solved the problem that the Windows client cannot be used in China even with the proxy turned on. You need to turn on the Tun mode of your proxy program (v2rayN is recommended). There is no need to turn on any proxy options in the SimpleX network settings. Restart SimpleX and you can connect.
