### ISSUE TITLE
 Build Error: Missing 'libsimplex.so' file in Android Studio Project

### ISSUE THREAD

**Issue by TheTanmay1** [simplex-chat/simplex-chat#2197]
I am trying to build the Simplex Chat Android app from the source code provided in this repository (https://github.com/simplex-chat/simplex-chat), but I'm encountering a build error in Android Studio. The error I'm facing is related to a missing 'libsimplex.so' file:

ninja: error: 'T:/01)android_studio_projects/07)simplex_chatapp_github_18april2023/01)simplexapp_18april23_github1/apps/android/app/src/main/cpp/libs/arm64-v8a/libsimplex.so', needed by 'T:/01)android_studio_projects/07)simplex_chatapp_github_18april2023/01)simplexapp_18april23_github1/apps/android/app/build/intermediates/cxx/Debug/6e3c314a/obj/arm64-v8a/libapp-lib.so', missing and no known rule to make it

It seems that the 'libsimplex.so' file is not provided in the repository, and I'm unable to find any instructions on how to compile or obtain this file. Could you please guide me on the correct way to compile or obtain the required 'libsimplex.so' file for building the Android app? Your assistance would be greatly appreciated.

Thank you in advance for your help!

**Comment by danivideda** [comment]
I'm still having trouble with this for the past week. Can you tell us how did you solve this? Thanks

**Comment by umarmnaq** [comment]
> I'm still having trouble with this for the past week. Can you tell us how did you solve this? Thanks

https://github.com/simplex-chat/simplex-chat/issues/734#issuecomment-1151073393
