### ISSUE TITLE
Missing libs folder in the Android project.

### ISSUE THREAD

**Issue by TheTanmay1** [simplex-chat/simplex-chat#2203]
Hello,

I am trying to compile and run the Android project from the repository but encountered an issue during the build process. The error message indicates that the 'libsimplex.so' library is missing for the arm64-v8a architecture. Upon checking the repository, I noticed that the 'libs' folder containing the required '.so' files for different architectures is missing from the 'apps/android/app/src/main/cpp' directory.

Could you please provide the missing 'libs' folder with the required '.so' files or suggest an alternative solution to fix this build issue? I am unable to proceed with my work on the project without resolving this error.

Thank you for your assistance.

**Comment by darcycui** [comment]
Could you tell me how to fix this? I am still troubled in this question !
