### ISSUE TITLE
latest 51 commits are having some issue, due to which when creating account in android app its showing some error on dialog box

### ISSUE THREAD

**Issue by TheTanmay1** [simplex-chat/simplex-chat#2239]
I yesterday pull some around 51 commits from your simplex chat stable branch to my fork repo and then when I am trying to run the android app and when clicking on create account, it throwing some errors and showing some code on dialog box, kindly fix that issue .

**Comment by shumvgolove** [comment]
You should build Android app based on the tag like [this](https://github.com/simplex-chat/simplex-chat/releases/tag/v5.0.0).

**Comment by TheTanmay1** [comment]
i have tried merging updates from tagv5.0.0 still it shows this error, when clicking on create profile, it shows this error :-
apiCreateActiveUser: chatCmdError invalid json {
                                                                                                        "type": "error",
                                                                                                        "errorType": {
                                                                                                            "type": "userExists",
                                                                                                            "contactName": "thetanmay1"
                                                                                                        }
                                                                                                    }
                                                                                                    
                                                                                                    
![photo_2023-04-27_04-27-11](https://user-images.githubusercontent.com/70553394/234720216-5f39f88e-726b-495f-b1b6-f336301f3b84.jpg)

**Comment by shumvgolove** [comment]
Please specify the exact steps to reproduce the issue:

1. `git clone ...`
2. `cd ... `
3. `nix build ... `
4. etc.
