### ISSUE TITLE
Standalone desktop client

### ISSUE THREAD

**Issue by epoberezkin** [simplex-chat/simplex-chat#2281]
Not linked to mobile client in any way, can be used independently

**Comment by PalmTamino** [comment]
But please make it possible to use the same account there, only then it would make sense for me.

**Comment by ElsAr4e** [comment]
Actually this would require Multi-Device?

**Comment by ElsAr4e** [comment]
So if you use multiple devices at the same time (Desktop - Mobile or Desktop - Desktop) you have to use multiple accounts?

**Comment by epoberezkin** [comment]
at this stage - yes. Connecting the same profile to two or more devices will be possible later, most likely with one way sync, when 1 device is the leader and desktops are followers.

**Comment by dillfrescott** [comment]
Desktop gui clients are the only thing stopping me from using this as my main messenger! Can't wait!

**Comment by ElsAr4e** [comment]
Will the desktop client also be available for Windows 10 32-bit?

And for 32-bit versions of Linux distros?

**Comment by dillfrescott** [comment]
@ElsAr4e Hopefully!

**Comment by PalmTamino** [comment]
> Will the desktop client also be available for Windows 10 32-bit?
> 
> 
> 
> And for 32-bit versions of Linux distros?

Sorry, but at this point just move on from your 20 year old pc... I really don't want the simplex team to waste time for an architecture that got replaced 2 decades ago.

**Comment by roihershberg** [comment]
Support for 32 bit is not dependent on the team but on the Compose Multiplatform framework which [doesn't support](https://github.com/JetBrains/compose-multiplatform/blob/master/VERSIONING.md#supported-platforms) 32 bit targets.
So currently the answer is no and will probably continue to be no as I don't think the framework will be adapted to those targets.

**Comment by x80486** [comment]
> Support for 32 bit is not dependent on the team but on the Compose Multiplatform framework

How do you know that `Compose Multiplatform` is what's going to be used for the desktop application? :thinking:

**Comment by roihershberg** [comment]
I have looked at the draft PR called "Multiplatform support". The goal is to share as much as possible between the Android app and the Desktop app so there won't be another platform to maintain with its own codebase and technology stack. This will allow more time to develop new features instead of propagating features slowly to all platforms with the burden it brings.

**Comment by PLAYERUNKNOWNHatsune01** [comment]
Please don't be Electron application. That's only my wish!

**Comment by ElsAr4e** [comment]
@epoberezkin So does Kotlin Multiplatform support Windows 10 32-bit and/or 32-bit Linux-distros?

Are there any plans to support these operating systems?

**Comment by TheFuzzStone** [comment]
> Please don't be Electron application. That's only my wish!

Same here. 

I don't think Eugene would do something as stupid as Matrix/Element.

**Comment by Mikaela** [comment]
I understand Compose/Kotlin Multiplatform to be separate from Electron, so that concern is addressed, but I wonder whether it will support Wayland (compare to [Briar Desktop](https://code.briarproject.org/briar/briar-desktop/-/issues/339)).

**Comment by painkiller1717** [comment]
Somebody knows when this great app would be released for can use it on Linux? And also Windows for people don't use Linux. I would like see an Appimage of SimpleX Chat, like Session for example. I saw this but I don't knows is reliable and if is also for normal users and not developers: https://github.com/sshine/simplex-desktop

**Comment by x80486** [comment]
And just to drop another unrelated comment, for `Linux`, it would be great to have `Flatpak` support — if possible, right from the beginning.

Certainly not everyone is happy about this (or anything else), but `Flatpak` works almost flawlessly on every distribution, and this is one of those applications that could take full advantage of that distribution format.

Not sure how `Kotlin Multiplatform` works, but if it has support for all those required portals, you are all set.

**Comment by painkiller1717** [comment]
> And just to drop another unrelated comment, for `Linux`, it would be great to have `Flatpak` support — if possible, right from the beginning.
> 
> Certainly not everyone is happy about this (or anything else), but `Flatpak` works almost flawlessly on every distribution, and this is one of those applications that could take full advantage of that distribution format.
> 
> Not sure how `Kotlin Multiplatform` works, but if it has support for all those required portals, you are all set.

Flatpak would be good, but I rather Appimage format, ready to use in almost every distro I think, if I'm not mistaken. But I hope they consider both.

**Comment by PalmTamino** [comment]
> > And just to drop another unrelated comment, for `Linux`, it would be great to have `Flatpak` support — if possible, right from the beginning.
> > Certainly not everyone is happy about this (or anything else), but `Flatpak` works almost flawlessly on every distribution, and this is one of those applications that could take full advantage of that distribution format.
> > Not sure how `Kotlin Multiplatform` works, but if it has support for all those required portals, you are all set.
> 
> Flatpak would be good, but I rather Appimage format, ready to use in almost every distro I think, if I'm not mistaken. But I hope they consider both.

Sorry, but i’m also more in for flatpak, appimage feels like cheap sideloading, no updates, not those cool features like sandbox (flatseal app), no app icon,… 

Please just use flatpak

**Comment by Hasshu** [comment]
Regarding Flatpak, see #1363.

**Comment by RpiController** [comment]
> at this stage - yes. Connecting the same profile to two or more devices will be possible later, most likely with one way sync, when 1 device is the leader and desktops are followers.

I'm okay with this. It's not that hard to make group conversations with various devices... such as JDoggMobile, JDoggWork, JDoggHome, etc. So please just prioritize making it available first, then work on the fancy sync stuff later.

**Comment by dillfrescott** [comment]
Is there a beta/alpha version of the desktop client we can test?

**Comment by Yiannis128** [comment]
> Is there a beta/alpha version of the desktop client we can test?

There's one now it seems: https://github.com/simplex-chat/simplex-chat/releases/tag/v5.3.0-beta.1

**Comment by dillfrescott** [comment]
Ah excellent. Thank you!

**Comment by RpiController** [comment]
> > Is there a beta/alpha version of the desktop client we can test?
> 
> There's one now it seems: https://github.com/simplex-chat/simplex-chat/releases/tag/v5.3.0-beta.1

There's no instructions provided how to install or use. The windows file you have to add .exe to after downloading. Running it only takes you to a Terminal version... not exactly what I would call "Desktop"... but eh, it's still kinda cool.

**Comment by dillfrescott** [comment]
The desktop gui version is only for mac and linux as of right now it seems

**Comment by valtoree** [comment]
exciting times yeh def need desktop app for me to move away from element/riot

**Comment by Yiannis128** [comment]
This is still a beta release so probably wait until the next proper release and there might be a windows version.

**Comment by valtoree** [comment]
@Yiannis128 👍

**Comment by Josh-SMU** [comment]
On Debian Bookworm, Simplex Desktop will not run (both the linux and ubuntu variants in the beta release) due to the following error:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/simplex/libs/libapp-lib.so: libffi.so.7: cannot open shared object file: No such file or directory`

I have libffi8 and libjffi-java installed; this has not made a difference.

**Comment by jittygitty** [comment]
@epoberezkin @avently Once you have desktop clients, I think you'll be golden! 
I currently use Element Desktop (but hate bloated electron), waiting for simplexDesktop. 
Have you considered FLUTTER instead of KOTLIN?

**Comment by avently** [comment]
@Josh-SMU don't worry about that lib. Next release will not require you to have it installed, so just works. Let us know lf you have other issues with the app

**Comment by epoberezkin** [comment]
> Have you considered FLUTTER instead of KOTLIN?

What would be the motivation to re-write the existing code? Flutter is as bad as Kotlin, so why change it. In fact, all UI frameworks seem quite bad, it's just very hard to make a good one, so the best is the one we already have.

> waiting for simplexDesktop.

Beta is available in releases! 🚀

**Comment by jittygitty** [comment]
@epoberezkin Sorry, I didn't know everything was in Kotlin Multiplatform already, I thought you were contemplating switching to it to gain cross-platform, desktop etc.

Also isn't the current desktop Beta just a command-line console only version so far?

I agree with you on there's no 'perfect' platform. If choosing from scratch, I like flutter for the "fast iterations" with hot reloading (is Kotlin compiler still very slow?) and I think it makes "cross-platform UI" easier, but perhaps Kotlin will catch-up in time.
And yea will be happy to try out Desktop when it has full GUI instead of console. (I've read that GUI desktop version is only for Mac and Linux currently, not for windows.)

**Comment by epoberezkin** [comment]
> Also isn't the current desktop Beta just a command-line console only version so far?

Nope, there is GUI - getting to a very usable state with the next release before Monday. But the one in GitHub is alright too.

> is Kotlin compiler still very slow?

Hard to be slower than Haskell :))
There are live previews, and it’s still quite fast.

> I've read that GUI desktop version is only for Mac and Linux currently, not for windows.

Working on Windows build now - might be available by the end of the next week.

**Comment by jittygitty** [comment]
@epoberezkin So did you pick Haskell over golang (or rust for that matter) just to prove you're much smarter than the rest of us? :)  (I got scared of Haskell code saying: "If it even compiles at all, it's correct." cuz I can get compiler errors out of the easiest langs.) I will definitely start using the chat soon as Win-Desktop's out. thx!

**Comment by arch-btw** [comment]
Great work @epoberezkin, looks good!

![simplex_desktop](https://github.com/simplex-chat/simplex-chat/assets/57669023/21802a44-043c-4c4e-9aca-cc7b9d71abd3)

**Comment by zevlee** [comment]
I'm very excited to see the release of the desktop GUI! When can we expect to see voice/video call functions working?

**Comment by RpiController** [comment]
Question... Will the Windows desktop GUI client have the ability to paste pictures/screenshots from the clipboard? For me, that's the whole point of having the desktop version... so I can use the ScreenSnip tool, then Ctl-V it into chat.

**Comment by Josh-SMU** [comment]
Will there be a (non-Mac) aarch64 build? For Debian/Ubuntu on arm64 devices such as Pinephone

**Comment by aicynide** [comment]
@Josh-SMU install the apk in pinephone

**Comment by Josh-SMU** [comment]
> @Josh-SMU install the apk in pinephone

I dont want the overhead of Waydroid

**Comment by RpiController** [comment]
Why has this "issue" 2281 been marked as Closed?
Can someone explain why the Windows desktop version seems to be given less priority than any of the other platforms?
If it's a matter of complexity and takes more time and effort, then it makes sense for a longer release time.

Hopefully it's not because someone thinks that there are more people waiting for the Pinephone/Ubuntu/xWayland/Linux/Nintendo/Gameboy version, versus the number of people who are anxiously waiting for the Windows version before they ask all their friends to switch over to SimpleX.

**Comment by dillfrescott** [comment]
> Why has this "issue" 2281 been marked as Closed? Can someone explain why the Windows desktop version seems to be given less priority than any of the other platforms? If it's a matter of complexity and takes more time and effort, then it makes sense for a longer release time.
> 
> Hopefully it's not because someone thinks that there are more people waiting for the Pinephone/Ubuntu/xWayland/Linux/Nintendo/Gameboy version, versus the number of people who are anxiously waiting for the Windows version before they ask all their friends to switch over to SimpleX.

I might add that even though Linux has gained popularity in recent years, Windows still dominates the usage percentage worldwide. Therefore, giving windows less priority isn't making much sense to me.

**Comment by avently** [comment]
Windows build is taking longer to make. It's not because we don't like Windows or something like that.

**Comment by dillfrescott** [comment]
> Windows build is taking longer to make. It's not because we don't like Windows or something like that.

Oh okay. My misunderstanding

**Comment by zevlee** [comment]
Given that the desktop client currently lacks voice/video call functionality, should I make an issue so that users can track the progress of this feature?

**Comment by epoberezkin** [comment]
> If it's a matter of complexity and takes more time and effort, then it makes sense for a longer release time.

yes, working on Windows, it is certainly a priority. CLI build was just fixed, desktop is next.

It's been additionally complicated with GHC 9.6.2 migration.

> versus the number of people who are anxiously waiting for the Windows version before they ask all their friends to switch over to SimpleX.

We understand that Windows is exceptionally widely adopted platform, and we have a very pragmatic prioritisation process. Great to hear that it's needed.

**Comment by zevlee** [comment]
I created an issue at https://github.com/simplex-chat/simplex-chat/issues/3060 to track the progress of voice/video calls in the desktop application.

**Comment by RpiController** [comment]
> I created an issue at #3060 to track the progress of voice/video calls in the desktop application.

How do you "track progress" other than being subscribed to the Releases?
There's no web client.  The Windows version doesn't even have a beta version yet. 
That's like wanting to track the progress of telepathic steering controls on flying cars.... Maybe just wait for the flying car first?

I'm going to create an issue for tracking Bitcoin Lighting QR code sharing in the Quantum Nostr version.

**Comment by jittygitty** [comment]
@RpiController I keep on getting the same E-Mail with a link to your comment which does not exist when I click the link. I don't see any sign of your comment here, just in my email, not sure if some Github glitch.

**Comment by RpiController** [comment]
> @RpiController I keep on getting the same E-Mail with a link to your comment which does not exist when I click the link. I don't see any sign of your comment here, just in my email, not sure if some Github glitch.

I think it's super awesome that this forum allows direct communication with the devs, and I don't want to abuse the privilege. 
I was told this forum is not for socializing or asking silly off-topic questions... especially not debating with other commenters. 
Some comments sound like a kid in the backseat constantly saying, "Are we there yet? Are we there yet?" (My own included)

So yeah, I deleted a previous comment and I will be deleting this one also.
Not sure about Github's email notifications... maybe there is a bug.

**Comment by avently** [comment]
Windows build is out:
https://github.com/simplex-chat/simplex-chat/releases/tag/v5.4.0-beta.0

Please, share your feedback once you try it

**Comment by RpiController** [comment]
Looks good! Thank you, thank you!

My only requests are to enable pasting pictures/images (Ctrl+V), and enable .gif animations.

**Comment by jittygitty** [comment]
@avently Many thanks for the Windows build! Just installed it and started a discussion with Developers since I didn't have anyone else to test with for now. That was a good idea to add the "chat with developers" function into the chat. I had asked if we can have a PORTABLE version, or how we can move entire chat in a folder to another PC.

**Comment by dillfrescott** [comment]
Its really great. I guess the only downside is that it looks like its still made for mobile with the big buttons and text boxes and stuff. Making it look a bit like running an android app on bluestacks. But besides that its really really good!

**Comment by k4r4b3y** [comment]
>it looks like its still made for mobile with the big buttons and text boxes and stuff.

Yeah, it is an eyesore. Not only that, on laptops with low resolution screens (like thinkpad X230), some of the buttons are so large that they push other buttons off-screen. It looks ugly and barely-functional.

I hope this resolution/UI elements proportion stuff will get fixed soon.

Apart from that, desktop app should have a tray icon on Linux.

**Comment by daic11** [comment]
Please need Linux Arm (aarch64) version for Desktop Gui Application.
