### ISSUE TITLE
Use the same profile on desktop.

### ISSUE THREAD

**Issue by epoberezkin** [simplex-chat/simplex-chat#2311]

**Comment by Alch-Emi** [comment]
Continued from [Issue #2281](https://github.com/simplex-chat/simplex-chat/issues/2281#issuecomment-1523771857), but moved to this issue because it seems like a more relevant location.  How would the solution proposed in the linked comment handle the leader device going offline, either temporarily (e.g. a phone going being placed in airplane mode, a laptop being closed) or permanently (a lost phone runs out of battery never to be rebooted, desktop computer's hard-drive fails)?

**Comment by shumvgolove** [comment]
Related: https://github.com/simplex-chat/simplex-chat/issues/444

**Comment by hpk42** [comment]
Why is it necessary to have a leader device?

**Comment by alltheseas** [comment]
> handle the leader device going offline

Is there a leader device, or is this an assumption @Alch-Emi ?

**Comment by Alch-Emi** [comment]
@alltheseas The linked comment was posted by the developer, where he explicitly says that a leader device system is "likely".  The quoted text in my previous comment is the entire text of the original comment.

**Comment by dwt** [comment]
This seems to be 'just' the feature to connect to the mobile over the local network and share the profile that way? 

Am I misunderstanding something here?

If so, we either need to clarify that this bug should be about a true multi device account that can be used on as many devices as I want without one leading device (mobile) having to be present, or we should add another bug that signifies that.

**Comment by quite** [comment]
> This seems to be 'just' the feature to connect to the mobile over the local network and share the profile that way?
> 
> Am I misunderstanding something here?

This is correctly understood. There is a "simplex desktop app" that can be linked to simplex on a mobile app (at least Android). The desktop app can then be used while these remain linked. Also note that while they are linked, the mobile app is not usable (for messaging etc) at all.

**Comment by Wisdompure** [comment]
Oui j'ai un compte mais 2 appareils mobiles en effet.


Le lun. 13 mai 2024, 08:46, Narasimha-sc ***@***.***> a
écrit :

**Comment by alltheseas** [comment]
> This seems to be 'just' the feature to connect to the mobile over the local network and share the profile that way?

> Am I misunderstanding something here?

My understanding was this is same as signal's link mobile to desktop.
