### ISSUE TITLE
Longer voice messages (probably require different UI to play)

### ISSUE THREAD

**Issue by epoberezkin** [simplex-chat/simplex-chat#2322]

**Comment by PalmTamino** [comment]
Yes please, but then also add an option to change speed too.

**Comment by epoberezkin** [comment]
I don't quite understand how you contact can steal audio? Can you maybe explain the attack you think about?

**Comment by PalmTamino** [comment]
> Yes please, but then also add an option to change speed too.

@epoberezkin Will this be added too to next release?
