### ISSUE TITLE
Can't join #SimpleX-Group-3 on Android

### ISSUE THREAD

**Issue by jonhermansen** [simplex-chat/simplex-chat#2325]
Steps to reproduce:

1. Install latest SimpleX version from F-Droid (5.0 at time of this writing)
2. In browser, navigate to this Github project README
3. Click link to join [#SimpleX-Group-3](https://simplex.chat/contact#/?v=1-2&smp=smp%3A%2F%2Fhpq7_4gGJiilmz5Rf-CswuU5kZGkm_zOIooSw6yALRg%3D%40smp5.simplex.im%2FeDEgekVhh0zIBYvUupGWZ96kiBEMbXwK%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEAS7Z3zQyOhZ9o1qzI9OTZRySpkFTagdLMa6Rc7opuNh4%253D%26srv%3Djjbyvoemxysm7qxap7m5d5m35jzv5qq6gnlv7s4rsn7tdwwmuqciwpid.onion&data=%7B%22type%22%3A%22group%22%2C%22groupLinkId%22%3A%22cG3W1qxZGzyrvHTugx16bg%3D%3D%22%7D)
4. Continue to next step by clicking "Open" button which links to simplex:/ protocol link
5. In SimpleX app, click again to request connection to the room

Expected Results:
I can join the chat using same process as joining old chat room, group 2

Actual Results:
![Screenshot_20230426-020217](https://user-images.githubusercontent.com/660911/234386263-a9628a71-71a2-4528-9960-3ae15f3bac1e.png)

Perhaps the link is one time use only, or somehow not copied correctly?

Also tried on multiple networks, with and without VPN...

**Comment by doomguy** [comment]
Same here on iOS with App version v5.0 (144)

**Comment by jonhermansen** [comment]
By the way, this also effects 4.6.1 from F-Droid too.

**Comment by epoberezkin** [comment]
the group link was removed temporarily, a different link is now available. Please note the updated participation rules in this section: https://github.com/simplex-chat/simplex-chat#join-user-groups

Sorry for the inconvenience!
