### ISSUE TITLE
HOWTO avoid notifications from the CLI/terminal app (Linux)

### ISSUE THREAD

**Issue by kseistrup** [simplex-chat/simplex-chat#2340]
For a long time I have been very annoyed that the CLI SimpleX is sending out notifications that pops up in the graphical user interface on my Linux PC: I shouldn't have to use my mouse to handle messages from a CLI app.

Today I was extra annoyed, so I decided to `grep` the source in order to see how SimpleX is sending its notifications.

Lucky me, SimpleX is simply using the CLI command `notify-send`. This means I can get completely rid of the notifications even without requiring a change in the SimpleX CLI command.

I know at least one other person who is annoyed, so here's my solution:

### Step 1

Create a “fake“ binary directory that only SimpleX knows about:

```sh
$ mkdir -p ~/.simplex/bin
```

### Step 2

Create a “fake” `notify-send` command inside the directory we made above:

```sh
$ cat <<EOF > ~/.simplex/bin/notify-send
#!/bin/sh
exit 0
EOF
^D
$ chmod +x ~/.simplex/bin/notify-send
```

### Step 3

Make sure `simplex-chat` sees our version of `notify-send` before it sees the real `notify-send`:

```sh
$ # Start simplex-chat like this (or make a script that does the same thing):
$ env PATH="$HOME/.simplex/bin:$PATH" simplex-chat  # and possibly more arguments and/or switches
```

### Step 4

Enjoy a silent SimpleX experience! :dove: 

----

PS: The notification thing should probably have a real main switch in the CLI app, but until then the above works like a charm.

----

Documentation:

* https://github.com/simplex-chat/simplex-chat/blob/stable/src/Simplex/Chat/Terminal/Notification.hs#L54

----

Edit: Add missing `^D` + a couple of other typos

**Comment by vsevolod-mineev** [comment]
Jesus...

I'm not sure if it'll help but I'll petition Evgeny.

**Comment by epoberezkin** [comment]
The option is coming :)))

**Comment by a-p-jo** [comment]
> The option is coming :)))

@epoberezkin How do I use it? What's the command?
