### ISSUE TITLE
UI: add a design for voice messages in the style of other messengers.

### ISSUE THREAD

**Issue by zhoska** [simplex-chat/simplex-chat#2353]
For voice messages, it would be worth adding a moving audio message slider so that it is possible to rewind a long voice message to a certain point and not listen to it all over again

**Comment by flypenguin** [comment]
i think this is done? it's subjectively ugly and not at all fluent (iOS), but it's done.

**Comment by epoberezkin** [comment]
Will do for now indeed. Agreed re ugly-ish.
