### ISSUE TITLE
Theme naming system

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#2380]
Might you add an hex value as naming model?

Instead of simplex.theme --> 5F23A9.theme

If I have ten different theme models, I can immediately recognized each one from their hash code.

**Comment by epoberezkin** [comment]
you can just rename files, without being constrained to any naming scheme. Theme can be imported from any file.

**Comment by epoberezkin** [comment]
Btw, would you be interested to contribute the themes you like using to a catalogue, if we were to add it here on GitHub?

**Comment by epoberezkin** [comment]
Great! I'll prepare a submission guide for the catalogue in a couple days - for now you can just drop it here :)

Also, if there are some colors you really want to change but they are not available to change - let us know :)

**Comment by epoberezkin** [comment]
just drag and drop? maybe they don't allow it any more. You can just paste the text as well.

**Comment by epoberezkin** [comment]
yes, you can open it in the editor, it's just a text

**Comment by epoberezkin** [comment]
[serrq.txt](https://github.com/simplex-chat/simplex-chat/files/11401970/serrq.txt)

**Comment by epoberezkin** [comment]
[1.txt](https://github.com/simplex-chat/simplex-chat/files/11401997/1.txt)
