### ISSUE TITLE
Removing unnecessary "stop chat" button (with automation)

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#2385]
The button in question allows access to functions such as database export.

Most people in the world don’t have advanced computer skills, and that button is a barrier and an inconvenience.

My point of view is this: removing that button completely (it will only exist in the CLI), and automating the on/off gate whenever it needs to do so to allow access to critical functions whenever it needs it.

It will be automated. It will no longer need to move it manually.

**Comment by theAkito** [comment]
I would propose for this to be the default, while keeping the functionality itself intact. For me, as someone with "advanced computer skills", it is a neat little helpful tool of many, which makes the app more usable to me.

This is my proposal.

Change the behaviour as you describe. But, if I toggle the "Allow Stopping Chat Explicitly" option in the Advanced Settings to "on", I want to have this button back, so I have full control over the chat process. 🙂
