### ISSUE TITLE
Add built in tor to connect to tor without orbot

### ISSUE THREAD

**Issue by User1l0** [simplex-chat/simplex-chat#2397]
I've seen open source bitcoin app Green Wallet uses built in tor, i think for this thing the code can be scrapped from green wallet.
There's also session messenger app that uses onion like routing specially made for messaging. I hope in the future easy to use anonymity can be the part of this app too.

**Comment by HostFat** [comment]
Tor integrated (and maybe enabled by default), is a good way to instantly reach the nearly perfect privacy to the end user.

**Comment by epoberezkin** [comment]
Some comments on why we didn't embed Tor are here: https://simplex.chat/faq/#why-dont-you-embed-tor-in-simplex-chat-app
