### ISSUE TITLE
SimpleX using IPFS Network?

### ISSUE THREAD

**Issue by User1l0** [simplex-chat/simplex-chat#2406]
I think making this messenger work on ipfs network can resolve lot of issues, for example for groups, instead of every user caching the media and storing on it's phone making this app become a storage drainer can be solved by making the SimpleX working like telegram by storing the files in a cloud making them accessible easier and faster to instantly load the file you want and then cache on your device, but with SimpleX in encrypted and anonymous decentralized way of course.

**Comment by Mikaela** [comment]
I am not sure if privacy of IPFS is compatible with SimpleX. I have previously written about this at https://github.com/matrix-org/matrix-spec/issues/98#issuecomment-1055686023.

**Comment by Scripter17** [comment]
Actually, [quiet](https://github.com/TryQuiet/quiet) uses per-group IPFS networks to be serverless *and* allow you to get files from currently offline members of groups. Granted, in one to one conversations it's not very applicable, but there is precedence

What's more relevant is something like [Send My](https://positive.security/blog/send-my), a method of sending messages via apple's "Find My" network

Most interestingly, this paragraph seems to imply that apple's "Find My" database is effectively the same as IPFS. Anyone can get any message, but only the intended recipient can decrypt it

> However, most interestingly for us, Apple does not know which public keys belong to your AirTag, and therefore which location reports were intended for you. This means the endpoint to request location reports for a specific key id does not perform any authorization (but you need to be authenticated with any Apple ID to access the endpoint).

Assuming I'm reading this right, the design aspect has already been done
