### ISSUE TITLE
Servers Down

### ISSUE THREAD

**Issue by x80486** [simplex-chat/simplex-chat#2419]
I'm sure this is not the best way to report this, but I see all the servers (`SMP` and `XFTP`) down.

When I run the test it says that `Test failed at step Connect. Possibly, certificate fingerprint in server address incorrect`. On the other hand, the [status page](https://status.simplex.chat/) states there are no problems :thinking:

**Comment by epoberezkin** [comment]
Is it still the case for you?

**Comment by epoberezkin** [comment]
The test doesn't differentiate why it failed to connect - it may be network issue.

**Comment by x80486** [comment]
I checked in the afternoon and everything was fine.
