### ISSUE TITLE
All links to blog posts on the website are 404ing

### ISSUE THREAD

**Issue by blakeashleyjr** [simplex-chat/simplex-chat#2433]
When reading the docs (or the website in general) any link to a blog post is 404ing.

For example, in this doc there is a [link](https://simplex.chat/docs/guide/send-messages.html) to a blog post about the rationale behind not forcing data deletion on other parties, but it 404s. It should go [here](https://simplex.chat/blog/20221206-simplex-chat-v4.3-voice-messages.html#irreversible-message-deletion), but instead it goes [here.](https://simplex.chat/docs/guide/blog/20221206-simplex-chat-v4.3-voice-messages.html#irreversible-message-deletion)

It has something to do with the shorthand used to link in the markdown, but the same shorthand works for images. So not sure what the issue is.

**Comment by epoberezkin** [comment]
fixed
