### ISSUE TITLE
theme colors hex code

### ISSUE THREAD

**Issue by zen0bit** [simplex-chat/simplex-chat#2434]
It would be great if we can add color by hex code in addition to color chooser

**Comment by epoberezkin** [comment]
you can:

1. export the theme
2. edit hex codes
3. import it back

I though about this idea for about a minute and decided that for most people it's not needed, and for the rest this workaround would do :)

**Comment by epoberezkin** [comment]
it's now available in v5.8-beta.3 if you enable dev tools.
