### ISSUE TITLE
New way to bypass Chat Control EU law (in case of)

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#2481]
These guys are genious.

A keyboard with built-in encrypt/decrypt tool, 100% indipendent from transport (it runs with all messengers). No server needed.

A new arrow is available in case EU law requires messengers opening their cryptography.

https://github.com/amnesica/KryptEY

**Comment by ElsAr4e** [comment]
Actually something like Silence would be great: https://git.silence.dev/Silence/Silence-Android

**Comment by Mikaela** [comment]
I think this should possibly be converted to a discussion
