### ISSUE TITLE
[Feature request] Disable attachments per contact (Independently of voice messages) / Allow Text-chat only

### ISSUE THREAD

**Issue by ElsAr4e** [simplex-chat/simplex-chat#2482]
I know it is supported that you can disable voice messages.

But I would also like to have an option to disable attachments - either for one or some specific file type(s) (like pdf, docx, png, etc.) or for any file type.

So for example contact 1 can only send you files that are images, contact 2 can only send you attachments that are pdfs, etc.

Maybe you can also limit the size of attachments per contact? (Not sure if this would generate too much metadata?)

And of course you should be able to disable receiving attachments (with/without any error message) but allow at the same time receiving voice messages.

**Comment by x80486** [comment]
That level of granularity will never end. This application already have too many options/toggles. What's the end goal for you?

**Comment by epoberezkin** [comment]
we will release it in v5.3 for the sake of simpler moderation in public groups.
