### ISSUE TITLE
[Q]: what is the file size limit ? 

### ISSUE THREAD

**Issue by freqmand** [simplex-chat/simplex-chat#2539]
### Question

what is the file size limit in group and direct chat?

**Comment by freqmand** [comment]
and after 2 days ? will the media be deleted from the group chat or how ?

**Comment by epoberezkin** [comment]
It will be only deleted from the relays, so it won’t be possible to receive after two days. If you received it, it will be stored locally indefinitely, until you delete it. You can use disappearing messages to make them removed.
