### ISSUE TITLE
[Feature]: Allow to re-create direct contact with group member

### ISSUE THREAD

**Issue by spaced4ndy** [simplex-chat/simplex-chat#2568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

all

### Feature

Currently a direct contact is created with each new group member who joins a group. It is then possible to send a direct message to a group member via Group Member view -> "Send direct message" button.

If one deletes a contact which is linked to a group member, it is no longer possible to send a direct message to that group member. A solution would be to add a new feature for negotiating a direct contact connection with a group member without a linked contact.

**Comment by EchedeyLR** [comment]
I can confirm.

**Comment by epoberezkin** [comment]
this is done
