### ISSUE TITLE
New UI design proposal

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#2640]
Show/Unshow favorites and search buttons are miles far away from my finger.

Might you shortening the distance?

You might also integrate pencil button in the same bar.

![1000029377](https://github.com/simplex-chat/simplex-chat/assets/113377431/01e65b76-e3f8-4955-8d75-f1108fef5780)

**Comment by Icy-Thought** [comment]
In my opinion, something similar to Signal's drag release to filter could be a better choice here.
