### ISSUE TITLE
[Bug]: Crash on launch - cannot locate symbol "getentropy"

### ISSUE THREAD

**Issue by franzos** [simplex-chat/simplex-chat#2689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

8.1.0

### App version

5.1.3

### Current Behavior

Crash.

### Expected Behavior

No crash.

### Steps To Reproduce

1. Download for the first time
2. Start -> Crash

### Relevant log output

```shell
07-13 12:07:31.003  9530  9530 E AndroidRuntime: FATAL EXCEPTION: main
07-13 12:07:31.003  9530  9530 E AndroidRuntime: Process: chat.simplex.app, PID: 9530
07-13 12:07:31.003  9530  9530 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "getentropy" referenced by "/data/app/chat.simplex.app-2o1fQdLmUQjDdRYljXJO7Q==/lib/arm64/libsimplex.so"...
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1657)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at chat.simplex.app.SimplexApp.<clinit>(SimplexApp.kt:256)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:1103)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:1088)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5770)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6558)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
07-13 12:07:31.003  9530  9530 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
07-13 12:07:31.005  2284  3733 W ActivityManager:   Force finishing activity chat.simplex.app/.MainActivity_default
07-13 12:07:31.006  2284  3733 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
07-13 12:07:31.009  2284  3733 E minilogger: make mLogDir failed
07-13 12:07:31.009  2284  3733 E minilogger: make mAppCrashDir failed
07-13 12:07:31.009  2284  3733 E minilogger: make mAppAnrDir failed
07-13 12:07:31.009  2284  3733 E minilogger: make mSystemCrashDir failed
07-13 12:07:31.009  2284  3733 E minilogger: make mCounterDir failed
```

**Comment by franzos** [comment]
This is happening on both Blackberry Key1 and Key2 (BBF100-6).

> We won't be able to provide a separate APK version for android that doesn't use getentropy, at least for now, as absolute majority of Android devices support it. Sorry!

Just curious, is this build specific, or was this not available as of 8.1.0?

It's too bad, because I've never had an app crash because of this, and I doubt I'm going to change my phone to use Simplex. It'll have to wait, till it breaks then.

**Comment by epoberezkin** [comment]
It's specific to OS distribution it seems, generally the app works on stock Android 8.

**Comment by pjanx** [comment]
Android 8.1, LineageOS 15.1 has the same issue.

**Comment by pjanx** [comment]
https://www.gnu.org/software/gnulib/manual/html_node/getentropy.html says:

> This function is missing on some platforms: glibc 2.24, Mac OS X 10.11, FreeBSD 11.0, NetBSD 9.0, OpenBSD 5.5, Minix 3.3, AIX 7.1, HP-UX 11.31, IRIX 6.5, Solaris 11.0, Cygwin 1.7.x, mingw, MSVC 14, Android 8.1.

**Comment by epoberezkin** [comment]
https://upload.disroot.org/r/7d8s9muz#Wl1fOjpkZj6g03ztVAjduU2ARM5adFbLLg0TmNj4/KI=

https://upload.disroot.org/r/6ooF0aqo#eY/Nw+7LyRIrnaZmL0yrWIrcsxko58UrHPxEv3wYJZk=

Can you please try one of this APKs on Android 8 and let me know if it works?

Do not use them, it's only to test if this is a possible approach to make it work - this is likely to be insecure to use.

**Comment by pjanx** [comment]
After uninstalling the F-Droid version (otherwise I got "App not installed."), the first one of these still crashes (architecture mismatch?), but the second one seems to work.

**Comment by epoberezkin** [comment]
simplex.apk is for aarch64, and simplex-armv7a.apk is for armv7a - so yes, can be architecture mismatch.

You mean it does work on Android 8, right?

Ok, good to know if so, it's the right direction to fix it. Certainly don't use this APKs for anything important/

**Comment by pjanx** [comment]
As I mentioned previously, this is specifically Android 8.1 in LineageOS 15.1, 8.0 might have no problem.

**Comment by franzos** [comment]
I can also report `simplex-armv7a.apk` working on Android 8.1.
Awesome!!! :) I hope this finds it's way into the release soon.
Couple more years for this phone.

**Comment by franzos** [comment]
I'm now using the following Version from F-Droid without any issue on my Android 8.1 device:

```
App: v5.4
App build: 162
Core: v5.4.0.6
simplexmq: v5.4.0.6 (281bdeb)
```

Thank you very much for supporting this old device!
I suppose this issue can be closed?
