### ISSUE TITLE
[Feature]: Chat preference to disallow media (pictures/photos, videos, etc.)

### ISSUE THREAD

**Issue by Mikaela** [simplex-chat/simplex-chat#2693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

all

### App version

5.2

### Feature

I would like to see an option to disallow media in your/chat preferences just like message reactions, voice messages and audio/video calls.

This could be a safe default that could then be adjusted contact preferences or group preferences when the user is expecting to face harassment in forms such as dickpics. There have recently been cases where someone attempts to message everyone they can (whether it be through dropping their contact link, using published address or groups allowing direct messages between members).

I think this might also be beneficial for screen reader users, although that would need to be asked from them and I have no idea how accessible SimpleX is through one or whether SimpleX goes through accessibility testing.

**Comment by epoberezkin** [comment]
it's already added, will ship in v5.3 for backward compatibility.

**Comment by ElsAr4e** [comment]
Isn't this similar to https://github.com/simplex-chat/simplex-chat/issues/2482 ?

**Comment by epoberezkin** [comment]
the same indeed :)
