### ISSUE TITLE
I cannot download my own files on chat

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#2712]
Today I sent a file, and after I deleted it from my download directory.

Afterwards I would to download it again from my chat. Impossible. SimpleX show me "Revoke File" dialog instead of "Download".
I can download that file from other sources, but why this happen?

**Comment by epoberezkin** [comment]
The app doesn’t keep a copy of sent files, only of received files. It actually specifically removes the local app copy of the file once it’s sent. It only keeps images, voice and videos to be able to show/play them, but not of usual files.

**Comment by epoberezkin** [comment]
I am not convinced it's the right decision tbh, but seemed right at the time it was implemented :)

**Comment by epoberezkin** [comment]
It was mostly to avoid unnecessarily increasing app storage side - the assumption is that you have these files elsewhere… But probably it creates more confusion than value.
