### ISSUE TITLE
Feature: Ability to Hide or incognito mode the creator of the group chat

### ISSUE THREAD

**Issue by User1l0** [simplex-chat/simplex-chat#2770]

**Comment by ElonSatoshi** [comment]
Here's a workaround:

1. Create a group
2. Create an address for the group
3. Join your own group as incognito
4. Promote your incognito account to owner
5. As not-incognito, delete the group address (just in case a group address can still function after the one who created it leaves)
6. Leave the group with your non-incognito account

Previous message history should not be shared. To confirm, create a group address and join as incognito again. The only history you should see is your incognito owner account connected.
