### ISSUE TITLE
Feature: Delete all messages and the whole pm from the menu option for you and the user after you delete the pm chat

### ISSUE THREAD

**Issue by User1l0** [simplex-chat/simplex-chat#2824]

**Comment by epoberezkin** [comment]
There is “Clear” action to delete all meaaages, and if you delete the chat it also deletes all messages. How is the suggestion different?

**Comment by epoberezkin** [comment]
> even the pm from menu also for the other user you're messaging, not only for you

Currently you can only delete the messages that you send within 24 hours of sending them. We will consider adding the option to clear the whole conversation on your contact's device as well, but it would require their consent anyway, and will be opt in - it won't be possible to do it by default.

What's the use case when it is helpful btw? The scenario should be that the contact agrees to that deletion but cannot do it themselves, so it only applies to the cases when this contact lost the device but it's still online, right?

**Comment by epoberezkin** [comment]
But how would the spammer reach you unless you accept the connection? And even if you do, and they sent you messages, I believe you shouldn't be able to delete data from other people devices.

The argument on the subject is extended here: https://simplex.chat/blog/20221206-simplex-chat-v4.3-voice-messages.html#irreversible-message-deletion

Our position, in short, is very simple here: we may add functions allowing removal of the data from other people devices, but it will always require their consent before you can do it, or at least they should be able to opt-out (as is the case with disappearing messages). But destructive action of removing all messages in the conversation can only be as opt-in.

That it works differently in Telegram is not relevant to this discussion, their position is that neither party owns the conversation, they do, and they don't mind either party removing it for both, without any guarantee that they don't keep the copy (their terms allow that, at least for _a limited time_).
