### ISSUE TITLE
[Bug]: simplex-desktop-macos-aarch64: app is damaged and can't be opened

### ISSUE THREAD

**Issue by doomguy** [simplex-chat/simplex-chat#2849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Mac

### OS version

13.4.1 (c); Apple M1

### App version

v5.3.0-beta.2

### Current Behavior

App doesn't start. Error appears "simplex.app is damaged and can't be opened"

### Expected Behavior

App starts up normally.

### Steps To Reproduce

1. Download simplex:
1.1 5c9b9d8bba669b38bf922d7aeb7806bd74fac5ff8f9e49ace442c6a941ec11fece057b875ad4a2ea9637c2566402e8048e03faaaf96c2ba89c9b352d04daa0ba  simplex-desktop-macos-aarch64.dmg
2. Try to run it on apple Silicon

### Relevant log output

```shell
No logs available
```

**Comment by epoberezkin** [comment]
This is what Mac says when Gatekeeper puts the app to quarantine… See the instruction in the release notes how to run it.
