### ISSUE TITLE
bitcoin_ add on fdroid app?

### ISSUE THREAD

**Issue by ghost** [simplex-chat/simplex-chat#2894]
* is it ok to add bitcoin address given @ https://github.com/simplex-chat/simplex-chat#help-us-with-donations
* adding bitcoin add in [app fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/chat.simplex.app.yml) will create a link on fdroid client

**Comment by epoberezkin** [comment]
Thank you - probably helpful to add it indeed.
