### ISSUE TITLE
Networking features like briar

### ISSUE THREAD

**Issue by User1l0** [simplex-chat/simplex-chat#2935]
It could be awesome if this app could work like briar by using offline wifi and Bluetooth mesh networks, this could be a lifesaver if you don't have a global internet connection

**Comment by ElsAr4e** [comment]
It's been already requested: https://github.com/simplex-chat/simplex-chat/issues/1628

And I would like to add it would be great if there was an opt-in setting that for example only users without internet can reach you (using Wifi and/or bluetooth) -even if the internet is / or becomes available (again).
