### ISSUE TITLE
how to verify appimage?? theres no hash!

### ISSUE THREAD

**Issue by valtoree** [simplex-chat/simplex-chat#2947]
sorry if dumb question, but there isnt any new hash so I can't update/install. 

unless I've missed something.
great work by the way.

**Comment by valtoree** [comment]
ty 4 putting hashes in current beta v5.3.0-beta.8 👍 I can now download and use the appimage. keep up great work.

**Comment by epoberezkin** [comment]
it's now automated. There wasn't much sense in manually adding hashes to the builds done in CI (we'd have to download them first, so it kind of defeats the purpose).
