### ISSUE TITLE
Explain why asymmetric key (public) is passed off-band (and why not pass symmetric keys)

### ISSUE THREAD

**Issue by efim-poberezkin** [simplex-chat/simplex-chat#30]
Draft:

It's more secure against an eavesdropping attacker. The keys that the receiver generates for the sender can be intercepted off-band via any channel except camera - email,  video call, mutual trusted friend. Even if public key is intercepted off-band it only allows a passive attacker to encrypt a message, but not to decrypt it.

If an active attacker intercepts a public key and tries to act as a sender, the real sender won't be able to create a simplex channel (i.e. will be denied by the server) and he will then communicate this to the receiver off-band.

**Comment by epoberezkin** [comment]
@efim-poberezkin is it done?

**Comment by efim-poberezkin** [comment]
@epoberezkin yep.. I'm not sure the draft in description has to do smth with the explanation, but it's explained differently here:
https://github.com/simplex-chat/simplexmq/blob/master/rfcs/2021-01-26-crypto.md#why-handshake-has-to-be-with-asymmetric-keys
I've checked the logic, seems good to me, please double check

**Comment by efim-poberezkin** [comment]
oh well.. re-reading the desciption it actually seems to do explain the same thing.. still it's better when it's semi-formal and I believe explanation is more complete in rfc

**Comment by epoberezkin** [comment]
what should we do with it? A bit lost :)

**Comment by efim-poberezkin** [comment]
to do - copy explanation from https://github.com/simplex-chat/simplexmq/blob/master/rfcs/2021-01-26-crypto.md#why-handshake-has-to-be-with-asymmetric-keys to protocol

**Comment by juev** [comment]
These links is not working: 404 :-(

**Comment by efim-poberezkin** [comment]
@juev Hi, apologies - it seems we recently moved that doc to a different folder, here's the link:

https://github.com/simplex-chat/simplexmq/blob/master/rfcs/done/2021-01-26-crypto.md#why-handshake-has-to-be-with-asymmetric-keys

The explanation there is not the clearest really, it was more of a not very formal proof of a thought experiment for ourselves at that moment.

Also we plan to switch to different cryptographic primitives in near future - this explanation is going to be outdated soon. You may want to check out the draft of a new technical document, [available here](https://github.com/simplex-chat/simplexmq/blob/master/protocol/overview.md).

**Comment by juev** [comment]
Thank you!
