### ISSUE TITLE
Crypto donations (not easy after all)

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#3006]
The nature of an individual donation is often small and dictated by chance (what is available in a certain period).

However, I notice that I can’t donate conveniently because most of coins that would save me time and fees are not currently available in Github.

BTC is not Taproot (bc1q...).

TRX and XEC I can’t use them because you don’t have them.

**Comment by jooray** [comment]
Sending to legacy BTC address is not more expensive for you, only to spend it.

You can you Monero (XMR), low fees and privacy.
