### ISSUE TITLE
[Bug]: App's not opening/working

### ISSUE THREAD

**Issue by Zokii0** [simplex-chat/simplex-chat#3042]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Platform

Android

### OS version

Android 8.0 , LG V30 Stock rom

### App version

5.2.3

### Current Behavior

App installed from play store, it doesn't want to open, it's instantly crashing.

https://github.com/simplex-chat/simplex-chat/assets/144468403/a581feb3-1442-4b19-a405-42ba9322211b

Edit: I just found out about this previous issue someone had:

https://github.com/simplex-chat/simplex-chat/issues/2689

I also found same log output text in "Send feedback" button, which means that I have exact same issue. Is there any way to insert that "getentropy" in system if my phone is rooted?

### Expected Behavior

App to open

### Steps To Reproduce

See my video file above, not sure how to get log file.

**Comment by securegh** [comment]
I had the same issue here is the solution:
There are two versions of SimpleX on the F-droid app, choose the second one. 
![F-Droid](https://github.com/simplex-chat/simplex-chat/assets/113610808/e2506862-e3f7-4338-95a7-058e3177975b)

**Comment by securegh** [comment]
It you don't want to use F-droid, download and install the arm7a version 
https://github.com/simplex-chat/simplex-chat/releases/download/v5.2.3/simplex-armv7a.apk

**Comment by Zokii0** [comment]
> It you don't want to use F-droid, download and install the arm7a version https://github.com/simplex-chat/simplex-chat/releases/download/v5.2.3/simplex-armv7a.apk

This actually worked, didn't even think to check F-droid, tysm!
