### ISSUE TITLE
[P] [D] SimpleX doesn't ask me permission to access my media files but it can read them

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#3066]
Android 13 splits the "files" permission in "photo" and "audio" files or "access to all files" if you allow "all".

SimpleX access to my gallery without ask me nothing by circumvent permissions pattern.

This is not the right way: control and good behaviors is the way.

Please add both permissions in next version.

Power is nothing without control.

**Comment by pm4rcin** [comment]
Looks like it was implemented. Issue could be closed.
