### ISSUE TITLE
Comparison with Session App

### ISSUE THREAD

**Issue by 0xspade** [simplex-chat/simplex-chat#309]
Can you provide us the comparison between this and session app?

**Comment by epoberezkin** [comment]
session treats user’s public key as a long term user identity and it is passed out of band for key exchange and used as a non-optional user’s long term address. So while it minimises metadata collection, an attacker can still reconstruct some parts of users connection graph using these keys, via service nodes (?) or other client devices. For example if Alice communicated with Bob and with Mallory by obtaining the devices of both bob and Mallory you “probably” can prove that this is the same person.

SimpleX protocol doesn’t have identity keys or any other form of global user identity.

While we do have optional long term “addresses” they can be changed by the user without losing the established connection, and these addresses are not used for communication. 

Also, we do not want SimpleX depend on any cryptocurrency as session does.

it’s worth reading their whiteparer and also this doc about SimpleX: https://github.com/simplex-chat/simplexmq/blob/master/protocol/overview-tjr.md

**Comment by Bugaddr** [comment]
> session treats user’s public key as a long term user identity and it is passed out of band for key exchange and used as a non-optional user’s long term address. So while it minimises metadata collection, an attacker can still reconstruct some parts of users connection graph using these keys, by observing key exchange, as they point out, via service nodes (?) or other client devices. For example if Alice communicated with Bob and with Mallory by obtaining the devices of both bob and Mallory you “probably” can prove that this is the same person.
> 
> SimpleX protocol doesn’t have identity keys or any other form of global user identity.
> 
> While we do have optional long term “addresses” they can be changed by the user without losing the established connection, and these addresses are not used for communication, only to establish the initial connestion
> 
> Also, we do not want SimpleX depend on any cryptocurrency as session does.
> 
> it’s worth reading their whiteparer and also this doc about SimpleX: [https://github.com/simplex-chat/simplexmq/blob/master/protocol/overview-tjr.md](https://github.com/simplex-chat/simplexmq/blob/master/protocol/overview-tjr.md?rgh-link-date=2022-02-20T08%3A06%3A03Z)

Hey, would like to read you'r thoughts on comparision with briar https://play.google.com/store/apps/details?id=org.briarproject.briar.android

**Comment by epoberezkin** [comment]
Briar is p2p, so it has the problems of that design - I've summarised it here: https://github.com/simplex-chat/simplex-chat/blob/stable/docs/SIMPLEX.md#comparison-with-p2p-messaging-protocols

Also, using persistent user identifier has the same problems as with other apps/platforms.

**Comment by bambirombi** [comment]
It would be interesting to have a comparison table in the homepage.

I would also add to the comparison: [berty](https://github.com/berty/berty) and [coyim](https://github.com/coyim/coyim)

**Comment by shumvgolove** [comment]
Discussion is continued in https://github.com/simplex-chat/simplex-chat/issues/1298
