### ISSUE TITLE
[Feature]: Encrypted videos

### ISSUE THREAD

**Issue by User1l0** [simplex-chat/simplex-chat#3091]
Hope this comes soon

**Comment by ElonSatoshi** [comment]
Just to be clear: Videos are E2E encrypted in transit to another contact. The issue is that SimpleX Chat stores your chat history, accounts, etc. in a locally encrypted database, and the videos, as files, are stored on your device unencrypted.

Do I understand this correctly?

**Comment by massimopavoni** [comment]
> Just to be clear: Videos are E2E encrypted in transit to another contact. The issue is that SimpleX Chat stores your chat history, accounts, etc. in a locally encrypted database, and the videos, as files, are stored on your device unencrypted.
> 
> Do I understand this correctly?

That is indeed what is specified in [v5.3](https://github.com/simplex-chat/simplex-chat/releases/tag/v5.3.0).

I too am interested in having videos encrypted locally, as photos are.

**Comment by epoberezkin** [comment]
yes, this is coming. However complex, it has to be done, even if for the sake of perception, as the need for this disclaimer ("videos not encrypted locally") makes a lot of people think that videos are sent unencrypted, which is not the case of course - everything is sent end-to-end encrypted...
