### ISSUE TITLE
[Bug]: Desktop: missing library: /tmp/simplex/libs/libapp-lib.so

### ISSUE THREAD

**Issue by dvn0** [simplex-chat/simplex-chat#3110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### OS version

Ubuntu 22.04

### App version

v5.3.0

### Current Behavior

Starting with `v5.3.0-beta.9` I get a new error when attempting run simplex desktop after installing the DEB package.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /tmp/simplex/libs/libapp-lib.so
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at chat.simplex.desktop.MainKt.initHaskell(Main.kt:24)
        at chat.simplex.desktop.MainKt.main(Main.kt:12)
        at chat.simplex.desktop.MainKt.main(Main.kt)
```
This bug shows up for me whether I build the deb package myself, or use the official release (from github).

There is a dpkg error when installing that started showing up on beta.8, iirc, but I don't think it's related: `xdg-desktop-menu: No writable system menu directory found.`

### Expected Behavior

simplex desktop should start without fatal errors.

### Steps To Reproduce

1. Download and install https://github.com/simplex-chat/simplex-chat/releases/download/v5.3.0/simplex-desktop-ubuntu-22_04-x86_64.deb

2. Execute `/opt/simplex/bin/simplex`

**Comment by dvn0** [comment]
FYI:

```
$> find /opt/simplex/lib -name "*libapp*" -type f
/opt/simplex/lib/libapplauncher.so
$> find /tmp -name "*libapp*" -type f 
(no results)
```

**Comment by epoberezkin** [comment]
did it start from beta.9 or you didn't try earlier?

**Comment by epoberezkin** [comment]
confirmed, please use app image for now, removed 20_04 and 22_04 from the release

**Comment by epoberezkin** [comment]
(appimage works)

**Comment by dvn0** [comment]
Definitely only started with beta.9. Everything up through beta.8 worked. I was trying to track down the change culprit, but I'm not sure yet.

**Comment by dvn0** [comment]
I've been building the deb locally since beta.1, and upgrading via apt with each beta release.

**Comment by dvn0** [comment]
This appears to be fixed in master now. Just built c1854b7d507708942397869d09b8828096e9d0d4 and it's running fine.
