### ISSUE TITLE
[Discussion] We already have the best privacy options in SimpleX

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#3199]
Signal Introduces Message Editing

"The pro-privacy messaging app, Signal, has taken a significant stride, granting its users the leeway to amend or append texts up to a full day after being sent. This change, accessible via a simple long press on the message followed by selecting “Edit,” is seen as a game-changer in the realm of private digital dialog."

https://reclaimthenet.org/signal-introduces-message-editing

**Comment by Lord-KA** [comment]
I am not sure how that is something new, more so gamechanging. The current SimpleX message editing seems very close by function and more transparent, as the receiving client may store change history anyway, you can't be sure that the original message can't be accessed. If you want more privacy, use self-destructing chats.

**Comment by epoberezkin** [comment]
As long as message history remains visible editing seems not violating the contract or any natural laws - the message is marked as edited.

not sure what’s so game changing here and why it didn’t have it before…
