### ISSUE TITLE
[Feature]: Allow to paste files on Windows desktop version

### ISSUE THREAD

**Issue by tracewave** [simplex-chat/simplex-chat#3232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Windows

### App version

5.4.0-beta.0, 5.4.0-beta.2

### Feature

We should be able to paste images or other files from the clipboard and detect the proper file type. So it should treat the file as a video if it is a video and allow to play it, or an image and allow to view it in the chat.

**Comment by tracewave** [comment]
Still happening on `5.4.0-beta.2` after the `desktop: paste files/images to attach to message (https://github.com/simplex-chat/simplex-chat/pull/3165)` commit.

**Comment by jessehorne** [comment]
With the following PR, once it's merged, you'll be able to copy images to the clipboard and paste thing into messages which will put them as an attachment.

#3378
