### ISSUE TITLE
[Feature]: make desktop app usable without GPU acceleration

### ISSUE THREAD

**Issue by Lord-KA** [simplex-chat/simplex-chat#3236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### App version

5.3.1

### Feature

Now when using simplex-desktop on a device without any GPU acceleration, the CPU load is extreme even on a static screen. My daily-driver is QubesOS, it runs apps in different virtual machines, thus GPU connection isn't really possible (at least for most of them). I understand that this may be a framework limitation and you don't have the resources to support a standalone desktop application like Telegram does. But there still may be a chance that this is a configuration problem and it is fixable.
![2023-10-16_18-21](https://github.com/simplex-chat/simplex-chat/assets/43700614/08b81ac5-ae0c-4586-bbc7-e6dc021a4469)
(And this is i7 12th gen)

**Comment by epoberezkin** [comment]
thank you!

**Comment by Lord-KA** [comment]
> @Narasimha-sc, @Lord-KA have you tried the latest version - https://github.com/simplex-chat/simplex-chat/releases/tag/v5.6.1? The cursor problem should be fixed there (we updated Compose version to 1.6.1 which includes the fix).

Wow, this really made a huge difference. Now on a static screen the CPU usage is ok, while scrolling is still pretty bad.

**Comment by avently** [comment]
Good to know it helped, thank you all for checking. 

Scrolling is the most problematic part as it involves a lot of components and requires everything to be too fast to be drawn in real time. We make it better from time to time, but it does not always have a place for a huge optimization.

**Comment by epoberezkin** [comment]
Let's call it "done" for now - making modern software usable without at least some GPU isn't trivial...
