### ISSUE TITLE
[Bug]: Cannot create a custom disappearing messages duration

### ISSUE THREAD

**Issue by JacksonChen666** [simplex-chat/simplex-chat#3329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Mac

### OS version

14.1

### App version

5.3.1

### Current Behavior

You can choose a custom disappearing message duration, but you can't actually select the things with your mouse, nor does scrolling (very hard to discover) actually change anything.

https://github.com/simplex-chat/simplex-chat/assets/50755746/b0d256fc-0edb-45a6-a2ab-24cfcbfaff3f

### Expected Behavior

The custom time is customizable on desktop with a mouse (how about on Android with a mouse?) and scrolling (make that discoverable first, it took me a long while to figure that out)

### Steps To Reproduce

1. Open a chat
2. Open preferences for chat/group
3. Enable disappearing messages if not already done
4. Set "Delete after" to be "Custom"
5. Try to click some other choice like 2 hours or 3 days
6. Also try scrolling

**Comment by jessehorne** [comment]
This is happening to me as well on Ubuntu 22.04 from `master`. Working on a solution atm. Will keep this thread updated.
