### ISSUE TITLE
[Q]: Details about preset servers

### ISSUE THREAD

**Issue by umarmnaq** [simplex-chat/simplex-chat#3348]
### Question

When I install the app, I would like the default server to be a custom server. But searching through the code, I found no references to the 5-10 default servers. Where are they?

Also have a question about the xftp servers. Is the stored data encrypted? Also how does SimpleX handle calls. Do they go through the SMP server or the XFTP server?

**Comment by epoberezkin** [comment]
> I found no references to the 5-10 default servers. Where are they?

Depends on the platform, but for GUI apps they are in Chat.hs file

> xftp servers. Is the stored data encrypted?

yes, of course

> Also how does SimpleX handle calls. Do they go through the SMP server or the XFTP server?

Calls use WebRTC, with the signalling and key agreement for e2e encryption via SMP.

**Comment by umarmnaq** [comment]
> > I found no references to the 5-10 default servers. Where are they?
> 
> Depends on the platform, but for GUI apps they are in Chat.hs file

I was talking about the android apps. I suppose that they are located in the binaries?
