### ISSUE TITLE
5.4-beta.3 crashing at launch

### ISSUE THREAD

**Issue by nahuhh** [simplex-chat/simplex-chat#3357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

Android 10

### App version

5.4.0-beta.3

### Current Behavior

App refuses to launch. Crashes immediately,
Previous beta worked.

### Expected Behavior

App should open.

### Steps To Reproduce

1. Open app

**Comment by PLAYERUNKNOWNHatsune01** [comment]
Still no fix on this one? I can' t use SimpleX Chat

**Comment by nahuhh** [comment]
Fixed in beta-4
