### ISSUE TITLE
[Bug]: White text with white background

### ISSUE THREAD

**Issue by kremzli** [simplex-chat/simplex-chat#3363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

Android 13

### App version

5.3.2

### Current Behavior

White backgrounds display some text in white
![image](https://github.com/simplex-chat/simplex-chat/assets/87526638/dc05dd55-a397-44d1-b6b4-f15bc1fee62c)

### Expected Behavior

White backgrounds to make all text dark

### Steps To Reproduce

1. Make a theme with a white background
2. See white text

**Comment by avently** [comment]
If you want to set white background, use the light theme and change colors in it. Don't use dark themes for that purpose expecting they will work in such scenarios

**Comment by kremzli** [comment]
Sorry for being gone.

Ive been trying to see what would fix this but it doesnt seem to fully fix the issue of having some white text

Heres the theme i tried using https://github.com/iruzo/simplex/blob/main/catppuccin-latte.theme

I tried every "base" but doesnt fix it, i also removed that extra ":" at accentVariant but it didnt do anything

Heres some screenshots:

SIMPLEX base (the same as DARK but it has this shade):

![signal-2023-12-31-233455_005](https://github.com/simplex-chat/simplex-chat/assets/87526638/79a626c0-c728-413c-9549-fcf570720d2c)
![signal-2023-12-31-233455_003](https://github.com/simplex-chat/simplex-chat/assets/87526638/1e19c95f-401a-47e0-bbb7-236cbc6bc3b9)

LIGHT base:

![signal-2023-12-31-233455_004](https://github.com/simplex-chat/simplex-chat/assets/87526638/9f6955fb-7cbc-48ca-aa7f-52e58abe586f)
![signal-2023-12-31-233455_002](https://github.com/simplex-chat/simplex-chat/assets/87526638/b2ee52d1-c162-4d39-8d53-dfc923986c60)

**Comment by avently** [comment]
Ok, thank you for the theme, I'll look into it

**Comment by avently** [comment]
[kremzli](https://github.com/kremzli), as I told you a couple of times, dark themes are for dark colors. Blue dark theme can't have light background. I tried to make it possible but it gives a lot of problems in code, complicates it, and requires to review every screen and every view of the app, so it's just doesn't worth it. My only advice for you is to use light theme for modifications you want. The only downside of this is the fact that you'll lose gradient of blue theme. Otherwise, it's the same. 

And also keep in mind that background of splashscreen you see when the app launches depends on light/dark theme flag, not on background of the theme.  So if you use light theme and trying to make it dark, you'll still see light splashscreen anyway. That's why it's better to use correct theme for modification.

**Comment by kremzli** [comment]
I did try the light theme base with my own modifications of that catppuccin theme though, screenshots are above

**Comment by avently** [comment]
That's weird, but if you replace this color:
```yaml
  menus: "#ff8839ef"            # mauve
```
with this:
```yaml
  menus: "#ff8839ee"            # mauve
````

Everything will look fine. As a temporary solution.

I made a PR that fixes it completely: #3635

**Comment by avently** [comment]
[kremzli](https://github.com/kremzli), previous PR was not ideal, this one should be better: https://github.com/simplex-chat/simplex-chat/pull/3649. 
You'll be able to see it in action in the next build. Let me know if you'll still see any inconsistencies.

**Comment by kremzli** [comment]
It fixed the text issues but chat bubbles now look like this (and that hold menu is not great but i dont think thats a bug, maybe cant really change it)


![signal-2024-01-13-191102_002](https://github.com/simplex-chat/simplex-chat/assets/87526638/67f732a9-ada1-499a-afd6-3ebeacbffe84)
![signal-2024-01-13-191055_002](https://github.com/simplex-chat/simplex-chat/assets/87526638/5ea9c741-fd10-4fde-84c2-13a521ad8f58)


Should i rename this issue since now its other light theme issues too

**Comment by avently** [comment]
1. Menu color you can change in Menus & alerts option in theme
2. Chat bubbles in Sent message and Received message. If you want to change the text color in bubbles, you can't.

Try to change these colors and everything should be fine

**Comment by kremzli** [comment]
I will notify the theme maker to update it. Thanks
