### ISSUE TITLE
[Bug]: iOS crash bug at Displaying GroupMemberInfoView

### ISSUE THREAD

**Issue by koba-ninkigumi** [simplex-chat/simplex-chat#3487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

iOS

### OS version

iOS 15

### App version

ios: 5.4.1 build 185

### Current Behavior

The application freezes and nothing can be operated.

### Expected Behavior

The application does not freeze.

### Steps To Reproduce

1. Install a new simplex app
2. create a new group
3. invite existing contacts.
4. select invite member at group setting view
5. Call memberInfoView(member) from NavigationLink at line 107 of 
    /simplex-chat/apps/ios/Shared/Views/Chat/Group/GroupChatInfoView.swift
6. Displaying GroupMemberInfoView in 
    /simplex-chat/apps/ios/Shared/Views/Chat/Group/GroupMemberInfoView.swift
It will freeze the simplex app.

**Comment by epoberezkin** [comment]
I can reproduce in iOS 15. Did it happen before or started in v5.4?

**Comment by epoberezkin** [comment]
looks like it started from build 181...

**Comment by epoberezkin** [comment]
https://github.com/simplex-chat/simplex-chat/compare/0bd59364fd3431eba6913263e1222ee8b8b15206...11362941fdb9ab6f088287fa8e574475f12d7546

**Comment by koba-ninkigumi** [comment]
👍
