### ISSUE TITLE
[Bug]: iOS crash bug at push confirm button for Connect to desktop 

### ISSUE THREAD

**Issue by koba-ninkigumi** [simplex-chat/simplex-chat#3488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

iOS

### OS version

iOS 15

### App version

ios: 5.4.1 build 185

### Current Behavior

To connect to desktop app on Mac, press the "Confirm" button on the "Verify connection" screen of iOS

Calling verifyDesktopSessionCode at line 263 of 
/simplex-chat/apps/ios/Shared/Views/RemoteAccess/ConnectDesktopView.swift
causes the simplex app to crash.

### Expected Behavior

The app does not crash.

### Steps To Reproduce

1. push "Use from desktop" button at "Your settings" view
2. Scan QR code at "Connect to desktop" view
3. push "Confirm" button at "Verify connection" view

It will crash the simplex app.

**Comment by epoberezkin** [comment]
It does happen right after scanning if I prevent access to local network, not on confirm step.

In newer OSs it asks for permission (unless it was disabled) but in any case it does not crash...

There is no easy way to check if permission is granted without trying to access the network.

In any case, can you check in System settings if the app is allowed to access local network?

**Comment by koba-ninkigumi** [comment]
You are misreading where the problem is occurring.
The QR code reads successfully.
When I press the "Confirm" button it crashes.

https://github.com/simplex-chat/simplex-chat/blob/stable/blog/20231125-simplex-chat-v5-4-link-mobile-desktop-quantum-resistant-better-groups.md

<img src="https://github.com/simplex-chat/simplex-chat/assets/1291966/d1d67717-bd34-4336-9d4d-b6d40b224b17" width="300px">

<img width="390" alt="mac" src="https://github.com/simplex-chat/simplex-chat/assets/1291966/64957a5f-2278-4141-800c-3b1902c43383">

**Comment by epoberezkin** [comment]
I understand, but I can't reproduce it on iOS 15...

Can you please check app settings to see if local network access is allowed for the app?

When it crashes and you send crash report - can you please add some distinct note there and share here?

**Comment by epoberezkin** [comment]
although, logically, if you got as far as verifying session code, then you must have local network access - it already connected... Please re-submit the crash with some note, to be certain which one is that, it's not clear from what I see...

**Comment by koba-ninkigumi** [comment]
I just sent it to you.
I sent it from my iPhone with "https://github.com/simplex-chat/simplex-chat/issues/3488" in the memo field.
I also sent a crash log to the SimpleX Chat Ceam chat.

**Comment by epoberezkin** [comment]
Yes, I can see it - thank you.

It appears like it might be specific to iPhone 7 and SE gen 1 that have a different CPU, investigating...

**Comment by koba-ninkigumi** [comment]
This problem has been fixed in v5.4.2. 
Thanks!
