### ISSUE TITLE
[Feature]: need HiDPI supprt request for Desktop

### ISSUE THREAD

**Issue by Extr3m4R4710** [simplex-chat/simplex-chat#3501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### App version

5.4(18) 

### Feature

I am using GUI simplex in xfce4 environment with 4k display. For a simple java application it is an easy problem. But this application is provided as appimage and is difficult to use in HiDPI.

I tried to use `GTK_SCALE=2.0` as a desperate measure, but it does not work at all.

We are looking for a way to handle this as a request or to solve the HiDPI problem with appimage.

**Comment by user3534** [comment]
hacky workaround
nothing else seems to work

sudo pacman -S xpra
run_scaled --scale=1.2 ./simplex-desktop-x86_64.AppImage
