### ISSUE TITLE
[Bug]: Unable to log in after restarting Windows.

### ISSUE THREAD

**Issue by nik2323** [simplex-chat/simplex-chat#3511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Windows

### OS version

Windows 10 PRO

### App version

5.4.0

### Current Behavior

After turning on the computer and enabling the Simplex application, a window pops up with the text "Incorrect database password." No passwords are suitable. Reinstalling the application does not help. Clearing leftovers in the registry only helps to register in the application again.
[Документ Microsoft Word.docx](https://github.com/simplex-chat/simplex-chat/files/13541683/Microsoft.Word.docx)

### Expected Behavior

The application should launch normally like any other application, but it doesn't.

### Steps To Reproduce

1. Turn on the computer. 2. I turn on the SimpleX 5.4.0 application. 3. I see a pop-up window. 4. Enter the password. 5. I see information that the password is not suitable.

**Comment by epoberezkin** [comment]
we have seen this happening when username in Windows was not latin - is it maybe the case here?

**Comment by epoberezkin** [comment]
can you try it in v5.4.2 please - it might be fixed there.
