### ISSUE TITLE
[Bug]: cabal error compiling SimpleX on rPi - Invalid name in tar archive

### ISSUE THREAD

**Issue by cthulhubuddha** [simplex-chat/simplex-chat#3521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### OS version

Debian GNU/Linux 11 Linux host 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

### App version

5.4.0.6

### Current Behavior

Raspberry Pi, compiling from source.

GHCup 0.1.20.0
Stack 2.13.1
Cabal 3.10.2.0
GHC 9.6.3

```
cabal install simplex-chat:exe:simplex-chat
...
Starting     simplexmq-5.4.0.6 (lib)
Building     simplexmq-5.4.0.6 (lib)
Installing   simplexmq-5.4.0.6 (lib)
Completed    simplexmq-5.4.0.6 (lib)
Error: cabal: Failed to unpack simplex-chat-5.4.0.6 (which is required by
exe:simplex-directory-service from simplex-chat-5.4.0.6, exe:simplex-chat from
simplex-chat-5.4.0.6 and others). The exception was:
Invalid file name in tar archive:
"simplex-chat-5.4.0.6/apps/simplex-broadcast-bot/src/../"
```

### Expected Behavior

Valid file name in tar archive

### Steps To Reproduce

sudo apt install build-essential curl libffi-dev libffi7 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
ghcup install ghc 9.6.3
ghcup install cabal 3.10.2.0

git clone https://github.com/simplex-chat/simplex-chat
cd simplex-chat
git checkout stable
apt-get update && apt-get install -y build-essential libgmp3-dev zlib1g-dev
cp scripts/cabal.project.local.linux cabal.project.local
cabal update
cabal install simplex-chat:exe:simplex-chat

**Comment by andorsk** [comment]
I think https://github.com/simplex-chat/simplex-chat/pull/3559 might be fixing this.

**Comment by cthulhubuddha** [comment]
@andorsk thank you for that note above. i cloned the latest version and simplex-chat.cabal still had those ../ references so I removed them. now onto the next compile error which is Error: cabal: Main.hs doesn't exist. I'll open a new issue.

**Comment by cthulhubuddha** [comment]
closing, workaround is https://github.com/simplex-chat/simplex-chat/pull/3559
