### ISSUE TITLE
Pannic button!

### ISSUE THREAD

**Issue by g1zza** [simplex-chat/simplex-chat#3522]
### Question

I think will be nice to have in log in screen ,if enter the pin 5 time  triggered to wipe the app with out warning,the warning shud when you setup the account for the fist time.

2 ) i think calling shud have despairing time like message ,sow you dont leave any traces.

**Comment by nahuhh** [comment]
It exists. 

settings > security > SimpleX Lock

issue cam be closed @epoberezkin

**Comment by epoberezkin** [comment]
yes, there is self-destruct
