### ISSUE TITLE
[Q]: How can I get the database password for a new iPhone?

### ISSUE THREAD

**Issue by chmac** [simplex-chat/simplex-chat#3564]
### Question

I've just a new iPhone. SimpleX wants a database password on the new phone to unlock. But my old phone says the password is stored in keychain. Is there a process to transfer to a new device? Did I miss this in the docs somewhere?

(I tried to post this as a discussion but I got a permission error. It seems I can’t post discussions so I’m posting an issue instead.)

**Comment by koba-ninkigumi** [comment]
At Your Old iPhone
1. Display the "Your chat database" screen. 
2. Click on "Chat is running" and turn it Off.
3. Select "Database passphrase". 
4. Enter a new passphrase in the "New passphrase" field. 
5. Enter the new passphrase in the "Comfirm new passphrase" field. 
6. Press "Update database passphrase". 
7. Press "Export database".

**Comment by chmac** [comment]
@koba-ninkigumi That's great, thanks. How do I import the database on the new phone? It just says "Please enter passphrase to unlock database"...

**Comment by koba-ninkigumi** [comment]
At Your New iPhone
1. Install the Simplex chat app
2. Open the application.
3. Press the Next button.
4. Press "Create your profile".
5. Choose a name for your profile.
6. Press "Create SimpleX address".
7. Select the Push notifications setting.
8. Select the icon in the upper left corner to display the "Your settings" screen.
9. Select "Database passphrase & export".
10. Press "Chat is running" to turn it off.
11. Select "Import database".
12. Select the database exported from Old iPhone.
13. Press "Chat is stopped".
14. Enter the passphrase you set in Old iPhone.

**Comment by chmac** [comment]
I’m in the situation that I “transferred” to a new iPhone. That means that the SimpleX app was automatically installed, and its data was migrated over. But without the key, I can’t access it on the new phone.

I guess I need to uninstall the app, then reinstall it, and then I can follow the steps above. Thanks.

Should I open a new issue to track handling this case better? My iPhone prompted me to wipe my old iPhone. After migration. If I had done that, I would no longer be able to access my data at all.

**Comment by chmac** [comment]
Okay, I created a new issue with a feature request, I'll close this one now. Thanks a lot for the quick feedback.
