### ISSUE TITLE
[Bug]: cabal install returns Error: cabal: Main.hs doesn't exist

### ISSUE THREAD

**Issue by cthulhubuddha** [simplex-chat/simplex-chat#3569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### OS version

Debian GNU/Linux 11 Linux host 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux

### App version

5.4.0.7

### Current Behavior

after running the below steps to reproduce, cabal install returns:

Error: cabal: Main.hs doesn't exist

### Expected Behavior

Cabal should be creating this file I believe

### Steps To Reproduce

sudo apt install build-essential curl libffi-dev libffi7 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org/ | sh
ghcup install ghc 9.6.3
ghcup install cabal 3.10.2.0

git clone https://github.com/simplex-chat/simplex-chat
cd simplex-chat
git checkout stable
apt-get update && apt-get install -y build-essential libgmp3-dev zlib1g-dev
cp scripts/cabal.project.local.linux cabal.project.local
cabal update
<replace ../Main.hs with Main.hs in simplex-chat.cabal, see https://github.com/simplex-chat/simplex-chat/pull/3559>
cabal install simplex-chat:exe:simplex-chat

**Comment by cthulhubuddha** [comment]
Closing, workaround is https://github.com/simplex-chat/simplex-chat/pull/3559

**Comment by cthulhubuddha** [comment]
^^ IGNORE above, I accidentally closed the wrong issue

**Comment by epoberezkin** [comment]
you need to use cabal build for now, there is PR that attempts to fix it.
