### ISSUE TITLE
[Bug]: Manual download of releases/download/v5.4.1/simplex-chat-ubuntu-22_04-x86-64 is still 5.4.0.7

### ISSUE THREAD

**Issue by cthulhubuddha** [simplex-chat/simplex-chat#3587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### OS version

Ubuntu

### App version

4.5.0.7, not 4.5.1

### Current Behavior

manually downloaded latest 4.5.1, --version says 4.5.0.7

### Expected Behavior

should have downloaded 4.5.1

### Steps To Reproduce

wget https://github.com/simplex-chat/simplex-chat/releases/download/v5.4.1/simplex-chat-ubuntu-22_04-x86-64
chmod 755 simplex-chat-ubuntu-22_04-x86-64
./simplex-chat-ubuntu-22_04-x86-64 --version
<returns 4.5.0.7>

**Comment by epoberezkin** [comment]
yes, that's how it was numbered.
