### ISSUE TITLE
[Q]: importing database in CLI

### ISSUE THREAD

**Issue by r4v3r23** [simplex-chat/simplex-chat#3590]
### Question

is it possible to transfer an account from mobile/desktop to CLI version using the encrypted database?

id like to have one instance of an account running on CLI server so connections can always be made

**Comment by epoberezkin** [comment]
yes, you can, by simply unpacking zip file and using options -d and --files-folder to point CLI to the right files

There are commands to import too, but they are usually not necessary.

You can then use `/db export` to create archive from CLI, it has to be started with -m option for that.
