### ISSUE TITLE
[Q]: Why simplex-chat isn't registered on Hackage?

### ISSUE THREAD

**Issue by yurivict** [simplex-chat/simplex-chat#3601]
### Question

?

**Comment by dpwiz** [comment]
What would that solve? :thinking:

**Comment by epoberezkin** [comment]
just never was asked for, we need to catch up with publishing simplexmq

**Comment by daviduhden** [comment]
@epoberezkin

> just never was asked for, we need to catch up with publishing simplexmq

I am trying to create a simplex-chat-cli port for OpenBSD, but it is impossible because the [cabal module](https://man.openbsd.org/cabal-module.5) used for haskell ports makes use of hackage.
