### ISSUE TITLE
What3Words (W3W) integration (when one shares a gps position)

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#3633]
Imagine being able to divide the surface of the entire planet into perfectly 3x3 (meters) square tiles, and give each of them a specific name, consisting of only three words.

Now, these words define a geographic location accurate enough to identify a man.

What advantage?

Three simple words are a unique address in the world.

Easy to remember and to pronounce (if you suggest it to a voice command).

https://what3words.com/

**Comment by Mikaela** [comment]
AFAIK everything with W3W is proprietary and if something like it was to be intrgrated, I would suggest Open Location Codes longer format also known as plus codes.

- https://github.com/google/open-location-code
- https://wiki.openstreetmap.org/wiki/Proposal_Open_Location_Code
