### ISSUE TITLE
Please remove the "delete" contact action from chat menu because is mistaken with "Clear" conversation action

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#3801]
A user can easily deleting a contact entering in the contact tab. Safely.

Too much times I mistakenly deleted a contact instead of clearing the conversation.

That is not the right place to put that action.

**Comment by epoberezkin** [comment]
You may like that a separate contact tab is in development, and while we didn't settle on the exact UX to delete, it will be possible to delete chat without deleting the contact.
