### ISSUE TITLE
[Bug]: iOS typing duplicates groups of letters, appending ahead of cursor

### ISSUE THREAD

**Issue by dolly8104** [simplex-chat/simplex-chat#3812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

iOS

### OS version

17.3.1

### App version

5.5.3 (198)

### Current Behavior

With or without auto complete toggled on, when typing a message to another user, the previously typed 1-4 letters will suddenly appear in duplicate, appended after the cursor. For example, if I try to type "work", I will get "worwork".

### Expected Behavior

Typing should not randomly create duplicate groups of letters.

### Steps To Reproduce

1. Open a message
2. Begin typing
3. Text duplication begins to happen almost immediately

**Comment by kimg45** [comment]
This seems to be fixed now? Anyone else able to confirm?
