### ISSUE TITLE
[Bug]: Jittery scrolling in iOS app

### ISSUE THREAD

**Issue by kimg45** [simplex-chat/simplex-chat#3827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

iOS

### OS version

iOS 17.5.1

### App version

5.8.2

### Current Behavior

Scrolling in all chats is jittery and not smooth. Scrolling in the settings screen is smooth however.

### Expected Behavior

Chats should scroll smoothly.

### Steps To Reproduce

1. Go to any chat
2. Scroll

**Comment by 77corn** [comment]
I have the same issue, even on the newest v5.7.3. This issue seems only IOS related, I tried SimplexChat on an $200 Samsung an it scrolled smoothly.

**Comment by kimg45** [comment]
Fixed now
