### ISSUE TITLE
[Bug]: Memory leak on 5.5 and lineageos 20

### ISSUE THREAD

**Issue by ClockGen** [simplex-chat/simplex-chat#3865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

Android 13 (LineageOS 20)

### App version

5.5.5

### Current Behavior

Sometimes (although rarely), the app starts to slow down and be unresponsive. During that time I can see my other apps (with persistent notifications) are killed, after that SimpleX randomly crashes (or gets killed by OOM manager). When checking task manager in dev options, it says that the app consumed 12 gb of RAM (total ram of my phone).  

I installed latest version (5.5.5) from github releases.   

My only system modification that's somehow related to this is Mulch webview (installed via a magisk module) from DivestOS project (which uses some other malloc implementation) but I don't know if it can even be responsible or used by SimpleX.

### Expected Behavior

Not consume 12 GB of ram.

### Steps To Reproduce

I couldn't figure out exact steps to reproduce it, it seems to happen randomly while chatting.

**Comment by ClockGen** [comment]
UPD: it also happens on 32 bit version (which has a different allocator according to https://github.com/simplex-chat/simplex-chat/issues/2790#issuecomment-1656037230). I also disabled all system modifications and ran on stock LOS 20, still happens on arm64 version too.

**Comment by icorneli** [comment]
![Uploading 2024-03-06_224342.png…]()

**Comment by icorneli** [comment]
The problem has not been resolved!
Personally, after some time, simplex begins to consume all the RAM, as well as the swap file, a total of 55 GB!
