### ISSUE TITLE
Tweak invite button text on iOS

### ISSUE THREAD

**Issue by robchandhok** [simplex-chat/simplex-chat#397]
Current link when the invite web page shows on iOS browser is `Open in mobile app`.  some users find this confusing.

Suggest new text `Join Chat in Simplex` or `Accept Invitation in Simplex`

Suggest new text above to replace `Scan QR code.....the app.` with `To accept the invitation on this device, click on the Accept Invitation button below (please be sure you've installed and opened Simplex at least once).  Otherwise, you can scan the barcode from the Simplex app.`

The most likely path is invite from one iphone to another, so the QR code should be secondary.

**Comment by z8512** [comment]
Its confusing. qr code should be secondary

**Comment by epoberezkin** [comment]
removed qr code from mobile page, updated copy.
