### ISSUE TITLE
App resolution is too high and does not follow system settings

### ISSUE THREAD

**Issue by sang-shelton** [simplex-chat/simplex-chat#3986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux

### OS version

MX Linux 23.2 - Based on Debian GNU/Linux 12 (bookworm)

### App version

5.6

### Current Behavior

I am using [MX Linux](https://mxlinux.org/) with XFCE as a desktop environment.

The system resolution is 2560 x 1600 and the scale is 1x.

<details><summary>Image</summary>
<p>

![Screenshot_2024-04-03_07-28-19](https://github.com/simplex-chat/simplex-chat/assets/154356073/7dcc5269-9a23-46fa-9129-85cce320c573)

</p>
</details> 

The elements on my screen were very small when i first installed MX Linux, so l followed [this guide](https://mxlinux.org/wiki/hardware/high-resolution-displays/), i tweaked the "Window Scaling" to be 2x in "Appearance"

<details><summary>Image</summary>
<p>

![Screenshot_2024-04-03_03-18-15](https://github.com/simplex-chat/simplex-chat/assets/154356073/c04fe044-02a9-4522-947e-a504455cb470)

</p>
</details>

Also i changed the DPI to custom one for the font to be a bit smaller and comfy

<details><summary>Image</summary>
<p>

![Screenshot_2024-04-03_03-18-06](https://github.com/simplex-chat/simplex-chat/assets/154356073/3caae91e-ff07-40e4-b55d-0092a3824c8f)

</p>
</details>

---

Now most of the apps on my computer looks like the above images and this:

<details><summary>Image</summary>
<p>

![Screenshot_2024-04-03_03-13-33](https://github.com/simplex-chat/simplex-chat/assets/154356073/3f7ec8aa-6711-4c6f-aab3-fb775538623a)

</p>
</details>

<details><summary>Image</summary>
<p>

![Screenshot_2024-04-03_03-17-33](https://github.com/simplex-chat/simplex-chat/assets/154356073/8a47e4f0-786a-4a92-9c56-2f3c1ef7b983)

</p>
</details>

When i open Simplex, it looks like this:

<details><summary>Image</summary>
<p>

![Screenshot_2024-04-03_03-13-47](https://github.com/simplex-chat/simplex-chat/assets/154356073/9baec8e2-5ad5-41c3-b5ba-5155002a17cf)

</p>
</details>

The interface elements are very small. The Simplex interface is displayed as 2560 x 1600 resolution without respecting the 2x window scale or custom font DPI.

The same problem is happening with Gimp for instance:

<details><summary>Image</summary>
<p>

![Screenshot_2024-04-03_07-40-08](https://github.com/simplex-chat/simplex-chat/assets/154356073/b9f0a7fb-e16c-4daa-9f04-6a70a9976ba6)

</p>
</details>

And some apps has a bit bigger interface, some Qt apps like Keepassxc and OBStudio, but they look fine afterall.

### Expected Behavior

Simplex should respect the Window scaling of the OS, the font DPI and display the interface correctly.

### Steps To Reproduce

1. Install MX Linux on a computer with a high resolution screen and install all latest system updates.
2. Follow [this guide](https://mxlinux.org/wiki/hardware/high-resolution-displays/) to make the interface bigger to be able to read comfortably. Make the Window scale 2x and the font DPI appropriate. 
3. Download Simplex the .deb package and install it.
4. Open Simplex and observe the interface.

**Comment by purplehepatica** [comment]
I agree, the problem exists. On Linux Fedora 40 and AppImage, the text is very small and using the app is not really pleasant. Personally, I thought it might be a great idea to implement a scaling selection from the settings, such as “150%, 200%” or via CTRL + "+/-" keys.

**Comment by sang-shelton** [comment]
> you can change font size now, does it help?

No, i still can't change font size, i am using version 5.8.2 flatpak

**Comment by sang-shelton** [comment]
> > > you can change font size now, does it help?
> > 
> > 
> > No, i still can't change font size, i am using version 5.8.2 flatpak
> 
> it's only available in v6.0.0 beta

I tried version 6.0 now and set the zoom to 1.5, now everything works fine. Thanks much
