### ISSUE TITLE
[Feature]: First-class Desktop App (independent of phone)

### ISSUE THREAD

**Issue by maltfield** [simplex-chat/simplex-chat#4020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux, Mac, Windows

### Feature

This ticket is a request to create a SimpleX app for Desktop (eg Linux) that is a "first-class" app -- one that is completely independent of a phone.

A "first-class" desktop app:

1. Allows a new user to create an account directly on the desktop app
2. Allows a new or existing user to send messages from their desktop to their contacts, with or without using the mobile app

This is a basic requirement that prevents many users from moving from platforms with first-class desktop apps (eg Skype, Wire, Matrix) to SimpleX.

**Comment by maltfield** [comment]
> currently in SimpleX Chat you can only link your device to a second mobile/desktop device on the local network, which requires your first device to remain online.

Yes, this is the problem. When people hear there is a "desktop app" then they expect to be able to use it without having to go through their phone on the local network. This is a "second-class desktop app"

>  you cannot use the same profile in 2 devices simultaneously for security reasons, other platforms allow unlimited amount of devices using the same profile through weakening security

I don't think this is an issue for most people, especially if the UX requires verification (cross-signing) of new device public keys from old devices via scanning QR code, manually reviewing the fingerprint, etc.

This is a basic requirement that will simply make SimpleX unuseable for many users until it is implemented.

**Comment by ElsAr4e** [comment]
I thought this will be not possible this year? https://www.reddit.com/r/SimpleXChat/comments/19bbisl/two_devices_at_once/

**Comment by epoberezkin** [comment]
What won't be possible is to be able to use two devices with the same profile.

You can certainly use desktop app independently from mobile, with its own user profile - when you install the app you have two choices:

1) connect to mobile (and you will be able to add an independent desktop profile later in this case).
2) create a new profile (and you can still connect to mobile later).

**Comment by maltfield** [comment]
*sigh* I guess SimpleX will always be unuseable for most users

*crosses SimpleX off the list of possible recommendations to users*

**Comment by ElsAr4e** [comment]
> What won't be possible is to be able to use two devices with the same profile.

@epoberezkin Do you mean that even in the future you don't even think about making it possible to use two different devices with the same profile (like Session)?

Or do you just mean not this year?

**Comment by sang-shelton** [comment]
I am thinking of a desktop app in Rust and [Iced](https://iced.rs/)

**Comment by Narasimha-sc** [comment]
> > you can create separate profiles and invite them to every chat that you want to be accessible from multiple devices, currently messages are deleted from servers on successful delivery, for a multi-device design, messages would have to be no longer deleted and kept to be sent to multiple devices, together with added attack surface from multi-device access, it's a difficult problem... currently there is no platform that handles multiple devices and end-to-end encryption without serious security flaws
> 
> This is misleading. The real issue is not unavoidable vulnerabilities, it’s the absence of a sophisticated synchronisation system designed with privacy in mind.
> 
> Platforms like Syncthing demonstrate that secure, peer-approved, bidirectional synchronisation is entirely possible and very secure indeed. Devices exchange data via encrypted relay communication, maintain decentralised profiles, and use user interaction for approval. The process can be adapted for SimpleX with no compromise to its metadata resistance goals.
> 
> A practical solution would include:
> 
>     * Synchronisation between authorised devices using SimpleX's existing relay nodes
> 
>     * Device linking initiated through a user-approved flow, where one device shows a one-time key and the other enters it
> 
>     * Use of ECDH for the initial key exchange, possibly followed by a Noise-based handshake for additional authentication and session security
> 
>     * Encrypted transfer of private keys and session data strictly through relay infrastructure, avoiding exposure to third-party servers
> 
>     * A clear explanation to users that each paired device increases the attack surface, which can be mitigated by hardware-level protections like TPMs or secure elements
> 
>     * Continued adherence to metadata protection by maintaining pairwise anonymous message queues across devices
> 
> 
> Multi-device support is not inherently insecure and certainly its incorrect to consider it insurmountable, it’s just needs some thought, a problem that deserves intelligent design and careful implementation. With the right architecture, it’s possible to deliver seamless, private cross device functionality without compromising security principles and sharing the same profile
> 
> For now, creating separate profiles across devices and expecting your contact to copy-paste their message to each of your many device 1:1 profiles, just to make sure you get it on all your devices, is a shocking solution. Its a band aid at best. Good luck, this is not a hard problem to solve, just needs some effort.

note that copy pasting to different profiles is currently not needed - just create a group with your devices and contact, and with business addresses, group creation is mostly automated
