### ISSUE TITLE
Not opening on iOS 15.3.1 (iPhone 7)

### ISSUE THREAD

**Issue by Yolakalemowa** [simplex-chat/simplex-chat#413]
Hi there,

First, congrats on the newly launched apps. I just tried on iOS but it fails to open :(

**Comment by epoberezkin** [comment]
Which device you are on? It might be that the current release on AppStore crashes on iPhone 7 - the release on TestFlight already fixed it and it is in review on AppStore - so could be available some time this week.

**Comment by Yolakalemowa** [comment]
@epoberezkin thanks. Yes it was iphone 7. Will await update soon :D 

keep up the good work. An exciting project.

**Comment by z8512** [comment]
> First, congrats on the newly launched apps. 

Its being developed for about 2 years

**Comment by Yolakalemowa** [comment]
> Its being developed for about 2 years

the mobile apps are that old?

**Comment by epoberezkin** [comment]
@Yolakalemowa it's now "in review" and you can get it via testflight :) 

> the mobile apps are that old?

Depends which part of the app... We started mobile app UIs in the end of January this year, so UIs are brand new. 80% of mobile apps code is Haskell code that is used in terminal clients, so it's not new. The protocol design started in the end of 2019, then there were some slow experiments with Haskell, the first server code is written in October 2020. So yes, about 2 years.

**Comment by epoberezkin** [comment]
The update is released @Yolakalemowa
