### ISSUE TITLE
[Bug]: Application doesn't open - white screen

### ISSUE THREAD

**Issue by Martina-Neumayer** [simplex-chat/simplex-chat#4138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

Android 8.0

### App version

5.7.1

### Current Behavior

Hi.
I am writing this bug report in the name of my husband who has this issue and doesn't have account here on github.

After today update from the v.5.4 to the latest v.5.7.1 from the official SimpleX F-Droid repository app doesn't launch properly. It somehow freezes on the "white screen". 
As shown on the screenshot attached.

Nothing else happens. The app don't even display the PIN lock screen.

Application needs to be killed otherwise it remains in that state indefinitely and after a while it also slows down the entire system pretty heavily.

Sadly I was unable to get any logs from the app. Even by using some external "logcat" apps, because SimpleX freezes immediately after start and also slows down the entire system of the device to such an extent that I cannot do anything at all on it. The only thing left is to turn off the phone using the hardware button to restart it. 

![Capture+_2024-05-06-08-43-01](https://github.com/simplex-chat/simplex-chat/assets/13028529/1b04873a-8c6e-46f0-b737-f87637925673)

### Expected Behavior

Normal app launch and to be functional as usual. 

### Steps To Reproduce

Install the 5.4 app version from the F-Droid's SimpleX repository, first.
Set up and configure the account etc. 
Update it to the 5.7.1 version.
Try to normally launch SimpleX application.

**Comment by avently** [comment]
> after a while it also slows down the entire system pretty heavily

Which means something is working and produces some logs anyway.

I'd like to help in this situation but in order to do it I need to look at the logs. Are you able to do the following? :
- setup `adb` on your computer by following this guide: https://www.xda-developers.com/install-adb-windows-macos-linux
- force close the app by going to system settings and finding SimpleX in Apps section
- connect to a computer
- launch adb with a command like `adb -d logcat -T 1 > log.txt`
- launch the app
- after you see it hangs, stop adb by pressing Ctrl + C in terminal
- modify log.txt by removing any private information you don't want to share
- upload log.txt here

This way I will be able to understand the problem, I hope.

**Comment by Martina-Neumayer** [comment]
@avently No worries, I know how to use and gather logs 😉 but thanks anyway.

The problem is (and I know that is bit strange) that, that there is nothing to find, no trace of any crash logs from this app in the entire system after the device reboots itself. Sadly after my husband did the data/cache cleaning, leaving the SompleX app hanged lead to the phone overheating and immediate rebooting. Few seconds and it is restarting on alone.

Well.. I will later try to catch some data in the other way, but to do that I need to be at home.
If I get something useful I will attach it here in the topic.

**Comment by Martina-Neumayer** [comment]
Okay.. I think I know whee the whole problem was or perhaps still is, but that's not your or SimpleX app fault.

The fault here is fully on the F-Droid side.
Their faulty stupid app had updated to the wrong version.

Instead of selecting a proper v7a file accordingly to the device's system, it somehow forced v8a.

Such a simple task as properly recognizing system architecture by F-Droid can of course not be normally done, because why bother about it?
They trying that for years and still can't. 🤦‍♀️

My man tapped as usual on the "update" button and the dumb fdroid made him a mess. 

I have today manually select the v7a file from the versions list and now is working fine.

Okay, almost fine because of the one old issue with the profile picture which can't be loaded from the device gallery - that bug is still present.

But everything else seems to be all right.

The solution is to choose the file for update by hand, instead of automatically.

Perhaps this problem should be reported to the F-Droid directly? They should fix that asap.

I think I can close the this issue now.
Thank you for quick response and sorry for the false alarm 😇

**Comment by avently** [comment]
That wasn't obvious reason for such situation, good to know that you sorted it out.

> almost fine because of the one old issue with the profile picture which can't be loaded from the device gallery - that bug is still present

Did you see such issue on Github regarding this problem? So I would look closely on it. If there is no such issue, you can create one with details of how to reproduce it. Because It's probably not about Android 8 specific problem but about maybe the gallery app you use. I use Simple Gallery from F-Droid and it works just fine

**Comment by epoberezkin** [comment]
I am wondering if we can do something from our side to mark APKs in some way to help f-droid app correctly determine which one should be used?

cc @licaon-kter @shumvgolove

**Comment by Martina-Neumayer** [comment]
@avently That's true. I was lucky I think. You know.. We are a married couple for years but some things we are doing with slightly different ways. Well.. lesson learned for the future 😁

As for the second bug, no I don't saw such issue here. I was searching but nothing found.

If I remember correctly I saw this problem from the very early SimpleX versions. Some people on Mastodon told us that they doesn't have it anymore after the update to the 5.7 version. That's why my husband wants to check and try it. But without success.

Even reinstalling the app from scratch with the data/cache cleaning doesn't help.

I tried to reproduce the issue on the different phones and yes it is there as well. Samsung, Huawei, Lg had it.

I think that is the app problem because by doing this SimpleX app does not call for the permission to access the data storage on the phone - "storage and usb" one on every single of them.

Even if I manually add this permission nothing changes. Still it is not possible to load the picture.

But works fine if I choose camera as a source. Permission to use device camera is called, screen info pops up and after I allow it, everything works as it should.

There is also no difference by what app I choose to do that task - different galleries, filemanagers or system default file chooser. None of them seem to work.

I can browse through the directories, I can see the pictures, but after I tap on some, nothing happens, except for going back to the profile picture choosing screen.

Those devices I tried on, have different system versions. From android 8 up to 13. With google services installed and also without them.
The symptoms are identical on each of them.

I tried all the standard things to do, data/cache cleaning, app reinstalling, device factory reset or in two cases also firmware reflash.
Sadly and literally nothing helps.

I also have one phone where it works, an OnePlus. On that one there's no issue at all. Picture loads normally, but still the permission isn't called. It's need to be added manually.

Apps I used to test were same as my husband is using on his phone: Default lg's gallery from their android 8, QuickPic forked/modded version, Photo Studio PRO, File manager +

I also noticed something strange, don't know if this is important?
By choosing from gallery option in SimpleX on the next screen where are showing up available apps to use, it also appears app completely not related to the task. For example an icon pack app which is installed on the phone. No idea what it is doing there and why it can be chosen?
Out of curiosity, I checked and installed various icon packs on my test phones and yes, they show up there on all of them.

@epoberezkin 
I think that is possible. Some time ago I saw similar problem that people had with the "OsmAnd" maps application. Identical thing happened. But now is no more. Seems that they have done something with their app, but I don't know what exactly or how they managed it.

Once I've only heard an "between devs talk" that this problem can very possibly be because of F-Droid is sometimes messing crap with the apps signature keys, that are published trough their platform. It was an discussion between the programmers sitting in the club. You know. 

But I have no idea if this is true?
I never used F-Droid to release my apps or code. So, I can't confirm that.

**Comment by licaon-kter** [comment]
@Martina-Neumayer

> Android 8.0

But which device exactly? And why do you think it should use armv7 exactly?

> I have today manually select the v7a file from the versions list and now is working fine.

On devices that DON'T support arm64 there's nothing to select, because it is not compatible hence arm64 is not shown.

eg. I can't get 5.7.1 arm64 working either, and my device supports arm64, lol

One issue that I see, not under F-Droid's control since the repo is from upstream, is that both arm64 and armv7 are the same version code @epoberezkin as F-Droid does not recommend this.

> because of F-Droid is sometimes messing crap with the apps signature keys, that are published trough their platform

Maybe don't use FUD and hearsay when asking for help, pretty please?

**Comment by licaon-kter** [comment]
Testing this, I did uncover one issue: https://gitlab.com/fdroid/fdroidclient/-/issues/2792

**Comment by licaon-kter** [comment]
> On some models and their variants v8a apk'a are working fine, but on other ones not and user need to choose v7a instead. The v8a app won't launch. 

that's true for all apps or just some? Eg. if you install Quicksy arm64 _(if you don't have it already I mean :smile:)_: https://f-droid.org/repo/im.quicksy.client_4211004.apk does it start to the "enter phone number screen"?

> I asked a few friends who worked at LG about this, but even they couldn't answer this question. 

Think I heard about such cases, yes, but never encountered one.

**Comment by Martina-Neumayer** [comment]
@licaon-kter
That's true. It happens differently, depending on the device model, variant of it, firmware installed and the app as well.

I have mine v30 too but it is an Korean DS variant. DS means dual-sim. With factory 8.1 system and there are no issues at all. All v8a apps are working nice.
But on my husband european model not. Some apps are okay, but some must be v7a otherwise they won't even start. As for example your SimpleX. But the "Osm And" he has is in the v8a version works normally. 
That's totally strange, I know.

I've tested now this "Quicksy" on his phone and it is working good. Even F-Droid have recommend v8a for installation.

Well.. I saw this many times. Even more stranger than that things by the time I had worked six years in their Chungcheongbuk-do research factory. And that's why I know that by android and it's apps everything is possible and can be expected. Not mentioning that by LG hardware/devices too. 
Yes they designed amazing products, new things etc. They were precursors in this topic and lots of their ideas, patents are even today widely used by the other companies. Their some designs were superb, without any doubts. For example their latest mobile phone model that sadly almost no one knows about. The v70 one, which was manufactured in the very small amount and given to the employees as an "good bye" gift. This thing was fully packed with everything they had and they planned to release in the future devices. I had an opportunity to have it in my hands and play with only one time for circa two weeks. Gosh! What an frickin crazy phone it was! I was totally shocked how cool made it was. It is very sad that they doesn't release it for a normal sale to customers. This thing if released would turn the entire today phone market 180 degrees. Well.. but they decided otherwise and shut down the whole mobile production. 
But they also have problems later with bringing all that cool stuff and ideas into the real life, and by manufacturing them as well. Bad management, stupid decisions, greed for money, cheaper and cheaper, mass made products etc. That killed the company in this particular area.

**Comment by licaon-kter** [comment]
> Even F-Droid have recommend v8a for installation.

Yes, as the phone says "I can do arm64 I swear" :( :)

**Comment by epoberezkin** [comment]
@licaon-kter I may be confused here, but is it the case of arm64 compatible CPUs that are vendor-locked in 32 mode?

The latter is rather common afaik.

So, maybe it's possible not only to detect which CPU mode is _capable_ of, but it's also to detect the system kernel mode, and if it's 32bit then offer armv7a APKs?

**Comment by epoberezkin** [comment]
@Martina-Neumayer can you please install z-cpu app and see what kernel mode it reports?

**Comment by Martina-Neumayer** [comment]
@epoberezkin Yes of course. Here you have some infos from this app.

![Capture+_2024-05-07-12-09-26](https://github.com/simplex-chat/simplex-chat/assets/13028529/13e8cedb-7053-497a-a4d5-9616029c20d1)
![Capture+_2024-05-07-12-09-59](https://github.com/simplex-chat/simplex-chat/assets/13028529/ca28f3ac-89a7-4ca5-98d6-3e1f5a40f5f4)
![Capture+_2024-05-07-12-12-48](https://github.com/simplex-chat/simplex-chat/assets/13028529/d544f994-dc14-47a5-992c-f88c82d6c223)

**Comment by licaon-kter** [comment]
`Kernel Architecture: aarch64` sounds pretty clear to me, odd that LG b0rken it so bad

I had this CPU in Pixel 2 and 2 XL and works fine on arm64

elsewhere you can get Android 14 ( for it https://wiki.lineageos.org/devices/joan/ ) and maybe not be stuck on 8, but yeah :shrug:

**Comment by epoberezkin** [comment]
yes, I've seen 32-bit devices with 64-bit CPUs that correctly reported 32 bit kernel - so this indeed looks like the device issue 🤦‍♂️

**Comment by epoberezkin** [comment]
ok, thank you @licaon-kter for helping us figuring it out...

@Martina-Neumayer upgrading would also increase device security if you get Android 14 that no longer supports 32 bit apps (I think).

**Comment by licaon-kter** [comment]
@Martina-Neumayer I see that that you should be able to get at least Android 9: https://www.gsmarena.com/lg_v30-8712.php but not sure if that fixes it since it could still be LG bad :) but it's newer anyway, until you figure out how to jump to Lineage :wink:

**Comment by Martina-Neumayer** [comment]
@epoberezkin Sadly there is no newest factory firmware available for this phone as 9.0. They planned to do 10, but never did.

Besides from the 9 one some important for my husband features suddenly stopped working, because, as it shows up bit later, google removed them from the source code which LG used to build their system images back in the days.
For example wide range equalizer build into the phone hardware DAC doesn't work anymore, there was also very limited manual camera mode where in 8 it is fully available. And so on. That's why he decided to stay on the system that the phone comes with from the factory. He is totally happy with it and doesn't want any third-party custom roms. 

@licaon-kter He once upgraded to the 9 but very quickly want to go back to the 8 one. Luckily I had factory images for my box and was able to get his phone back to the previous state. He was completely disappointed with the Pie and what they did with it. He bought this device especially for the great quality of music and camera full manual mode he uses very often. They get completely "castrated" out from the Pie. Why? I don't know, but google does such stupid ideas even now.
Apart from that, and from what I've seen, the eighth version is the best one made for this phone.

**Comment by pedrodelbosque** [comment]
Something similar has been happening to me (for years now); for every 5-6 times I open SimpleX, a black screen hangs indefinitely until I force stop and launch again. This is seemingly random, I see no recognizable pattern

**Comment by Martina-Neumayer** [comment]
@pedrodelbosque A black screen is a bit different than the white one. In most cases it is a symptom of problems with the device's memory.
For example if the phone memory is full of some user data, apps temporary data and such things.
Android is sadly a bit stupid system in that topic and by circa 75-90 percent of the full memory/storage begin to play strange things.

The second most common cause of the black (and also light blue or green) screen are some hardware issues.
Memory chipsets can going bad, dying, ootb being faulty or low quality parts have been mounted by the factory. Memory chips can very often even detaching or desoldering, themselves from the motherboard due to overheating of the device.

I had on my service table plenty of such cases in the few past years.
Sadly actually made devices are so cheap and poor manufactured that is literally beyond believing sometimes.

Well.. It can also be an particular app fault.

It is hard to say what's the exact reason, without any logs provided.

In one of the comments here above was mentioned how to get them.

If you can do and provide it here, perhaps someone will be able to say more and help you?

**Comment by pedrodelbosque** [comment]
@Martina-Neumayer Actually, it's a grey-blackish screen, default SimpleX background one. Sometimes, it hangs indefinitely displaying the big startup SimpleX logo, so I'd say its a software issue. To be sure, I just reproduced the bug by simple opening and backing out of the app a couple of times. I appreciate you enthusiasm to try to fix this long-time issue, I'll post logs ASAP.

**Comment by pedrodelbosque** [comment]
@Martina-Neumayer @avently I've opened a separate issue, https://github.com/simplex-chat/simplex-chat/issues/4154, providing logs, as to not clutter this thread.
