### ISSUE TITLE
Secret shown in notification  message

### ISSUE THREAD

**Issue by damien-biasotto** [simplex-chat/simplex-chat#416]
When using markdown #secret#, the notification will show the text in clear on iOS.

**Comment by epoberezkin** [comment]
yes, I am also annoyed by it - just realised it yesterday! needs to be improved - than you!

**Comment by damien-biasotto** [comment]
Sorry for the short feedback, I was trying it out with my wife , and I just noticed that, so before I forgot, I wrote it down. It's not critical at all :)  

I'm an Haskell enthusiast, and really I am impressed by the app, especially building the mobile app.

**Comment by damien-biasotto** [comment]
Also, my wife has a weird bug on her phone, she can't copy the secret message, iPhone 12 Pro, iOS 15.3.1 whereas I can on my iPhone 12 Pro Max iOS 15.3.1.

I tried restarting her phone, deleting/reinstalling the app, and starting a new conversation, she still has the same issue.

No idea how to reproduce it on mine. We both have multilingual keyboards, but I believe she has an extra one (non-official).

She could be unlucky and be the only one affected by it, but I believe it is worth mentioning it.

**Comment by epoberezkin** [comment]
this pr would fix notifications :)

We will add context menu to messages in some release in March, that would have reply (without quoting the message), copy and possibly some other actions, so there will be a workaround to copying it as a selectable text (which also copies the time, which is difficult to avoid, and also not very convenient anyway...)

Thank you!

**Comment by epoberezkin** [comment]
closing it - release is coming next week
