### ISSUE TITLE
Link in FAQ returns 404

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [simplex-chat/simplex-chat#4173]
The link listed in https://simplex.chat/faq/#what-is-database-what-can-i-do-with-it returns a 404

I initially opened my issue in https://github.com/simplex-chat/website but i saw in another issue in that repo that the repo is deprecated. 

**Please archive the repo and direct users to this repo so we can prevent users being confused**

**Comment by epoberezkin** [comment]
fixed
