### ISSUE TITLE
[Bug]: Wallpaper don't show in empty rooms

### ISSUE THREAD

**Issue by summoner001** [simplex-chat/simplex-chat#4210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

Android 9

### App version

5.8-beta.1

### Current Behavior

Wallpaper don't show when the room is empty, If there are no messages.

### Expected Behavior

Show wallpaper in the room

### Steps To Reproduce

1) Set a custom wallpaper.
2) Make a new room or clear messages in one room

**Comment by avently** [comment]
This is fixed already in beta 3 or 4

**Comment by summoner001** [comment]
@avently I can confirm! This issue is solved in 5.8-beta.3 rls. Thanks!
