### ISSUE TITLE
[Q]: Scalable Group Messaging Proposal

### ISSUE THREAD

**Issue by JonathanWilbur** [simplex-chat/simplex-chat#4220]
### Question

It is an admitted shortcoming of Simplex Chat that group messaging is not very scalable. As I understand it, when chatting in a group, all messages get delivered individually to all other recipients by the sending client, rather than fan-out happening at the server. (Let me interject here and say that I do understand the privacy concerns with fan-out happening at the server: members in a group are thereby disclosed to the server.) For N group members in the chat, every user message sent results in N-1 messages in the underlying SMP transport (and each is decrypted and re-encrypted!).

It seems to me that there should be an _option_ (I want to emphasize that this shouldn't be a default or mandatory behavior) to use an alternate more scalable--though less private--approach as follows:

The server receives messages at a queue as usual. However, multiple senders use the same private key (or perhaps the protocol can accommodate different private keys that are still privileged to write to the same queue). This queue serves as an inbox for the whole group chat. Everybody submits messages to this queue, and everybody reads from this queue. This queue is a central point where the group relays messages.

One sender key is the "admin" of this queue, and only this key can delete messages from the queue; all others can only download messages. The admin ultimately can delete messages arbitrarily, but a beneficent admin will wait until all group members have seen a message (perhaps signaled via an application-layer message) before deleting a message from the queue.

This, as far as I can see, solves the scalability problem. A message is uploaded once and downloaded many times. Instead of having 2*(N-1) copies of the message being encrypted, only (N-1) are encrypted (from server-to-client upon download). Instead of storing N-1 copies of the message on the server, only 1 copy is stored.

As far as I can see, the pros are:

- Greatly reduced storage demands on the server
- Reduced compute demands on the server
- Reduced compute demands on clients (which are often mobile phones, and therefore resource-constrained)

And the cons are:

- Reduced privacy: the server can who is in a group
- Trusting not only the server, but now the admin too, to not delete messages to suppress their receipt by group members
- Complexity, of course. This is a new feature.

Things to be discussed (inclusively):

- How members can be kicked out of a group (perhaps by just creating another queue for a new "epoch" of the group (to borrow Message Layer Security terms)) and distributing the keys to the "survivors" of this "purge"

I want to clarify that I do not believe this should _replace_ the existing group chat mechanism. It should be an _option_. Perhaps in the UI, when a user creates a new group chat, they may be asked if they want it to be a "small and secret" or "scalable, but less private" group chat.

Thanks for reading, and thanks for implementing this wonderful protocol! It's genius!

**Comment by greensheeps** [comment]
This is already being addressed with super peers and won't reduce privacy by exposing any information to the server
it's covered in this live stream from last year
https://youtu.be/7yjQFmhAftE

**Comment by JonathanWilbur** [comment]
That makes perfect sense. Thank you! Closing.
