### ISSUE TITLE
[Q]: Are backups worthless because of break-in recovery?

### ISSUE THREAD

**Issue by pedrodelbosque** [simplex-chat/simplex-chat#4223]
### Question

If I understand correctly, the currently implemented break-in recovery randomly switches encryption keys with each message.
I am currently doing backups every week, expecting my chats to be available and usable in case I lose my device, restoring the database to a state from days prior.

But, because of break-in recovery, this is worthless, right? Is it true that I will not be able to contact any user that I have messaged between now and the last backup?

**Comment by epoberezkin** [comment]
there are two layers of encryption - per queue and double ratchet.

If you restore from backup, you are likely to start receiving "decryption failed" errors in contacts with which you exchanged messages. In this case you will have a button "fix encryption" and it will re-negotiate new ratchets (and if security code was verified, the verification status will be reset).

If messages were sent only in one direction (that is, before break-in recovery was triggered) you will see "skipped messages".

So if the attacker were to obtain a copy of the database and the passphrase, either they will lose the ability to receive messages or you will, so it won't be undetected.

But backups aren't completely worthless - while you would miss some messages until encryption is re-established, you would keep the connection - then it's up to you how you verify the authenticity of your contact.

Please just run experiment:

1) make a backup
2) exchange messages with some test connection you control
3) restore from backup

**Comment by pedrodelbosque** [comment]
That's excellent, thanks a ton for the info.
