### ISSUE TITLE
Why do you need of "change your audio settings" permission?

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#4227]
For bluetooth headset?

This is a dangerous change because I don't have full control over volume audio, especially when I have to be silent in certain scenario (office, church, etc.). In this way I am not the only entity to change the volume and/or audio channel destination (loudness speaker, ear capsule, bluetooth headset or speaker).

Not strictly necessary in my opinion.

**Comment by avently** [comment]
This permission is required because the app allows to change audio route while in call. So you can play sound from speaker, earpiece, bluetooth, usb, etc. This permission can not be removed without removing functionality which we will not do.
