### ISSUE TITLE
simplex name is not catchy

### ISSUE THREAD

**Issue by yaitskov** [simplex-chat/simplex-chat#427]
Hi,

I am very glad that Haskell ecosystem can provide such cool tool for broad audience, but I am concerned with name. 

- word simple has negative associations
- simplex makes me think about X window manager
- simplex-chat is 2 words
- simplex is not related to info propagation (compare with whatsapp, messenger, telegram)
- Google Play has other apps with same name

**Comment by epoberezkin** [comment]
Thank you for the feedback!

> word simple has negative associations

Not sure I feel the same, people seem to prefer simple things...

> simplex is not related to info propagation (compare with whatsapp, messenger, telegram)

It's from "simplex communication" - the core protocol defines unidirectional queues that the whole network is built on, whether for direct or group conversations.

> Google Play has other apps with same name

that is true.

We will re-evaluate after some time.
