### ISSUE TITLE
Android 9 support

### ISSUE THREAD

**Issue by yaitskov** [simplex-chat/simplex-chat#428]
I wanted to try the app and realized that it is not available for my device (Motorola g7).
It is a very cheap and popular gadget.

**Comment by epoberezkin** [comment]
We are working on Android 9 support!

**Comment by ata-star** [comment]
would love it if my android 11 device would be supported even

**Comment by DeMoN100** [comment]
Related Issue Compatability Request!
#1384

**Comment by BarbzYHOOL** [comment]
Simplex looks incredible, my phone is on android 7, sadly (it's from 2018)

**Comment by Kortik7** [comment]
blank page when using Pixle 3a with GraphineOS and latest release of simpleX  cannot use this app.

**Comment by epoberezkin** [comment]
https://github.com/simplex-chat/simplex-chat/releases/tag/v4.6.0-beta.0

This beta supports armv7a and Android 8+

**Comment by epoberezkin** [comment]
post any comments/feedback here please: https://github.com/simplex-chat/simplex-chat/issues/538
