### ISSUE TITLE
SimpleX client for The Light Phone III

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#4323]
• Website https://www.thelightphone.com/lightiii

• YouTube https://www.youtube.com/watch?v=KhMb0-t2MyU

A phone for minimalists.

![1000113699](https://github.com/simplex-chat/simplex-chat/assets/113377431/37778ee1-a858-4f08-b128-2b35e8ff3f1a)

![1000113701](https://github.com/simplex-chat/simplex-chat/assets/113377431/356429c7-5d56-46d1-a8a7-5ca96ffd3d9d)

![1000113705](https://github.com/simplex-chat/simplex-chat/assets/113377431/ed966716-84cf-400c-bf4a-cc414f221e16)

![1000113708](https://github.com/simplex-chat/simplex-chat/assets/113377431/c975c554-88ad-4f6b-9ebf-756a96717db7)

**Comment by PalmTamino** [comment]
Nobody uses this product. Its wasted time for simplex developers.

Why not just use an android phone with a custom rom without any apps or something, and you got a better light phone…

**Comment by PalmTamino** [comment]
> > Nobody uses this product.
> 
> Source?
> 
> It has been presented yesterday. Come on, give it its time to grown.

Mrwhosetheboss reviewed it here: [https://youtu.be/Fd57NOavMWs?si=vkFR4SCkaw0PRk5w](url) minute 12:31

And its a terrible phone, no reason to work on an app for it…

**Comment by PalmTamino** [comment]
> > its a terrible phone, no reason to work on an app for it…
> 
> Maybe you didn't read the word "minimalist" phone. It is not, intentionally, a smartphone.
> 
> It is a device for seniors or for men that not need of all powerful features.
> 
> It is an aware choise, not a mistake or a lack.

Just get Nokia 8810 instead, i think you can even sideload simplex to it. But considering development for this phone is beyond crazy

**Comment by pedrodelbosque** [comment]
> This will become a global trendy product.

doubt

**Comment by Lippiece** [comment]
This looks like an advertisment

**Comment by Lippiece** [comment]
> > This looks like an advertisment
> 
> Then we split the money that this company pays me to advertise it. 🙂
> 
> 50% / 50% okay?

They don't have to pay you for you to be able to advertise it. It's like wearing a hoodie with a logo, except this here feels more… intentional.

**Comment by greensheeps** [comment]
This device is insecure and certainly doesn't have anywhere close to the market share of iOS/Android so it's probably not worth developing a client for
