### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [simplex-chat/simplex-chat#437]
How hard would that be, to build the app only from FOSS deps?

Eg. https://github.com/simplex-chat/simplex-chat/blob/stable/apps/android/app/build.gradle#L94 needs to be removed/replaced (it's not FOSS), say via a gradle flavour

**Comment by epoberezkin** [comment]
That one shouldn’t be too hard to replace I think - good spot.

I don’t think there is anything else to replace, is there?

**Comment by epoberezkin** [comment]
We’ve made a repo for a f-droid client btw - do you mean to add to f-droid catalogue?

**Comment by licaon-kter** [comment]
Of course.

It's great that you have a repo, decentralization is an F-Droid tenet...but I didn't see any mentions of it on the website.

**Comment by epoberezkin** [comment]
@licaon-kter hey! we've replaced the qr code recognition library with an open-source one - it will be in v2 release (due Tuesday May 10)

**Comment by licaon-kter** [comment]
Any build instructions for Android? The Haskell stuff...

**Comment by licaon-kter** [comment]
Status IM app uses a Nix build chain, building stuff as needed.
