### ISSUE TITLE
Android app dont run in background

### ISSUE THREAD

**Issue by mika-nl** [simplex-chat/simplex-chat#441]
First , thx for the nice app.

My problem :
On some phones the app dont run in the background.
I try all options in the website https://dontkillmyapp.com/

The problem is that you dont get a notification or  a message.

**Comment by epoberezkin** [comment]
Great you like it - thank you!

We're aware of the problem - will be fixing it!

Longer term (think 3-4 weeks) we will be adding push notifications, but looks like there is a value in making it run on schedule in background...

**Comment by fightuntilwedie** [comment]
Hi, same here. Right now SimpleX doesn't register with MicroG for push notifications but I get notifications when I don't close the app but simply minimize it. Is that the correct behaviour at this level of development?

**Comment by epoberezkin** [comment]
Yes, the next release should improve it - I’m considering making it a foreground service - as it’s just open sockets, so it should consume very little power if any in the absence of messages.

**Comment by fightuntilwedie** [comment]
Okay, thank you!

**Comment by mika-nl** [comment]
This is fixed in v3
