### ISSUE TITLE
[Feature]: Database encryption at rest on mobile

### ISSUE THREAD

**Issue by greensheeps** [simplex-chat/simplex-chat#4417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android, iOS

### Feature

Add ability to encrypt database at rest [like Molly](https://github.com/mollyim/mollyim-android/wiki/Data-Encryption-At-Rest)

**Comment by epoberezkin** [comment]
yes

**Comment by greensheeps** [comment]
> yes - it is already encrypted. Not sure what is proposed on top of what exists.

You're right.

**Comment by greensheeps** [comment]
[KeePassXC](https://github.com/Kunzisoft/KeePassDX) and [Molly](https://github.com/mollyim/mollyim-android) show a notification to remind you the database is unlocked, with a button to quickly close it.

**Comment by greensheeps** [comment]
![Screenshot_20240818-215439](https://github.com/user-attachments/assets/c20a6679-9a78-426f-866c-e48c6c44105f)
