### ISSUE TITLE
Can't connect to anyone using latest iOS client

### ISSUE THREAD

**Issue by adamshand** [simplex-chat/simplex-chat#449]
Hello,

I'm a brand-new user.  I've downloaded the latest version of simplex-chat from the iOS App Store and installed the terminal client on my macOS laptop and Linux server.  The macOS & Linux clients seems to be working as expected, but on the iOS client I don't seem to be able to do anything.  

Clicking the top right icon does nothing.

So I sent an invitation from the macOS client to my iOS device and I get a message saying that my macOS client wants to connect, but clicking on the message does nothing.

In addition, clicking the "# Chat with the founder" link in the settings takes me to "Your chats" but does nothing else.

I've tried with the latest simplex-chat iOS version from the app store and the TestFlight version.  Running iOS 15.2.1 on an iPhone 12 mini.

I assume I'm doing something stupid, but I can't for the life of me see what.

Many thanks,
Adam.

**Comment by adamshand** [comment]
Hrm, I just force quit the iOS app and now it appears to be working as expected. 

If there’s any debugging information I can send through to be helpful, please let me know.

**Comment by epoberezkin** [comment]
Thanks you for the report! If you could open the chat console and see if there are any errors there? But it would be cleared if you restarted most likely.
I've seen the client could temporarily hang if the network connection is bad - I am investigating how to improve it - it seems related...

**Comment by epoberezkin** [comment]
closing it for now - please ping here if it reoccurs.
