### ISSUE TITLE
[Q]: Failed run using terminal

### ISSUE THREAD

**Issue by ysavr** [simplex-chat/simplex-chat#4509]
### Question

i have install simplex-chat using this command
`curl -o- https://raw.githubusercontent.com/simplex-chat/simplex-chat/stable/install.sh | bash`

but when i run using `simplex-chat`

found this error
```
dyld[21039]: Library not loaded: /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib
  Referenced from: <15FEC632-76E8-3D78-8D06-3AB35639FE02> /Users/mobiledev/.local/bin/simplex-chat
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file)
zsh: abort      simplex-chat
```

**Comment by avently** [comment]
The script you use doesn't take into account that your version of Debian/Ubuntu can be newer and tries to download binaries for older version of OS.


You can change the script yourself if you wish:
https://github.com/simplex-chat/simplex-chat/blob/stable/install.sh#L23

Specify here 22_04 instead of 20_04. And it should work.

This script works only with Debian/Ubuntu.

**Comment by ysavr** [comment]
Still facing same issue run this script on m1 mac

> The script you use doesn't take into account that your version of Debian/Ubuntu can be newer and tries to download binaries for older version of OS.
> 
> You can change the script yourself if you wish: https://github.com/simplex-chat/simplex-chat/blob/stable/install.sh#L23
> 
> Specify here 22_04 instead of 20_04. And it should work.
> 
> This script works only with Debian/Ubuntu.

**Comment by avently** [comment]
@ysavr ahah, I didn't even notice that you were on mac, sorry, it was too late for me. The script only expects to see x86_64, not an arm.

**Comment by avently** [comment]
Also, I think you can fix the situation just by installing openssl@1.1 yourself via Homebrew like this:

brew install openssl@1.1

Since mac can run that x86_64 via Rosetta. But still you need openssl installed

**Comment by ysavr** [comment]
@avently i already installing openssl@1.1 also facing this issue

```
dyld[21111]: Library not loaded: /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib
  Referenced from: <15FEC632-76E8-3D78-8D06-3AB35639FE02> /Users/mobiledev/.local/bin/simplex-chat
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file)
zsh: abort      simplex-chat
```

**Comment by avently** [comment]
Interesting, what path does this command show to you?
brew info openssl@1.1

In my case at the bottom of the output (where brew says about exporting PATH) I see the same path as in your message.

**Comment by ysavr** [comment]
this is my log from `brew info openssl@1.1`
```
brew info openssl@1.1
==> openssl@1.1: stable 1.1.1w (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
Deprecated because it is not supported upstream! It will be disabled on 2024-10-24.
Installed
/opt/homebrew/Cellar/openssl@1.1/1.1.1w (8,102 files, 18MB)
  Poured from bottle using the formulae.brew.sh API on 2024-07-24 at 10:32:23
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/o/openssl@1.1.rb
License: OpenSSL
==> Dependencies
Required: ca-certificates ✘
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /opt/homebrew/etc/openssl@1.1/certs

and run
  /opt/homebrew/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /opt/homebrew,
because this is an alternate version of another formula.

If you need to have openssl@1.1 first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.1/lib/pkgconfig"
==> Analytics
install: 30,411 (30 days), 107,928 (90 days), 878,209 (365 days)
install-on-request: 18,374 (30 days), 69,663 (90 days), 487,033 (365 days)
build-error: 12 (30 days)

```

**Comment by avently** [comment]
So in you case Homebrew put libraries into different path than expected by binary. Try the following **without sudo first**. If it doesn't work (not enough permissions), prepend `sudo` for the following commands:
```bash
mkdir -p /usr/local/opt
ln -s /opt/homebrew/opt/openssl@1.1 /usr/local/opt/openssl@1.1
```

**Comment by ysavr** [comment]
After i update the path there is an architecture issue for openssl, should i use another version for openssl ?

```
dyld[32238]: Library not loaded: /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib
  Referenced from: <15FEC632-76E8-3D78-8D06-3AB35639FE02> /Users/mobiledev/.local/bin/simplex-chat
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib/libcrypto.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib/libcrypto.1.1.dylib' (no such file), '/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib/libcrypto.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
zsh: abort      simplex-chat
```

**Comment by avently** [comment]
Better to just use a binary for arm which we have too (just not in that script). 
You have two choices:

Edit script here: https://github.com/simplex-chat/simplex-chat/blob/stable/install.sh#L21 and specify ` macos-aarch64 ` instead of `macos-x86-64`. Rerun the script


**Or** 

Download correct binary (named ` simplex-chat-macos-aarch64 `) yourself from here: https://github.com/simplex-chat/simplex-chat/releases , rename it to `simplex-chat`, put it to `$HOME/.local/bin`, make it executable `chmod +x $HOME/.local/bin/simplex-chat`. 
You can run this commands when you download the binary to Downloads (just to automate what I said before):
```bash
mv ~/Downloads/simplex-chat-macos-aarch64 ~/.local/bin/simplex-chat
chmod +x ~/.local/bin/simplex-chat
```

Then you can run it, finally

**Comment by ysavr** [comment]
thank you @avently it finally run

**Comment by ysavr** [comment]
can you give me a suggestion if i want to run an android app on android studio?,  [issue](https://github.com/simplex-chat/simplex-chat/issues/2697#issue-1804808183)
