### ISSUE TITLE
[Feature]: rewrite desktop client

### ISSUE THREAD

**Issue by ghost** [simplex-chat/simplex-chat#4550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

all

### App version

all

### Feature

desktop clients severly needs rework/love, interface, markdown, chats, message and image duplication, clipboard issues, squished sent messages, and slew of other oversighted design with current distribution. severly needs more work and actual love and support. all the simplex protocols still exist but are not hooked up. extreme disappointment just trying to use simplex and its experience for month of use...simplex desktop (java) is also affected by fracturiser malware (we found and have a sample that detects more processes) and can reside undetected, so thats just great. in tests it rats and stole our database which apparently can be easily decrypted as nothing inside was encoded, everything was converted to plaintext. simplex is really feeling like a wash and not what expected with something so 'popular'

**Comment by epoberezkin** [comment]
Without specifics and details proving the statements it's hard to respond or address any issues - this does not read as a credible report, sorry.

Part of this message reads as security vulnerability report, if so - it should be submitted privately: https://simplex.chat/security/

If you really observed some abnormal behaviours and were simply writing this message in a rush, and also have confirmation/proof that it is indeed the client and not some other system processes, then please submit a detailed report following the process described above - either via email or to team's address in the client.

Specifically about the database, it is encrypted. If you see some files that are not encrypted then again - please submit detailed report via the above process. Users may choose to store database passphrase in plaintext (for convenience), but this is not the default option that the app offers.

Thank you.
