### ISSUE TITLE
Nix: build terminal app for aarch64

### ISSUE THREAD

**Issue by 573** [simplex-chat/simplex-chat#456]
Is there a possibility to build the Console-Version on aarch64-linux via nix ?

**Comment by vsevolod-mineev** [comment]
Not sure if this helps but I have a garage project where I compiled this for aarch64-ubuntu here: https://github.com/vsevolod-mineev/simplex-aarch64-termux 

I use simplex from my S9 within Termux. 

I maintain this repo with the latest binaries, just click on releases.

This binary is to be launched from
```proot-distro login ubuntu```
I'm not sure how nix fits into this picture.

Kindest regards,
VM

**Comment by 573** [comment]
@vsevolod-mineev first of all  thx, this guide is awesome I think I should give proot a try.

atm I have flake-enabled nix set up already (via nix-on-droid) so my question would be more like how I'd build the command line client.

```console
nix-repl> :lf /data/data/com.termux.nix/files/home/simplex-chat/
nix-repl> :b packages.aarch64-linux.exe\:simplex-chat
```

seems not yet to do the right thing here.

**Comment by 573** [comment]
```console
nix build .#packages.aarch64-linux.exe:simplex-chat
```
I get

>trace: To make project.plan-nix for haskell-project a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.           trace: To materialize project.plan-nix for haskell-project entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.                       trace: haskell-nix.haskellLib.cleanGit: /nix/store/npx4r48kzy59g058456fb39yl45xwqmy-source does not seem to be a git repository,    assuming it is a clean checkout.                                  error: attribute 'https://github.com/simplex-chat/simplexmq.git' missing                                                                                                                                     at /nix/store/6w5dr9xpxi5jcvg865r760ry76af1vlg-source/lib/cabal-project-parser.nix:82:14:                                                                                                                 81|       if sha256map != null                                    82|         then sha256map."${repo.location}"."${repo.tag}"                                                                           |              ^                                                83|         else null);                                (use '--show-trace' to show detailed location information)

**Comment by 573** [comment]
A little further investigation and some flakes knowledge gained:

>nix flake show --allow-import-from-derivation github:simplex-chat/simplex-chat
github:simplex-chat/simplex-chat/138dc7fe8f8f417a5380600ef459d337b534aa55
├───devShell
│   ├───aarch64-darwin: development environment 'nix-shell'
│   ├───aarch64-linux: development environment 'nix-shell'
│   ├───x86_64-darwin: development environment 'nix-shell'
│   └───x86_64-linux: development environment 'nix-shell'
├───hydraJobs
trace: To make project.plan-nix for haskell-project a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for haskell-project entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: haskell-nix.haskellLib.cleanGit: /nix/store/dcsx7vanhq614yf4v2zkhs402z1dxy48-source does not seem to be a git repository,
assuming it is a clean checkout.

(To proceed if the above is ready with one of the flake "targets" listed, i. e. `nix develop github:simplex-chat/simplex-chat#devShell.x86_64-linux` or `nix build github:simplex-chat/simplex-chat#...`)

This seems to build the world, maybe simplex-chat should use a [cachix](https://www.cachix.org/) instance as binary cache or such ?
