### ISSUE TITLE
[Feature]: Having multiple identity

### ISSUE THREAD

**Issue by mathieujobin** [simplex-chat/simplex-chat#4728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

all

### Feature

When I add a new contact, or create a new link to connect with someone. I have given a choice between using my account main's identity. or creating a randomly generated anonymous one.

could I have more than one identity, so I could reuse a 2nd identity with multiple contacts instead of having all random identity with everybody? I realize this is the point. but... i don't know, sometimes I feel I like to have a 2nd stable username.

thanks

**Comment by epoberezkin** [comment]
You can indeed create another chat profile - see Your chat profiles in settings

**Comment by mathieujobin** [comment]
Indeed, thank you 

How did I miss it
