### ISSUE TITLE
Windows 7 dll missing disaster movie (installation)

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#4850]
I didn't seen a Windows OS since XP.

Three days ago my sister gifted me an old Win 7 notebook that I use for some classroom courses (Google Workspace and bla bla).

I just wanted install SimpleX but it is impossible. During the installation process every time I push "Next" it warns me «it missing bla bla core dll" and so on.

I manually installed at least five dll, but it yet say me "it missing another bla bla dll".

Hey is there a fucking method to update all missing dll with one shot?

The pc is very slow and It is a nightmare.

PS: I am not a developer.

**Comment by imgalaxyhunter** [comment]
I don't think it says anywhere that Windows 7 is supported, but I also don't see anywhere that it says it's *not* supported, so that probably should be clarified.

Is there a reason why you can't just install a Linux distribution? I'm sure it'd help with the speed.

**Comment by migozz** [comment]
Why the heck that anyone bothered that Win7 is not officially supported BY MS?
Total Commander supports Win95. And the author did not write about Win95 is not supported BY MS.
For simplex, no one asked for Win 95, only for Win 7, that is not old enough.
If the W10/11 users don't have their own opinion and do what the corporations tell them to do, that is not the reason to "upgrade".

**Comment by kimg45** [comment]
SImpleX Chat minimum requirements would be nice. Don't think it's reasonable to expect support to go as far back as Windows 7.
