### ISSUE TITLE
[Bug]: Linking QR code from Android app to Linux app doesn't do anything

### ISSUE THREAD

**Issue by toreyes0** [simplex-chat/simplex-chat#4856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux, Android

### OS version

Arch 6.10.8, Android 11

### App version

6.0.4 (both devices)

### Current Behavior

Scanning the QR code to link the mobile app to the Linux app doesn't do anything. It just returns me to the page where the options "Link a mobile" and "Create your profile" are.

For the mobile, after confirming the connection. It goes back to the scanning page with a frozen still of what the camera sees at that time. Pressing back will send me to the same page again while having a new frozen still at that time again. Pressing back again will take me to the default home page of the app.

### Expected Behavior

Some response that shows that I have linked my mobile to the Linux device.

### Steps To Reproduce

1.) Install in devices. (Linux from AppImage file, Android from Play Store)
2.) Connect both devices to the same WiFi connection.
3.) Open mobile app and create profile.
4.) Open desktop app -> use random passphrase -> link a mobile
5.) Scan QR code from mobile -> accept from mobile

### Relevant log output

```shell
~/Downloads $ ./simplex-desktop-x86_64.AppImage
D: useDatabaseKey true
D: sendCmd: apiSetAppFilePaths
D: sendCmd response type cmdOk
D: sendCmd: apiSetEncryptLocalFiles
D: sendCmd response type cmdOk
D: sendCmd: showActiveUser
D: sendCmd response type chatCmdError
D: apiGetActiveUser: chatCmdError chat noActiveUser
D: sendCmd: listRemoteHosts
D: sendCmd response type remoteHostList
D: user: null
D: ChatController startReceiver
D: sendCmd: setLocalDeviceName
D: sendCmd response type cmdOk
D: startChat: started without user
D: sendCmd: startRemoteHost
D: sendCmd response type remoteHostStarted
D: chatRecvMsg: remoteHostSessionCode
D: chatRecvMsg: remoteHostStopped
D: sendCmd: switchRemoteHost
D: sendCmd response type currentRemoteHost
D: sendCmd: listRemoteHosts
D: sendCmd response type remoteHostList
D: sendCmd: showActiveUser
D: sendCmd response type chatCmdError
D: apiGetActiveUser: chatCmdError chat noActiveUser
D: sendCmd: listUsers
D: sendCmd response type usersList
D: sendCmd: apiGetNetworkStatuses
D: sendCmd response type chatCmdError
E: apiGetNetworkStatuses bad response: chatCmdError chat noActiveUser
E: apiGetChats: no current user
D: sendCmd: stopRemoteHost
D: sendCmd response type cmdOk
```

**Comment by pm4rcin** [comment]
Did you open firewall port on desktop?

**Comment by toreyes0** [comment]
Somehow fixed after being invited in a chat group in mobile.
