### ISSUE TITLE
[Feature]: Group descriptions and ability to pin conversations

### ISSUE THREAD

**Issue by Final-Phoenix** [simplex-chat/simplex-chat#4932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

all

### App version

6.0.1

### Feature

Allow us to create short descriptions under the group name

Allow us to pin conversations

Look at Signal messenger for an example of both features

**Comment by kevATin** [comment]
I think that this issue should be reopened, I consider a proper group description and a welcome message to be very different.

The welcome message should be a short "welcome message" that tells the user where to find what. I don't necessarily want the whole set of rules and the latest news and the invitation link to be contained in the welcome message. If it's too long no one is going to bother reading it. 
It could include a few bullet points but tell you to read the group description for more information.

The group description would contain all kinds of information that you want to be quickly and readily available to every user of the group. Rules, news, invitation link, websites, upcoming events, etc.

Sometimes I need some info in the welcome message that has no use being in the group description.

And very often I need some info in the group description that has no place being in the welcome message.

I hope you reconsider this, especially if you plan on supporting bigger communities in the future.

**Comment by kevATin** [comment]
> I understand, but this issue specifically talks about "short descriptions" not long ones, so it might be better to create another issue

Oh so "short descriptions under the group name" was literally meant as something like a subtitle shown under the name, I see. 
I will later create a new issue for this if i cant find an existing one.
