### ISSUE TITLE
[Q]: What am I doing wrong with Install on EndeavourOS ?

### ISSUE THREAD

**Issue by tastyythc** [simplex-chat/simplex-chat#4944]
### Question

Hi all, 

Noob here.
I am trying to follow the steps from the following site to install SimpleX Chat on EndeavourOS 
(https://ipv6.rs/tutorial/EndeavourOS_Latest/SimpleX_Chat/)

After Step 3 : npm install ; I see package-lock.json in the directory via file manager.

upon trying to run the command "npm start" 
I am met with this ERROR : 
 
 `[user@user simplex-chat]$ npm start
npm error code ENOENT
npm error syscall open
npm error path /home/user/simplex-chat/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/user/simplex-chat/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /home/user/.npm/_logs/2024-09-26T07_07_08_366Z-debug-0.log`

There is "package-lock.json" in the directory, however there is not a "package.json" file..

Any help getting SimpleX to run on Endeavour OS would be greatly appreciated! Amongst other tips as well! Please! <3

**Comment by PolarisFx** [comment]
simplex-desktop-bin is on the AUR. That being said only desktop & command line versions are on the AUR so if you specifically want this browser based one just ignore my comment. But if you just want SimpleX chat, AUR is the easiest way.
