### ISSUE TITLE
[Q]: security flaws libssl1.1 dependency needed in simplexchat, deprecated!

### ISSUE THREAD

**Issue by dannyp9000** [simplex-chat/simplex-chat#4973]
### Question

Why does libssl1.1 dependency needed in simplexchat .deb package? I have libssl3 installed. 1.1 has security flaws and no longer maintained, deprecated.

For a security / privacy app I didn't think this would happen. 

https://www.openssl.org/docs/man3.0/man7/migration_guide.html

```
dpkg: dependency problems prevent removal of libssl1.1:amd64:
simplex depends on libssl1.1.

dpkg: error processing package libssl1.1:amd64 (--purge):
dependency problems - not removing
Errors were encountered while processing:
libssl1.1:amd64

**Comment by endless-programmer** [comment]
I'm having the same issue here.

**Comment by gitayam** [comment]
same issue on macos m1 and m2
Error: openssl@1.1 has been disabled because it is not supported upstream! It was disabled on 2024-10-24.

All methods of install do not work except for docker

**Comment by epoberezkin** [comment]
yes, It’s replaced with openssl3.0 in v6.2-beta.1
