### ISSUE TITLE
[Bug]: The exported images can't be opened

### ISSUE THREAD

**Issue by hwyedba4** [simplex-chat/simplex-chat#5168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Windows

### OS version

Windows 10

### App version

6.1.1

### Current Behavior

When I try to open the images in the zip file that I got after I exported the database of my chats all of the images are corrupted. I had tried it before and I think it worked properly in one of the old versions.

### Expected Behavior

I want to be able to see the images
![image](https://github.com/user-attachments/assets/fd955b53-696d-48de-98e3-73429c014fdc)

### Steps To Reproduce

1. export the database
2. unzip the zip file
3. open one of the files in simplex_v1_files folder

**Comment by TalEdd** [comment]
Aren't the the files in simplex_v1_files folder encrypted, you have to save them first before you can view them, if I am not wrong.
