### ISSUE TITLE
[Bug]: can't use custom servers; "use for new connections" is greyed out

### ISSUE THREAD

**Issue by j-lakeman** [simplex-chat/simplex-chat#5222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

Android 14

### App version

6.2-beta.0

### Current Behavior

Custom message as well as media & file servers can be added. However it seems they can't be used for new connections.

### Expected Behavior

custom servers should be usable

### Steps To Reproduce

1. add custom servers
2. tap on it
3. _use for new connections_ is greyed out

**Comment by Bjarne-La** [comment]
Hello John! Have you tried to test the server inside the clients settings after adding it to your server list? Before you can use a server for new connections, the test has to be successful.

**Comment by j-lakeman** [comment]
Damn I’m such an idiot! 🤦‍♂️ 
Thanks, resolved my issue.
