### ISSUE TITLE
[Feature]: Encrypt SDP offer using message protocol

### ISSUE THREAD

**Issue by Striker789** [simplex-chat/simplex-chat#5419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

all

### Feature

SimpleX is doing great work regarding anonymity and has started out well and is competing exceptionally well against other well established platforms. 

Upon reviewing the white papers, it became clear that simplex utilizes WebRTC to establish an encrypted peer to peer connection. However, WebRTC is prone to MITM attacks by insecure signalling severs and this is already well known. To circumvent this issue messengers like signal utilize the Signal protocol for call encryption, while Threema and Wire who also use WebRTC and encrypt their SDP offer to prevent MITM attacks. 
Likewise, Simplex should encrypt SDP exchange to prevent MITM attacks using their messaging protocol.

**Comment by epoberezkin** [comment]
This is already the case - all WebRTC handshake messaging handles over messaging protocol.
