### ISSUE TITLE
an option to show last n messages

### ISSUE THREAD

**Issue by Musickiller** [simplex-chat/simplex-chat#556]
Hi!

Please make an option to display last n messages on startup.

Ways to implement:
1. parameter. Like -lm --last-messages
2. config file in ~/.config/simplex-chat that can be overwritten by parameters
3. config in system folder that can be overwritten by user config and parameters

Sure option 1 is enough for the start, and option 3 seems to serious for a chat app =D

**Comment by epoberezkin** [comment]
there will be a command in v2 (/tail) to display the last n messages, overall or in a given conversation.

**Comment by Musickiller** [comment]
Help file also has to be updated now =)

Also, I think I should create a separate issue to have things like `/help tail` with per-command syntax and usage examples.. No time right now ((

**Comment by epoberezkin** [comment]
Yep, that’s a good idea

**Comment by shumvgolove** [comment]
The feature was implemented in https://github.com/simplex-chat/simplex-chat/commit/2b1ab01efe591f760d092ff5f531d0c136382207
