### ISSUE TITLE
option to hide messages when connection to contact is lost

### ISSUE THREAD

**Issue by Musickiller** [simplex-chat/simplex-chat#557]
Hi again!

Please add a parameter/config option to hide messages when a connection to a contact is lost. It may be OK to show info that connectiont to server is lost though.

Just lots of spam on the laptop on the go =)

Thanks!

**Comment by epoberezkin** [comment]
What’s already done in the latest code - it shows one event per server with all the contacts. It’s about to be released as v2

**Comment by shumvgolove** [comment]
If issue still persist — please reopen.

**Comment by Musickiller** [comment]
I think there is no need to create another issue for it, so I'd like to reopen this one as "need a console option to shorten/hide connection loss messages" =)

**Comment by Musickiller** [comment]
@shumvgolove @epoberezkin or should I create a new issue for that? o_O
