### ISSUE TITLE
SimpleX chat protocol and mobile app MVP

### ISSUE THREAD

**Issue by epoberezkin** [simplex-chat/simplex-chat#60]
- [ ] agent protocol extensions/improvement
  - [ ] message receipts (ACK/RCVD)
  - [x] confirmation/approval steps (CONF/LET)
  - [ ] "small" client-based groups
  - [ ] agents cluster (device sync)
- [ ] chat protocol:
  - [ ] profiles
  - [x] message formats
  - [ ] how agent protocol is used for various chat scenarios
  - [ ] chat groups: protocol to identify and confirm user connections in groups
- [ ] SMP server
  - [x] Websockets support
  - [ ] server deployment: linode and digital ocean
- [x] SMP agent: manage JOIN when the initiating agent is not online
- [ ] terminal UI
  - [ ] upgrade for chat protocol
  - [x] system notifications
- [x] mobile app:
  - [ ] websockets vs TCP decision
  - [ ] app system design (cordova + react)
  - [ ] setup cordova + react app
  - [ ] UX - decide on the flow of profiles and adding contacts
  - [ ] fully private mode (no sharable user profile, as now in the terminal)
  - [ ] chat protocol
  - [ ] IndexDB store: current methods for the agent
  - [ ] IndexDB store: additional methods for chat UI
  - [ ] picture and file transmission: WebRTC or SMP streams?
- [ ] simplexmq-js:
  - [x] SMP protocol (types, parsing/serialization)
  - [ ] SMP agent protocol (types etc)
  - [x] SMP client
  - [ ] SMP agent
  - [x] Abstract transport, WebSockets (?) implementation
  - [x] Abstract cryptography class, WebCrypt implementation
  - [x] Client handshake

**Comment by pleshevskiy** [comment]
@epoberezkin  I have a lot of experience in web development. Particularly with cordova and react. I would be happy to help build a mobile app

**Comment by epoberezkin** [comment]
Hi - great - let’s chat how we can work!

**Comment by epoberezkin** [comment]
@pleshevskiy wrote some thoughts in chat - let's talk via call tomorrow/some other day maybe?

**Comment by pleshevskiy** [comment]
@epoberezkin This week we'll be able to hold a call on Thursday. Next week is tentatively free.

**Comment by Cryptor84** [comment]
Hi @ all,
Can i unstall sympleX Chat for Android too?

**Comment by vsevolod-mineev** [comment]
@Cryptor84 You can run it on Android inside Termux like this: https://github.com/vsevolod-mineev/simplex-aarch64-termux

**Comment by Cryptor84** [comment]
Hi,IT,s all in english,Doesn,t Unserstand how to install simplex-chat on my Android xiaomi redmi Note 10-5g Phone!!!???I need Tutorial in German,please!!Pls Feedback,F.Harner--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 20.01.22, 19:10 schrieb "Vsevolod (Sebastian) Mineev" ***@***.***>:

   
  @Cryptor84 You can run it on Android inside Termux like this: https://github.com/vsevolod-mineev/simplex-aarch64-termux
