### ISSUE TITLE
Support for older iOS versions?

### ISSUE THREAD

**Issue by S-NA** [simplex-chat/simplex-chat#619]
Is there a reason why the iOS app requires iOS 15? Such as using APIs specific to iOS 15? If not, could the minimum deployment target be lowered to iOS 14 or older? At the moment iOS 15 is a limit for some users due to it having no functioning jailbreaks. This has unfortunately been a common issue I have run into when trying to have other people download the iOS app.

**Comment by epoberezkin** [comment]
This is non-trivial as some things that are simple with iOS 15 SwiftUI, require quite a bit of code for iOS 14 - so it’s not just changing the setting in the app…

The reasoning behind it was that all devices from iPhone 6S (or 7?) can in theory run iOS 15, but we didn’t consider all the factors it seems.

We will put it into the roadmap.

**Comment by epoberezkin** [comment]
We will not be prioritising older iOS support for now, sorry. iOS 15 has many high level solutions that would require a lot of development work. We will re-assess it at a later point, closing for now.
