### ISSUE TITLE
Encrypt simplex_XX_agent.db and simplex_XX_chat.db

### ISSUE THREAD

**Issue by ncoder-1** [simplex-chat/simplex-chat#637]
Are there any plans to allow for data-at-rest encryption of both `simplex_XX_agent.db` and `simplex_XX_chat.db`, perhaps with a user key, biometric or hardware token (such as a Yubikey) when the client loads?

**Comment by epoberezkin** [comment]
Agreed - it's important - and it's in [the roadmap](https://github.com/simplex-chat/simplex-chat#roadmap). Do you think it should be prioritised higher?

**Comment by ncoder-1** [comment]
It might be a good idea if you want faster mass adoption, that way you'd have both data-at-rest and end-to-end encryption.

**Comment by blueice777** [comment]
any update about this improvement? this is important

**Comment by epoberezkin** [comment]
this is now released in v4 - see the release announcement: https://github.com/simplex-chat/simplex-chat/blob/stable/blog/20220928-simplex-chat-v4-encrypted-database.md
