### ISSUE TITLE
Using a translation platform

### ISSUE THREAD

**Issue by StoyanDimitrov** [simplex-chat/simplex-chat#641]
Have you ever thought about using a translation platform to handle app translations?

I can warmly recommend [Weblate](https://hosted.weblate.org). It is provided free of charge for FLOSS projects.

Weblate itself is FLOSS too. It is a home for many well known open source projects like F-Droid, OsmAnd, KOReader, DAVx5, Tasks.org, AndrOBD, Minetest, Orbot, Freedombox, and many, many others.

After the initial project setup it is a matter of a `push` to send new strings to translators and a `pull` to get the latest translated strings back. That's the manual mode…

<details>
The project has to apply for the service, providing some data proving FOSS license and such but is simple and for about a week the application (let's hope for) is approved. While the application is being reviewed the project is accessible to translators with a warning at the top of the page explaining that the project is not approved yet.
</details>

I'm asking because I'm interested in translating SimpleX and this will greatly improve translators' workflow and onboarding for the project. Plus, Weblate handles fastlane meta too.

**Comment by epoberezkin** [comment]
Looking at their configuration... The initial setup is non-trivial...

**Comment by StoyanDimitrov** [comment]
Can you elaborate further? What are the pain points? Is it something specific to SimpleX chat?

Weblate has support for [Apple iOS strings](https://docs.weblate.org/en/latest/formats.html#apple) as well as [Android string resources](https://docs.weblate.org/en/latest/formats.html#aresource).

**Comment by comradekingu** [comment]
@epoberezkin Happy to help.
Do you intend to use your own platform, or maybe
https://weblate.bubu1.eu/ or https://hosted.weblate.org/hosting/ ?
I am "kingu" on the latter two.

**Comment by lodart** [comment]
I would be happy to help translating to french 🥖 😃

**Comment by epoberezkin** [comment]
weblate is configured and French language is half done there already :) @lodart

**Comment by sith-on-mars** [comment]
Is there any progress on translation? I'm happy to do the simplified Chinese translation!

**Comment by shuvashish76** [comment]
https://hosted.weblate.org/projects/simplex-chat/

**Comment by sith-on-mars** [comment]
> https://hosted.weblate.org/projects/simplex-chat/

Cheers! This should have been on the Github page.

**Comment by comradekingu** [comment]
@sith-on-mars Creating new locales is turned off, so I can't translate nb_NO (Norwegian Bokmål).

**Comment by sith-on-mars** [comment]
> @sith-on-mars Creating new locales is turned off, so I can't translate nb_NO (Norwegian Bokmål).

I requested the translation of new locale, now waiting for the approval.

**Comment by epoberezkin** [comment]
@sith-on-mars thank you! Now that we've added French, and figured out how to use Weblate, we can manage it – I've just added the languages. It's a major effort - thank you - please connect in the chat and let me know any questions!

**Comment by sith-on-mars** [comment]
> @sith-on-mars thank you! Now that we've added French, and figured out how to use Weblate, we can manage it – I've just added the languages. It's a major effort - thank you - please connect in the chat and let me know any questions!

No worries I’m glad I can help. For some reasons the languages you added seemed to disappear. I was doing the Chinese translation before and now is not there anymore and I’m not sure if the progress is lost.
