### ISSUE TITLE
Simplex-chat should follow system proxy configuration

### ISSUE THREAD

**Issue by kheops2713** [simplex-chat/simplex-chat#645]
Starting `simplex-chat` in a terminal on Linux with the variables `https_proxy` et `http_proxy` (also in uppercase) set to a proxy address, it still connects directly to the SMP servers. No possibility of using proxies appears in the help messages so I am assuming this is not implemented.

SMP connection is I guess not technically considered HTTPS, so maybe these specific variables are not the best choice, but it would be great if `simplex-chat` could somehow follow system proxy configuration for all outbound connections.

**Comment by epoberezkin** [comment]
I think it should be possible to configure it on TCP level. SMP is definitely not HTTP traffic, and most likely it won’t work correctly via HTTP proxy - you need to proxy all TCP traffic

**Comment by kheops2713** [comment]
An HTTP proxy that accepts `CONNECT` should be transparent to any kind of TCP trafic, but of course it needs to allow SMP ports. A support for SOCKS5 would otherwise be great too!

**Comment by epoberezkin** [comment]
I might be terribly wrong, but I think I was always configuring it on the system level, and the application doesn't need to be changed to use proxy... I will review it again.

**Comment by kheops2713** [comment]
I also tried setting the `all_proxy` environment variable, with no effect.

**Comment by epoberezkin** [comment]
Trying to change it via environment variable still puts the responsibility for using proxy on the app, some apps may use it and some would not… I will look into how to configure it on the system level.

**Comment by epoberezkin** [comment]
It has SOCKS5 proxy support now
