### ISSUE TITLE
fr(mark-as-read): extend sdk to easily mark all messages in a chat as read

### ISSUE THREAD

**Issue by tomquas** [simplex-chat/simplex-chat#647]
actual: /_read chat @x from=y to=z

wish list: /_read @chat @x

as discussed before, it would be convenient for app developers to not go through the the hassle of reading chat stats for @x... fetch it... iterate through chat item ids to find the latest id, aka to=z

this could easily be solved with a single sql update statement and would add much convenience.

**Comment by epoberezkin** [comment]
done
