### ISSUE TITLE
Async tasks not running in iOS simulator until "kicked"

### ISSUE THREAD

**Issue by jmatsushita** [simplex-chat/simplex-chat#731]
Hi there,

First issue on this repo, and just wanted to say, it's awesome that there's an app using Haskell code as a library in mobile apps. There used to be esoteric and out of date knowledge about this, but thanks to awesome folks like zw3rk angerman and you guys, we have a chance to use Haskell in more places. That's so cool! 

I'm running into an issue on my M1 Mac after the following:
```
# creating the build product
nix build .#aarch64-darwin-ios:lib:simplex-chat 
# run the preparation scripts (having mac2ios in the nix flake would be awesome!)
scripts/ios/prepare.sh
# Some fiddling with the XCode library to point to the new `*.a` files in the Libraries/sim folder
```

After this, I'm able to start the app with XCode in the simulator, but there's a weird bug where if I click the send message button, nothing happens. In the log I only get:
```
2022-06-05 16:26:54.378204+0200 SimpleX[88158:13656984] ChatView sendMessage
```  
And if I debug into the ComposeView and add breakpoints I see that I [never reach inside the `Task`](https://github.com/simplex-chat/simplex-chat/blob/stable/apps/ios/Shared/Views/Chat/ComposeMessage/ComposeView.swift#L286).

However, if I send a message from the App store build on an iOS device to the simulator build, then it seems to "wake up" the Task scheduler, I then see the received message arrive, and each attempt to click the send button on the simulator app, appears with a timestamp:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/356097/172055772-5ec7ea5d-d579-420c-9409-59eed44f28a0.png">

And the logs do show the `in Task` message.

Not sure what's going on, but I thought I'd report it :)

**Comment by epoberezkin** [comment]
@jmatsushita btw, to try to reproduce in sim - how did you make a connection? What simulator are you using?

**Comment by epoberezkin** [comment]
closing
