### ISSUE TITLE
Missing guidance to build libsimplex.so

### ISSUE THREAD

**Issue by ldoublewood** [simplex-chat/simplex-chat#734]
building android mobile app failed as below:
./gradlew assembleDebug                                        
                                                                                                                                   
> Task :app:buildCMakeDebug[arm64-v8a] FAILED                                                                                      
C/C++: ninja: error: '/work/simplex-chat/apps/android/app/src/main/cpp/libs/arm64-v8a/libsimplex.so', needed by '/work/simplex-chat/apps/android/app/build/intermediates/cxx/Debug/2q591w3h/obj/arm64-v8a/libapp-lib.so', missing and no known rule to make it

according to author's description, the native lib (libsimplex.so etc.) building is quite complicated, however I can not find any document to describe such building steps, could you please provide such document?

**Comment by epoberezkin** [comment]
You need to use nix to build it, the config is in scripts folder.

**Comment by umarmnaq** [comment]
> You need to use nix to build it, the config is in scripts folder.

@epoberezkin Please give more information. I am a bit new to android development, and would like to develop on this awesome project. But getting the same error
