### ISSUE TITLE
Android App: Sent image in chat crashes app

### ISSUE THREAD

**Issue by dkathmann** [simplex-chat/simplex-chat#805]
Device: Huawei Mate 10 Pro
Android version: 10
App version: v3.0 (43) from Playstore

I sent an image over the Android app to a contact and the app crashed. I could open the app again but it crashed every time I tried to open the chat histroy of this contact. I could solve this whit clearing the history for the contact. My contact had the same problem and the same fix worked.

Kind regards.

**Comment by epoberezkin** [comment]
it's a shame you cleared the chat... could you maybe reproduce the issue with the same file on a clean chat profile (you could export your current one, delete it and create new, and then reimport your current one back) and export the database so we could investigate?

I suspect the issue could be a file format - but it would be great if we could reproduce...

**Comment by epoberezkin** [comment]
Thank you! We will be investigating

**Comment by epoberezkin** [comment]
The fix is released in 3.0.1 (in review in play store now)
