### ISSUE TITLE
Android share menu doesn't show SimpleX entry. 

### ISSUE THREAD

**Issue by eqniz** [simplex-chat/simplex-chat#807]
You can not share files directly via the default Android share menu. SystemX just has no entry in there. You are forced to share it via the SimpleX app.

Is this intended or a bug?

I use GrapheneOS with the f-droid version. No google play services.

**Comment by epoberezkin** [comment]
> Is this intended or a bug?

It's neither, it simply wasn't implemented yet. We will add it at some point.

**Comment by mika-nl** [comment]
It is working in 4.1
