### ISSUE TITLE
[BUG?] Private notifications on GrapheneOS

### ISSUE THREAD

**Issue by eqniz** [simplex-chat/simplex-chat#813]
After talking to the dev(s) on SimpleX chat itself through their official profile. I had some issues with "Private notifications" working on GrapheneOS. https://grapheneos.org  / Android 12.

So, notifications seem to work even with battery set to "optimized" - BUT - the app has to be open in the background. When it is closed, it does not work and I will not get any notifications. So far, so good. That seems intended, right?

When battery is set to "unrestricted" without enabling "Private notifications" in the app then it does actually nothing. Same behaviour as with "optimized". This also seems intended? 
But it would somehow make sense to make it work when somebody set it to "unrestricted on their own without going the route through the app option, I guess. 

But when I enable "Private notifications" in the app, it leads me to the popups on what to do etc. I then "allow" the app (which is the battery setting "unrestricted"). The problem here is, that it does not start the silent notification "service" in the background when the app is closed. It keeps working when the app is opened in background, as it does with the other settings too. But once closed, it doesn't work anymore. 

I had to manually set battery setting back to "optimized" and then disable/re-enable "Private notifications" in the app. Then it somehow started the background service. BUT, this did not work every time for 100%. I tried that a couple of times and sometimes I had to do these steps 2-3 times in a row to get it working. And one time I did a reboot and only after that it started working. 

So, as per request by that nice person I talked to in the simplex chat. I opened this Issue here, so you guys don't forget to fix it. ;-)

**Comment by avently** [comment]
Please, check the behavior you described in currently released version.
I made some improvements here:  https://github.com/simplex-chat/simplex-chat/pull/942

**Comment by shumvgolove** [comment]
If issue still persist — please reopen.
