### ISSUE TITLE
Documentation / How to use --execute switch?

### ISSUE THREAD

**Issue by andersaamodt** [simplex-chat/simplex-chat#890]
Is there any documentation on the --execute switch? When I try to use it to execute a command, for example `simplex-chat --execute "/g newgroup"`, it says `error: chat not started`.

I am looking for a way to run arbitrary simplex-chat commands from the command line, so I can automate adding contacts and joining and leaving groups.

**Comment by epoberezkin** [comment]
That might be a bug, let me have a look.

You can also look into chat-bot to do that - either as Haskell app or via web socket API (the latter not well documented yet, but there is an example).

**Comment by epoberezkin** [comment]
it's a bug, will be fixed in the next release (today/tomorrow), or you can compile from source from the pr if you need it urgently.
