### ISSUE TITLE
send message via bash?

### ISSUE THREAD

**Issue by prankousky** [simplex-chat/simplex-chat#917]
Hi everybody,

I just installed `SimpleX Chat v3.1.0` through the Arch Linux `AUR`. I created an address on my PC and one on my android device. After connecting them, messaging between those devices works fine.

However, I was wondering whether it was possible to do *something like* 

```
echo "@<contact> <message>"  | simplex-chat
# or
simplex-chat << echo "@<contact> <message>"
```

This would allow users to use `cron` to send messages automatically, or easily integrate `SimpleX` into something like `Home Assistant`. I wasn't able to find information on this, but perhaps / hopefully I just missed it :)

Thank you in advance for information.

**Comment by opensource21** [comment]
This combined with a client for raspbian on raspberry pi would be great.

**Comment by epoberezkin** [comment]
Yes, it’s supported with CLI option -e and you can use -t to increase the execution time if message fails to deliver in default 3 seconds.

Run `simplex-chat -h` for more info

**Comment by epoberezkin** [comment]
Btw the latest version is 4.x - please upgrade if you can

**Comment by shumvgolove** [comment]
If issue still persist — please reopen.
