### ISSUE TITLE
Feature request - ability to shut off or shutdown

### ISSUE THREAD

**Issue by kavemang** [simplex-chat/simplex-chat#941]
Hi everyone, i tried out simplex with a friend and found i could not really get it to go to sleep / stay shut down

I tried using the DB disconnect but sooner or later it wakes back up 

The result is that even if im not testing/touching simplex for days it uses more or comparable battery to element or whatsapp which im actually using to chat during that time period

**Comment by epoberezkin** [comment]
Right now there is a bug we are fixing. If you disable "notification service" it should not really start again, but it appears there might be a bug when it does - sorry!

Or, do you have notifications service enabled?

**Comment by shumvgolove** [comment]
If issue still persist — please reopen.

**Comment by theAkito** [comment]
Same problem here. It constantly wakes up.

**Comment by CherrieTheShifter** [comment]
Yes This
